import assert from 'node:assert/strict';
import test from 'node:test';
import { DETERMINISTIC_PROOFS, IMPOSSIBLE_PROBE, PUBLIC_PLAYTEST_MANIFEST, manifestDigest, roleGate, runPublicPlaytest, sanitizeReport, stopOwnedServer } from '../public-playtest.mjs';

test('public playtest manifest is stable 20–30 named turns', () => { assert.equal(PUBLIC_PLAYTEST_MANIFEST.length, 25); assert.equal(new Set(PUBLIC_PLAYTEST_MANIFEST.map((turn) => turn.id)).size, 25); assert.match(manifestDigest(), /^[a-f0-9]{64}$/u); });
test('fire affect requires the real world-process role after deterministic start', () => { const [start, affect] = PUBLIC_PLAYTEST_MANIFEST; assert.equal(start.id, 'fire-start'); assert.equal(affect.id, 'fire-affect'); assert.deepEqual(affect.required_role_ids, ['turn_step_planner', 'world_process_step']); });
test('ordinary narration gates live writer then auditor, never repair', () => { const expected = ['gameplay_narrator', 'gameplay_narrator_auditor']; const ordinary = ['ordinary-use', 'carry'].map((id) => PUBLIC_PLAYTEST_MANIFEST.find((turn) => turn.id === id)); for (const turn of ordinary) assert.deepEqual(turn.required_waterfall, expected); const report = { observed_role_ids: [], turns: [{ turn_id: 'ordinary', scenario_class: 'free_form', status: 200, required_waterfall: expected, role_ids: expected, llm: { turn_duration_ms: 1, aggregate: { repair_calls: 0 }, waterfall: expected.map((role) => ({ role })) } }] }; assert.equal(roleGate(report).gaps.some((gap) => gap.includes('missing live waterfall')), false); report.turns[0].llm.waterfall = report.turns[0].llm.waterfall.slice(0, 1); assert.ok(roleGate(report).gaps.includes('missing live waterfall: ordinary: gameplay_narrator_auditor')); });
test('repair paths remain deterministic proofs, never live waterfall claims', () => { assert.deepEqual(DETERMINISTIC_PROOFS.map(({ id, proof_kind, test }) => [id, proof_kind, test]), [['narration-audit-failure-before-commit', 'deterministic_focused_test', 'apps/game-server/test/lower-dvina-trace-precommit-narration-failure.test.js#required precommit narration failures reject before factual commit'], ['deadline-exhaustion-before-commit', 'deterministic_focused_test', 'apps/game-server/test/lower-dvina-trace-turn-budget-boundary.test.js#pre-commit reserve blocks phase 2 repository commit'], ['narration-localized-semantic-repair', 'deterministic_focused_test', 'packages/narration/test/narration-flow.test.js#repairs only auditor-flagged segment and re-audits complete prose'], ['cross-workflow-gameplay-repairs', 'deterministic_focused_test', 'apps/game-server/test/llm-turn-budget.test.js#cross-workflow gameplay repairs execute, duplicate repair is blocked before provider']]); assert.equal(PUBLIC_PLAYTEST_MANIFEST.some((turn) => turn.required_waterfall?.some((role) => role.includes('repair'))), false); const safe = sanitizeReport({ deterministic_proofs: DETERMINISTIC_PROOFS, gates: { pass: true, gaps: [], live_waterfalls: true, deterministic_proofs: DETERMINISTIC_PROOFS } }); assert.equal(safe.gates.live_waterfalls, true); assert.deepEqual(safe.gates.deterministic_proofs, DETERMINISTIC_PROOFS); assert.equal(JSON.stringify(safe.gates).includes('live_observed'), false); });
test('sanitizer uses strict public and diagnostic allowlists', () => { const safe = sanitizeReport({ api_key: 'secret', git: cleanGit(), public_responses: { turn: { status: 200, ok: true, data: { party_id: 'p', prose: 'hidden', turn: { turn_id: 't', mode: 'attention', summary: { outcome: 'not-a-code' } } } } }, turns: [{ turn_id: 'x', public_evidence: { expected: 'blue_wool_found', pass: false, prose: 'hidden' }, response: { status: 200, ok: true, data: { party_id: 'p', message: 'hidden' } }, llm: { turn_duration_ms: 4, turn_deadline_ms: 10, waterfall: [{ role: 'turn_step_planner', duration_ms: 4, provider_payload: 'hidden' }], aggregate: { llm_calls: 1, deadline_exceeded: true, secret: 'hidden' } } }] }); assert.equal(safe.public_responses.turn.domain_outcome_code, undefined); assert.deepEqual(safe.turns[0].public_evidence, { expected: 'blue_wool_found', pass: false }); assert.equal(safe.turns[0].llm.aggregate.deadline_exceeded, true); assert.equal(safe.turns[0].llm.waterfall[0].provider_payload, undefined); assert.equal(safe.turns[0].response.message, undefined); });
test('impossible 2xx requires public commit and planner observation', () => { const incomplete = roleGate({ observed_role_ids: [], turns: [{ turn_id: IMPOSSIBLE_PROBE.id, status: 200, expected_failure: true, response: {}, role_ids: [], llm: { turn_duration_ms: 1, turn_deadline_ms: 10, aggregate: { repair_calls: 0 } } }] }); assert.ok(incomplete.gaps.includes('impossible probe has no public committed turn: impossible-jump')); assert.ok(incomplete.gaps.includes('impossible probe planner not observed: impossible-jump')); const response = sanitizeReport({ turns: [{ response: traceTurn() }] }).turns[0].response; assert.equal(response.turn_id, 'turn-trace-1'); const observed = roleGate({ observed_role_ids: [], turns: [{ turn_id: IMPOSSIBLE_PROBE.id, status: 200, expected_failure: true, response, role_ids: ['turn_step_planner'], llm: { turn_duration_ms: 1, turn_deadline_ms: 10, aggregate: { repair_calls: 0 } } }] }); assert.equal(observed.gaps.some((gap) => gap.includes('impossible probe')), false); assert.equal(observed.deterministic_proofs.some(({ id }) => id === 'narration-audit-failure-before-commit'), true); });
test('deadline gate uses authoritative ceiling and LLM diagnostics, not client duration', () => { const withinDeadline = roleGate({ observed_role_ids: [], turns: [{ turn_id: 'x', status: 200, client_duration_ms: 99_999, llm: { turn_duration_ms: 1, turn_deadline_ms: 10, aggregate: { repair_calls: 0 } } }] }); assert.equal(withinDeadline.gaps.includes('deadline exceeded: x'), false); const ceilingExceeded = roleGate({ observed_role_ids: [], turns: [{ turn_id: 'ceiling', status: 200, llm: { turn_duration_ms: 30_000, turn_deadline_ms: 60_000, aggregate: { repair_calls: 0 } } }] }); assert.ok(ceilingExceeded.gaps.includes('deadline exceeded: ceiling')); const reportedExceeded = roleGate({ observed_role_ids: [], turns: [{ turn_id: 'y', status: 200, llm: { turn_duration_ms: 1, turn_deadline_ms: 60_000, aggregate: { repair_calls: 0, deadline_exceeded: true } } }] }); assert.ok(reportedExceeded.gaps.includes('deadline exceeded: y')); });
test('runner snapshots clean exact git before starting', async () => { let started = false; for (const git of [() => ({ head: 'short', dirty: false }), () => ({ head: 'a'.repeat(40), dirty: true })]) await assert.rejects(() => runPublicPlaytest({ git, start: async () => { started = true; } }), { code: 'PUBLIC_PLAYTEST_GIT_EVIDENCE_INVALID' }); assert.equal(started, false); });
test('runner reads diagnostics before pending ack and retains both attempts', async () => { const responses = [health(), catalog(), newGame(), ack(), pendingTurn(), diagnostics({ duration: 15_000, deadline: 60_000, role: 'turn_step_planner', repairCalls: 1, llmCalls: 2 }), turn(), diagnostics({ duration: 15_000, deadline: 60_000, role: 'turn_step_presenter', llmCalls: 1, budgetExhausted: true })]; const requests = []; await assert.rejects(() => runPublicPlaytest({ manifest: evidenceFirstManifest(), impossibleProbe: IMPOSSIBLE_PROBE, git: cleanGit, start: localStart, fetchImpl: async (url, request) => { requests.push({ url, body: request.body && JSON.parse(request.body) }); return responses.shift(); }, now: counter(), log() {} }), (error) => { const turn = error.report.turns[0]; assert.equal(turn.presentation_ack.screen_status, 'ready'); assert.deepEqual(turn.role_ids, ['turn_step_planner', 'turn_step_presenter']); assert.equal(turn.llm.turn_duration_ms, 30_000); assert.equal(turn.llm.aggregate.repair_calls, 1); assert.equal(turn.llm.aggregate.llm_calls, 3); assert.equal(turn.llm.aggregate.budget_exhausted, true); assert.deepEqual(turn.llm.attempts.map((attempt) => attempt.turn_deadline_ms), [60_000, 60_000]); assert.ok(error.report.gates.gaps.includes('deadline exceeded: probe-0')); return true; }); assert.match(requests[5].url, /developer\/llm-turn-reports/); assert.match(requests[6].url, /\/turns$/); assert.match(requests[7].url, /developer\/llm-turn-reports/); assert.deepEqual(requests[4].body, requests[6].body); });
test('runner skips presentation acknowledgement when turn is ready', async () => { const responses = [health(), catalog(), newGame(), ack(), turn(), diagnostics()]; const bodies = []; await assert.rejects(() => runPublicPlaytest({ manifest: evidenceFirstManifest(), impossibleProbe: IMPOSSIBLE_PROBE, git: cleanGit, start: localStart, fetchImpl: async (_url, request) => { if (request.body) bodies.push(JSON.parse(request.body)); return responses.shift(); }, now: counter(), log() {} }), (error) => { assert.equal(error.report.turns[0].presentation_ack.status, 0); return true; }); assert.equal(bodies.length, 3); });
test('runner rejects repeated pending presentation with typed local failure', async () => { const responses = [health(), catalog(), newGame(), ack(), pendingTurn(), diagnostics(), pendingTurn(), diagnostics()]; await assert.rejects(() => runPublicPlaytest({ manifest: testManifest(), impossibleProbe: IMPOSSIBLE_PROBE, git: cleanGit, start: localStart, fetchImpl: async () => responses.shift(), now: counter(), log() {} }), (error) => { assert.equal(error.code, 'PUBLIC_PLAYTEST_PRESENTATION_PENDING'); assert.deepEqual(error.report.turn_failure, { turn_id: 'probe-0', code: 'PUBLIC_PLAYTEST_PRESENTATION_PENDING', http_status: null, public_error_code: null }); assert.equal(error.report.turns[0].presentation_pending, true); assert.equal(error.report.turns[0].llm.attempts.length, 2); return true; }); });
test('runner reports failed presentation acknowledgement without unsafe payload', async () => { const responses = [health(), catalog(), newGame(), ack(), pendingTurn(), diagnostics(), { ok: false, status: 503, json: async () => ({ ok: false, error: { code: 'PRESENTATION_DOWN', message: 'do not retain' } }) }]; await assert.rejects(() => runPublicPlaytest({ manifest: testManifest(), impossibleProbe: IMPOSSIBLE_PROBE, git: cleanGit, start: localStart, fetchImpl: async () => responses.shift(), now: counter(), log() {} }), (error) => { assert.deepEqual(error.report.turn_failure, { turn_id: 'probe-0', code: 'PUBLIC_HTTP_FAILED', http_status: 503, public_error_code: 'PRESENTATION_DOWN' }); assert.equal(JSON.stringify(error.report).includes('do not retain'), false); return true; }); });
test('runner retains partial turns when a later turn fails', async () => { const responses = [health(), catalog(), newGame(), ack(), turn(), diagnostics(), { ok: false, status: 503, json: async () => ({ ok: false }) }]; const manifest = testManifest(); await assert.rejects(() => runPublicPlaytest({ manifest, impossibleProbe: IMPOSSIBLE_PROBE, git: cleanGit, start: async () => ({ url: 'http://local', child: { exitCode: 0, kill() {} } }), fetchImpl: async () => responses.shift(), now: counter(), log() {} }), (error) => { assert.ok(error.report, error.message); assert.deepEqual(error.report.git, cleanGit()); assert.equal(error.report.turns.length, 1); assert.equal(error.report.turn_failure.turn_id, 'probe-1'); return true; }); });
test('runner retains only safe status and public error code from failed turn', async () => { const responses = [health(), catalog(), newGame(), ack(), turn(), diagnostics(), { ok: false, status: 503, json: async () => ({ ok: false, error: { code: 'SAFE_CODE', message: 'do not retain' } }) }]; const manifest = testManifest(); await assert.rejects(() => runPublicPlaytest({ manifest, impossibleProbe: IMPOSSIBLE_PROBE, git: cleanGit, start: async () => ({ url: 'http://local', child: { exitCode: 0, kill() {} } }), fetchImpl: async () => responses.shift(), now: counter(), log() {} }), (error) => { assert.deepEqual(error.report.turn_failure, { turn_id: 'probe-1', code: 'PUBLIC_HTTP_FAILED', http_status: 503, public_error_code: 'SAFE_CODE' }); assert.equal(JSON.stringify(error.report).includes('do not retain'), false); return true; }); });
test('runner uses deterministic identities and stops on missing public causal evidence', async () => { const responses = [health(), catalog(), newGame(), ack(), turn(), diagnostics()]; const bodies = []; await assert.rejects(() => runPublicPlaytest({ manifest: PUBLIC_PLAYTEST_MANIFEST.slice(2), git: cleanGit, branch: 7, start: async () => ({ url: 'http://local', child: { exitCode: 0, kill() {} } }), fetchImpl: async (_url, request) => { if (request.body) bodies.push(JSON.parse(request.body)); return responses.shift(); }, now: counter(), log() {} }), (error) => { assert.equal(error.code, 'PUBLIC_PLAYTEST_CAUSAL_EVIDENCE_MISSING'); assert.equal(error.report.run_seed, `public-playtest:${'a'.repeat(40)}:branch:7`); assert.equal(error.report.turns.length, 1); assert.deepEqual(error.report.turns[0].public_evidence, { expected: 'blue_wool_found', pass: false }); return true; }); assert.equal(bodies[0].request_id, `public-playtest:${'a'.repeat(40)}:branch:7`); assert.equal(bodies[2].request_id, `public-playtest:${'a'.repeat(40)}:branch:7:inspect`); assert.equal(bodies[2].idempotency_key, bodies[2].request_id); });
test('runner stops at surrender when public marker is absent', async () => { const responses = [health(), catalog(), newGame(), ack(), turn(), diagnostics()]; const bodies = []; await assert.rejects(() => runPublicPlaytest({ manifest: surrenderFirstManifest(), impossibleProbe: IMPOSSIBLE_PROBE, git: cleanGit, start: async () => ({ url: 'http://local', child: { exitCode: 0, kill() {} } }), fetchImpl: async (_url, request) => { if (request.body) bodies.push(JSON.parse(request.body)); return responses.shift(); }, now: counter(), log() {} }), (error) => { assert.equal(error.code, 'PUBLIC_PLAYTEST_CAUSAL_EVIDENCE_MISSING'); assert.equal(error.report.turn_failure.turn_id, 'surrender'); assert.deepEqual(error.report.turns[0].public_evidence, { expected: 'ratsha_surrendered', pass: false }); return true; }); assert.equal(bodies.some(({ raw_text }) => raw_text === 'Оказать Онисиму первую помощь.'), false); });
test('manifest role evidence reports compound prerequisite gaps', () => { const gate = roleGate({ observed_role_ids: [], turns: [{ turn_id: 'rest', required_role_ids: ['turn_step_planner', 'npc_autonomous_decider'], role_ids: ['turn_step_planner'], status: 200, llm: { turn_duration_ms: 1, turn_deadline_ms: 10, aggregate: { repair_calls: 0 } } }] }); assert.ok(gate.gaps.includes('missing compound prerequisite: rest: npc_autonomous_decider')); });
test('ordinary discovery requires local planner and materialization evidence', () => { const turn = PUBLIC_PLAYTEST_MANIFEST.find(({ id }) => id === 'ordinary-discovery'); assert.deepEqual(turn.required_role_ids, ['turn_step_planner', 'ordinary_materialization']); const camp = PUBLIC_PLAYTEST_MANIFEST.findIndex(({ id }) => id === 'camp'); const discovery = PUBLIC_PLAYTEST_MANIFEST.findIndex(({ id }) => id === 'ordinary-discovery'); const use = PUBLIC_PLAYTEST_MANIFEST.findIndex(({ id }) => id === 'ordinary-use'); const route = PUBLIC_PLAYTEST_MANIFEST.findIndex(({ id }) => id === 'route'); assert.ok(camp < discovery && discovery < use && use < route); const gate = roleGate({ observed_role_ids: [], turns: [{ turn_id: turn.id, required_role_ids: turn.required_role_ids, role_ids: ['turn_step_planner'], status: 200, llm: { turn_duration_ms: 1, turn_deadline_ms: 10, aggregate: { repair_calls: 0 } } }] }); assert.ok(gate.gaps.includes('missing compound prerequisite: ordinary-discovery: ordinary_materialization')); });
test('runner fails partial report when git snapshot changes during run', async () => { const responses = [health(), catalog(), newGame(), ack(), turn(), diagnostics(), { ok: false, status: 503, json: async () => ({ ok: false }) }]; const manifest = testManifest(); let calls = 0; await assert.rejects(() => runPublicPlaytest({ manifest, impossibleProbe: IMPOSSIBLE_PROBE, git: () => ++calls === 1 ? cleanGit() : { head: 'b'.repeat(40), dirty: false }, start: async () => ({ url: 'http://local', child: { exitCode: 0, kill() {} } }), fetchImpl: async () => responses.shift(), now: counter(), log() {} }), (error) => { assert.equal(error.code, 'PUBLIC_PLAYTEST_GIT_SNAPSHOT_CHANGED'); assert.deepEqual(error.report.git_after, { head: 'b'.repeat(40), dirty: false }); return true; }); });
test('owned server waits for SIGTERM then uses SIGKILL fallback', async () => { const signals = []; await stopOwnedServer({ exitCode: null, kill(signal) { signals.push(signal); }, once() {} }, { timeoutMs: 1, sleep: async () => {} }); assert.deepEqual(signals, ['SIGTERM', 'SIGKILL']); });
function cleanGit() { return { head: 'a'.repeat(40), dirty: false }; }
function testManifest() { return PUBLIC_PLAYTEST_MANIFEST.map(({ expect: _expect, ...turn }, index) => ({ ...turn, id: `probe-${index}` })); }
function evidenceFirstManifest() { const manifest = testManifest(); return [{ ...manifest[0], expect: 'blue_wool_found' }, ...manifest.slice(1)]; }
function surrenderFirstManifest() { const surrender = PUBLIC_PLAYTEST_MANIFEST.find(({ id }) => id === 'surrender'); return [surrender, ...PUBLIC_PLAYTEST_MANIFEST.filter(({ id }) => id !== 'surrender')]; }
function counter() { let value = 0; return () => ++value; }
const localStart = async () => ({ url: 'http://local', child: { exitCode: 0, kill() {} } });
function json(data) { return async () => ({ ok: true, data }); }
function health() { return { ok: true, status: 200, json: json({ status: 'ok' }) }; }
function catalog() { return { ok: true, status: 200, json: json({ scenarios: [{ scenario_id: 'lower_dvina_trace_v1', available: true }] }) }; }
function newGame() { return { ok: true, status: 201, json: json({ party_id: 'party-1' }) }; }
function ack() { return { ok: true, status: 200, json: json({ party_id: 'party-1' }) }; }
function traceTurn() { return { status: 200, ok: true, data: { party_id: 'party-1', state_version: 7, option_id: 'wait', screen: { turn_id: 'turn-trace-1', turn_number: 1, screen_status: 'ready' } } }; }
function turn() { return { ok: true, status: 200, json: json({ party_id: 'party-1', turn: { turn_id: 'turn-1', status: 'resolved', mode: 'attention' }, screen: { schema: 'turn_screen', version: 1, screen_status: 'ready' } }) }; }
function pendingTurn() { return { ok: true, status: 200, json: json({ party_id: 'party-1', schema: 'turn_screen', version: 1, screen_status: 'committed_presentation_pending', turn: { turn_id: 'turn-1', status: 'resolved', mode: 'attention' } }) }; }
function diagnostics({ duration = 1, deadline = 10, role = null, repairCalls = 0, llmCalls = 0, budgetExhausted = false } = {}) { return { ok: true, status: 200, json: json({ turn_duration_ms: duration, turn_deadline_ms: deadline, waterfall: role ? [{ role, duration_ms: duration, status: 'ok', repair: repairCalls > 0 }] : [], aggregate: { repair_calls: repairCalls, llm_calls: llmCalls, budget_exhausted: budgetExhausted } }) }; }
