import assert from 'node:assert/strict';
import test from 'node:test';
import { IMPOSSIBLE_PROBE, PUBLIC_PLAYTEST_MANIFEST, manifestDigest, roleGate, runPublicPlaytest, sanitizeReport, stopOwnedServer } from '../public-playtest.mjs';

test('public playtest manifest is stable 20–30 named turns', () => { assert.equal(PUBLIC_PLAYTEST_MANIFEST.length, 23); assert.equal(new Set(PUBLIC_PLAYTEST_MANIFEST.map((turn) => turn.id)).size, 23); assert.match(manifestDigest(), /^[a-f0-9]{64}$/u); });
test('sanitizer uses strict public and diagnostic allowlists', () => { const safe = sanitizeReport({ api_key: 'secret', git: cleanGit(), public_responses: { turn: { status: 200, ok: true, data: { party_id: 'p', prose: 'hidden', turn: { turn_id: 't', mode: 'attention', summary: { outcome: 'not-a-code' } } } } }, turns: [{ turn_id: 'x', public_evidence: { expected: 'blue_wool_found', pass: false, prose: 'hidden' }, response: { status: 200, ok: true, data: { party_id: 'p', message: 'hidden' } }, llm: { turn_duration_ms: 4, turn_deadline_ms: 10, waterfall: [{ role: 'turn_step_planner', duration_ms: 4, provider_payload: 'hidden' }], aggregate: { llm_calls: 1, deadline_exceeded: true, secret: 'hidden' } } }] }); assert.equal(safe.public_responses.turn.domain_outcome_code, undefined); assert.deepEqual(safe.turns[0].public_evidence, { expected: 'blue_wool_found', pass: false }); assert.equal(safe.turns[0].llm.aggregate.deadline_exceeded, true); assert.equal(safe.turns[0].llm.waterfall[0].provider_payload, undefined); assert.equal(safe.turns[0].response.message, undefined); });
test('impossible 2xx requires public commit and planner observation', () => { const incomplete = roleGate({ observed_role_ids: [], turns: [{ turn_id: IMPOSSIBLE_PROBE.id, status: 200, expected_failure: true, response: {}, role_ids: [], llm: { turn_duration_ms: 1, turn_deadline_ms: 10, aggregate: { repair_calls: 0 } } }] }); assert.ok(incomplete.gaps.includes('impossible probe has no public committed turn: impossible-jump')); assert.ok(incomplete.gaps.includes('impossible probe planner not observed: impossible-jump')); const observed = roleGate({ observed_role_ids: [], turns: [{ turn_id: IMPOSSIBLE_PROBE.id, status: 200, expected_failure: true, response: { turn_id: 'turn-1' }, role_ids: ['turn_step_planner'], llm: { turn_duration_ms: 1, turn_deadline_ms: 10, aggregate: { repair_calls: 0 } } }] }); assert.equal(observed.gaps.some((gap) => gap.includes('impossible probe')), false); assert.equal(observed.deterministic_check, 'apps/game-server/test/lower-dvina-trace-turn-step-llm.test.js#impossible jump and absent spaceship plans stay grounded model contracts/jump'); });
test('deadline gate uses authoritative ceiling and LLM diagnostics, not client duration', () => { const withinDeadline = roleGate({ observed_role_ids: [], turns: [{ turn_id: 'x', status: 200, client_duration_ms: 99_999, llm: { turn_duration_ms: 1, turn_deadline_ms: 10, aggregate: { repair_calls: 0 } } }] }); assert.equal(withinDeadline.gaps.includes('deadline exceeded: x'), false); const ceilingExceeded = roleGate({ observed_role_ids: [], turns: [{ turn_id: 'ceiling', status: 200, llm: { turn_duration_ms: 30_000, turn_deadline_ms: 60_000, aggregate: { repair_calls: 0 } } }] }); assert.ok(ceilingExceeded.gaps.includes('deadline exceeded: ceiling')); const reportedExceeded = roleGate({ observed_role_ids: [], turns: [{ turn_id: 'y', status: 200, llm: { turn_duration_ms: 1, turn_deadline_ms: 60_000, aggregate: { repair_calls: 0, deadline_exceeded: true } } }] }); assert.ok(reportedExceeded.gaps.includes('deadline exceeded: y')); });
test('runner snapshots clean exact git before starting', async () => { let started = false; for (const git of [() => ({ head: 'short', dirty: false }), () => ({ head: 'a'.repeat(40), dirty: true })]) await assert.rejects(() => runPublicPlaytest({ git, start: async () => { started = true; } }), { code: 'PUBLIC_PLAYTEST_GIT_EVIDENCE_INVALID' }); assert.equal(started, false); });
test('runner retains partial turns when a later turn fails', async () => { const responses = [health(), catalog(), newGame(), ack(), turn(), diagnostics(), { ok: false, status: 503, json: async () => ({ ok: false }) }]; const manifest = testManifest(); await assert.rejects(() => runPublicPlaytest({ manifest, impossibleProbe: IMPOSSIBLE_PROBE, git: cleanGit, start: async () => ({ url: 'http://local', child: { exitCode: 0, kill() {} } }), fetchImpl: async () => responses.shift(), now: counter(), log() {} }), (error) => { assert.ok(error.report, error.message); assert.deepEqual(error.report.git, cleanGit()); assert.equal(error.report.turns.length, 1); assert.equal(error.report.turn_failure.turn_id, 'probe-1'); return true; }); });
test('runner retains only safe status and public error code from failed turn', async () => { const responses = [health(), catalog(), newGame(), ack(), turn(), diagnostics(), { ok: false, status: 503, json: async () => ({ ok: false, error: { code: 'SAFE_CODE', message: 'do not retain' } }) }]; const manifest = testManifest(); await assert.rejects(() => runPublicPlaytest({ manifest, impossibleProbe: IMPOSSIBLE_PROBE, git: cleanGit, start: async () => ({ url: 'http://local', child: { exitCode: 0, kill() {} } }), fetchImpl: async () => responses.shift(), now: counter(), log() {} }), (error) => { assert.deepEqual(error.report.turn_failure, { turn_id: 'probe-1', code: 'PUBLIC_HTTP_FAILED', http_status: 503, public_error_code: 'SAFE_CODE' }); assert.equal(JSON.stringify(error.report).includes('do not retain'), false); return true; }); });
test('runner uses deterministic identities and stops on missing public causal evidence', async () => { const responses = [health(), catalog(), newGame(), ack(), turn(), diagnostics()]; const bodies = []; await assert.rejects(() => runPublicPlaytest({ git: cleanGit, branch: 7, start: async () => ({ url: 'http://local', child: { exitCode: 0, kill() {} } }), fetchImpl: async (_url, request) => { if (request.body) bodies.push(JSON.parse(request.body)); return responses.shift(); }, now: counter(), log() {} }), (error) => { assert.equal(error.code, 'PUBLIC_PLAYTEST_CAUSAL_EVIDENCE_MISSING'); assert.equal(error.report.run_seed, `public-playtest:${'a'.repeat(40)}:branch:7`); assert.equal(error.report.turns.length, 1); assert.deepEqual(error.report.turns[0].public_evidence, { expected: 'blue_wool_found', pass: false }); return true; }); assert.equal(bodies[0].request_id, `public-playtest:${'a'.repeat(40)}:branch:7`); assert.equal(bodies[2].request_id, `public-playtest:${'a'.repeat(40)}:branch:7:inspect`); assert.equal(bodies[2].idempotency_key, bodies[2].request_id); });
test('runner stops at surrender when public marker is absent', async () => { const responses = [health(), catalog(), newGame(), ack(), turn(), diagnostics()]; const bodies = []; await assert.rejects(() => runPublicPlaytest({ manifest: surrenderFirstManifest(), impossibleProbe: IMPOSSIBLE_PROBE, git: cleanGit, start: async () => ({ url: 'http://local', child: { exitCode: 0, kill() {} } }), fetchImpl: async (_url, request) => { if (request.body) bodies.push(JSON.parse(request.body)); return responses.shift(); }, now: counter(), log() {} }), (error) => { assert.equal(error.code, 'PUBLIC_PLAYTEST_CAUSAL_EVIDENCE_MISSING'); assert.equal(error.report.turn_failure.turn_id, 'surrender'); assert.deepEqual(error.report.turns[0].public_evidence, { expected: 'ratsha_surrendered', pass: false }); return true; }); assert.equal(bodies.some(({ raw_text }) => raw_text === 'Оказать Онисиму первую помощь.'), false); });
test('manifest role evidence reports compound prerequisite gaps', () => { const gate = roleGate({ observed_role_ids: [], turns: [{ turn_id: 'rest', required_role_ids: ['turn_step_planner', 'npc_autonomous_decider'], role_ids: ['turn_step_planner'], status: 200, llm: { turn_duration_ms: 1, turn_deadline_ms: 10, aggregate: { repair_calls: 0 } } }] }); assert.ok(gate.gaps.includes('missing compound prerequisite: rest: npc_autonomous_decider')); });
test('runner fails partial report when git snapshot changes during run', async () => { const responses = [health(), catalog(), newGame(), ack(), turn(), diagnostics(), { ok: false, status: 503, json: async () => ({ ok: false }) }]; const manifest = testManifest(); let calls = 0; await assert.rejects(() => runPublicPlaytest({ manifest, impossibleProbe: IMPOSSIBLE_PROBE, git: () => ++calls === 1 ? cleanGit() : { head: 'b'.repeat(40), dirty: false }, start: async () => ({ url: 'http://local', child: { exitCode: 0, kill() {} } }), fetchImpl: async () => responses.shift(), now: counter(), log() {} }), (error) => { assert.equal(error.code, 'PUBLIC_PLAYTEST_GIT_SNAPSHOT_CHANGED'); assert.deepEqual(error.report.git_after, { head: 'b'.repeat(40), dirty: false }); return true; }); });
test('owned server waits for SIGTERM then uses SIGKILL fallback', async () => { const signals = []; await stopOwnedServer({ exitCode: null, kill(signal) { signals.push(signal); }, once() {} }, { timeoutMs: 1, sleep: async () => {} }); assert.deepEqual(signals, ['SIGTERM', 'SIGKILL']); });
function cleanGit() { return { head: 'a'.repeat(40), dirty: false }; }
function testManifest() { return PUBLIC_PLAYTEST_MANIFEST.map(({ expect: _expect, ...turn }, index) => ({ ...turn, id: `probe-${index}` })); }
function surrenderFirstManifest() { const surrender = PUBLIC_PLAYTEST_MANIFEST.find(({ id }) => id === 'surrender'); return [surrender, ...PUBLIC_PLAYTEST_MANIFEST.filter(({ id }) => id !== 'surrender')]; }
function counter() { let value = 0; return () => ++value; }
function json(data) { return async () => ({ ok: true, data }); }
function health() { return { ok: true, status: 200, json: json({ status: 'ok' }) }; }
function catalog() { return { ok: true, status: 200, json: json({ scenarios: [{ scenario_id: 'lower_dvina_trace_v1', available: true }] }) }; }
function newGame() { return { ok: true, status: 201, json: json({ party_id: 'party-1' }) }; }
function ack() { return { ok: true, status: 200, json: json({ party_id: 'party-1' }) }; }
function turn() { return { ok: true, status: 200, json: json({ party_id: 'party-1', turn: { turn_id: 'turn-1', status: 'resolved', mode: 'attention' }, screen: { schema: 'turn_screen', version: 1, screen_status: 'ready' } }) }; }
function diagnostics() { return { ok: true, status: 200, json: json({ turn_duration_ms: 1, turn_deadline_ms: 10, waterfall: [], aggregate: { repair_calls: 0 } }) }; }
