import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import test from 'node:test';

const docker = (args, input) => spawnSync('docker', args, { input, encoding: 'utf8', timeout: 45_000 });
const name = `p10-ddl-${process.pid}`;

test('P10 applies fresh, reapplies part 13, and rejects route/orientation authoring violations', async (t) => {
  if (docker(['version']).status !== 0) t.skip('Docker is required for isolated PostgreSQL P10 DDL test');
  t.after(() => docker(['rm', '-f', name]));
  assert.equal(docker(['run', '-d', '--name', name, '-e', 'POSTGRES_PASSWORD=p10_local_only', '-e', 'POSTGRES_USER=p10', '-e', 'POSTGRES_DB=p10', 'postgres:16-alpine']).status, 0);
  let ready = false;
  for (let attempt = 0; attempt < 40; attempt += 1) {
    if (docker(['exec', name, 'pg_isready', '-U', 'p10', '-d', 'p10']).status === 0) {
      await new Promise((resolve) => setTimeout(resolve, 500));
      if (docker(['exec', name, 'pg_isready', '-U', 'p10', '-d', 'p10']).status === 0) { ready = true; break; }
    }
    await new Promise((resolve) => setTimeout(resolve, 250));
  }
  assert.equal(ready, true, 'isolated PostgreSQL must become ready');
  const ddl = (await Promise.all(Array.from({ length: 13 }, (_, index) => readFile(`infra/world-base/schema/${String(index + 1).padStart(2, '0')}.sql`, 'utf8')))).join('\n');
  const psql = (sql) => docker(['exec', '-i', name, 'psql', '-q', '-v', 'ON_ERROR_STOP=1', '-U', 'p10', '-d', 'p10'], sql);
  const freshApply = psql(ddl);
  assert.equal(freshApply.status, 0, freshApply.stderr);
  assert.equal(psql(await readFile('infra/world-base/schema/13.sql', 'utf8')).status, 0, 'part 13 must safely reapply');
  for (const sql of [
    "INSERT INTO world_base.spatial_v3_movement_orientation_profiles (id,version,world_revision_id,reference_frame_id,reference_frame_version,profile_kind,vertical_direction,status,provenance_ref,canonical_digest) VALUES ('bad',1,'missing','missing',1,'fixed','level','approved','missing',repeat('a',64));",
    "INSERT INTO world_base.spatial_v3_world_route_segments (id,version,world_revision_id,world_route_id,world_route_version,ordinal,from_point_id,from_point_version,to_point_id,to_point_version,transition_environment_profile_id,transition_environment_profile_version,movement_orientation_profile_id,movement_orientation_profile_version,baseline_movement_method_id,movement_method_cost_profile_id,movement_method_cost_profile_version,base_minutes,dynamic_recheck_policy_id,dynamic_recheck_policy_version,status,provenance_ref,canonical_digest) VALUES ('bad',1,'missing','missing',1,0,'a',1,'b',1,'e',1,'o',1,'walk','c',1,0,'r',1,'approved','missing',repeat('a',64));"
  ]) assert.notEqual(psql(sql).status, 0, `invalid P10 mutation must fail: ${sql}`);
  const reverseSetup = `
    INSERT INTO world_base.source_records (id,status) VALUES ('p10-src','approved');
    INSERT INTO world_base.spatial_v3_world_revisions (id,catalog_digest,status,provenance_ref) VALUES ('p10-rev',repeat('a',64),'approved','p10-src');
    INSERT INTO world_base.spatial_v3_authoring_versions (entity_kind,entity_id,version,world_revision_id,canonical_digest,status,provenance_ref) VALUES
      ('orientation_reference_frame','p10-root',1,'p10-rev',repeat('b',64),'approved','p10-src'),('movement_orientation_profile','p10-fwd',1,'p10-rev',repeat('c',64),'approved','p10-src'),('movement_orientation_profile','p10-rev-profile',1,'p10-rev',repeat('d',64),'approved','p10-src'),('movement_orientation_profile','p10-unpaired',1,'p10-rev',repeat('e',64),'approved','p10-src');
    BEGIN;
    INSERT INTO world_base.spatial_v3_orientation_reference_frames (id,version,world_revision_id,scope_entity_kind,scope_entity_id,scope_entity_version,north_offset_mdeg,status,provenance_ref,canonical_digest) VALUES ('p10-root',1,'p10-rev','world_revision','p10-rev',1,0,'approved','p10-src',repeat('e',64));
    INSERT INTO world_base.spatial_v3_movement_orientation_profiles (id,version,world_revision_id,reference_frame_id,reference_frame_version,profile_kind,fixed_local_azimuth_mdeg,vertical_direction,status,provenance_ref,canonical_digest) VALUES ('p10-fwd',1,'p10-rev','p10-root',1,'curved',NULL,'up','approved','p10-src',repeat('f',64)),('p10-rev-profile',1,'p10-rev','p10-root',1,'curved',NULL,'down','approved','p10-src',repeat('0',64)),('p10-unpaired',1,'p10-rev','p10-root',1,'fixed',180000,'level','approved','p10-src',repeat('1',64));
    INSERT INTO world_base.spatial_v3_movement_orientation_profile_points VALUES ('p10-fwd',1,0,0,0,'shortest_arc'),('p10-fwd',1,1,1000000,90000,NULL),('p10-rev-profile',1,0,0,270000,'shortest_arc'),('p10-rev-profile',1,1,1000000,180000,NULL);
    UPDATE world_base.spatial_v3_movement_orientation_profiles SET reverse_profile_id='p10-rev-profile',reverse_profile_version=1 WHERE id='p10-fwd';
    UPDATE world_base.spatial_v3_movement_orientation_profiles SET reverse_profile_id='p10-fwd',reverse_profile_version=1 WHERE id='p10-rev-profile'; COMMIT;`;
  assert.equal(psql(reverseSetup).status, 0, 'valid reciprocal curved profiles commit');
  assert.notEqual(psql("BEGIN; UPDATE world_base.spatial_v3_movement_orientation_profile_points SET local_azimuth_mdeg=1 WHERE profile_id='p10-fwd' AND ordinal=0; COMMIT;").status, 0, 'reverse-profile point mutation must be rejected');
  assert.notEqual(psql("BEGIN; UPDATE world_base.spatial_v3_movement_orientation_profiles SET reverse_profile_id='p10-unpaired',reverse_profile_version=1 WHERE id='p10-fwd'; COMMIT;").status, 0, 'wrong reciprocal orientation profile must be rejected at COMMIT');

  // This aggregate deliberately uses every boundary dependency.  The negative
  // cases below prove that later direct mutations are rejected at COMMIT, rather
  // than only proving that an invalid boundary cannot be authored initially.
  const boundaryFixture = `
    INSERT INTO world_base.universal_categories (id,domain,stable_code,facet,preferred_label,definition,scope_note,inclusion_rules,exclusion_rules,title,status) VALUES ('p10-cat','spatial','p10-cat','class','P10 class','d','s','i','e','t','approved');
    INSERT INTO world_base.spatial_v3_authoring_versions (entity_kind,entity_id,version,world_revision_id,canonical_digest,status,provenance_ref) VALUES
      ('spatial_node','p10-g0',1,'p10-rev',repeat('1',64),'approved','p10-src'),('spatial_node','p10-g1a',1,'p10-rev',repeat('2',64),'approved','p10-src'),('spatial_node','p10-g1b',1,'p10-rev',repeat('3',64),'approved','p10-src'),('spatial_node','p10-g2',1,'p10-rev',repeat('4',64),'approved','p10-src'),('spatial_node','p10-g3',1,'p10-rev',repeat('5',64),'approved','p10-src'),('spatial_node','p10-g4',1,'p10-rev',repeat('6',64),'approved','p10-src'),('spatial_node','p10-g5a',1,'p10-rev',repeat('7',64),'approved','p10-src'),('spatial_node','p10-g5b',1,'p10-rev',repeat('8',64),'approved','p10-src'),
      ('g4_directional_exit','p10-exit',1,'p10-rev',repeat('9',64),'approved','p10-src'),('g4_directional_exit','p10-exit-rev',1,'p10-rev',repeat('a',64),'approved','p10-src'),('world_route','p10-route',1,'p10-rev',repeat('a',64),'approved','p10-src'),('world_route','p10-route-rev',1,'p10-rev',repeat('b',64),'approved','p10-src'),('world_route_point','p10-p0',1,'p10-rev',repeat('b',64),'approved','p10-src'),('world_route_point','p10-p1',1,'p10-rev',repeat('c',64),'approved','p10-src'),('world_route_point','p10-p2',1,'p10-rev',repeat('d',64),'approved','p10-src'),('world_route_point','p10-rp0',1,'p10-rev',repeat('e',64),'approved','p10-src'),('world_route_point','p10-rp1',1,'p10-rev',repeat('f',64),'approved','p10-src'),('world_route_point','p10-rp2',1,'p10-rev',repeat('0',64),'approved','p10-src'),('transition_environment_profile','p10-env',1,'p10-rev',repeat('e',64),'approved','p10-src'),('movement_method_cost_profile','p10-cost',1,'p10-rev',repeat('f',64),'approved','p10-src'),('dynamic_recheck_policy','p10-policy',1,'p10-rev',repeat('0',64),'approved','p10-src'),('world_route_segment','p10-s0',1,'p10-rev',repeat('1',64),'approved','p10-src'),('world_route_segment','p10-s1',1,'p10-rev',repeat('2',64),'approved','p10-src'),('world_route_segment','p10-rs0',1,'p10-rev',repeat('3',64),'approved','p10-src'),('world_route_segment','p10-rs1',1,'p10-rev',repeat('4',64),'approved','p10-src'),('spatial_transition_contract','p10-transition',1,'p10-rev',repeat('3',64),'approved','p10-src'),('boundary_crossing_contract','p10-boundary',1,'p10-rev',repeat('4',64),'approved','p10-src'),('world_route_endpoint_binding','p10-from',1,'p10-rev',repeat('5',64),'approved','p10-src'),('world_route_endpoint_binding','p10-to',1,'p10-rev',repeat('6',64),'approved','p10-src'),('world_route_endpoint_binding','p10-rev-from',1,'p10-rev',repeat('7',64),'approved','p10-src'),('world_route_endpoint_binding','p10-rev-to',1,'p10-rev',repeat('8',64),'approved','p10-src');
    BEGIN;
    INSERT INTO world_base.spatial_v3_nodes (id,version,world_revision_id,spatial_level,primary_class_id,evidence_status,traversal_model,status,provenance_ref,canonical_digest) VALUES
      ('p10-g0',1,'p10-rev','G0','p10-cat','reviewed',NULL,'approved','p10-src',repeat('1',64)),('p10-g1a',1,'p10-rev','G1','p10-cat','reviewed',NULL,'approved','p10-src',repeat('2',64)),('p10-g1b',1,'p10-rev','G1','p10-cat','reviewed',NULL,'approved','p10-src',repeat('3',64)),('p10-g2',1,'p10-rev','G2','p10-cat','reviewed',NULL,'approved','p10-src',repeat('4',64)),('p10-g3',1,'p10-rev','G3','p10-cat','reviewed',NULL,'approved','p10-src',repeat('5',64)),('p10-g4',1,'p10-rev','G4','p10-cat','reviewed','through_area','approved','p10-src',repeat('6',64)),('p10-g5a',1,'p10-rev','G5','p10-cat','reviewed',NULL,'approved','p10-src',repeat('7',64)),('p10-g5b',1,'p10-rev','G5','p10-cat','reviewed',NULL,'approved','p10-src',repeat('8',64));
    INSERT INTO world_base.spatial_v3_node_classes SELECT id,1,'p10-cat',0 FROM world_base.spatial_v3_nodes WHERE id LIKE 'p10-g%';
    INSERT INTO world_base.spatial_v3_node_parents VALUES ('p10-g1a',1,'p10-g0',1,'p10-rev'),('p10-g1b',1,'p10-g0',1,'p10-rev'),('p10-g2',1,'p10-g1a',1,'p10-rev'),('p10-g3',1,'p10-g2',1,'p10-rev'),('p10-g4',1,'p10-g3',1,'p10-rev'),('p10-g5a',1,'p10-g4',1,'p10-rev'),('p10-g5b',1,'p10-g4',1,'p10-rev');
    INSERT INTO world_base.spatial_v3_g1_grid_cells VALUES ('p10-g1a',1,'p10-rev','p10-g0',1,'grid_east_north_v1',0,0,'A1'),('p10-g1b',1,'p10-rev','p10-g0',1,'grid_east_north_v1',1,0,'B1');
    INSERT INTO world_base.spatial_v3_g4_directional_exits (id,version,world_revision_id,g4_id,g4_version,direction_context_id,exit_orientation_profile_id,exit_orientation_profile_version,exit_kind,exit_canonical_g5_id,exit_canonical_g5_version,status,provenance_ref,canonical_digest) VALUES ('p10-exit',1,'p10-rev','p10-g4',1,'east','p10-fwd',1,'world_route_exit','p10-g5a',1,'approved','p10-src',repeat('9',64)),('p10-exit-rev',1,'p10-rev','p10-g4',1,'west','p10-rev-profile',1,'world_route_exit','p10-g5b',1,'approved','p10-src',repeat('a',64));
    INSERT INTO world_base.spatial_v3_world_routes (id,version,world_revision_id,route_kind_id,status,provenance_ref,canonical_digest) VALUES ('p10-route',1,'p10-rev','road','approved','p10-src',repeat('a',64)),('p10-route-rev',1,'p10-rev','road','approved','p10-src',repeat('b',64));
    INSERT INTO world_base.spatial_v3_world_route_points (id,version,world_revision_id,world_route_id,world_route_version,ordinal,point_kind,anchor_policy,context_switch_phase,status,provenance_ref,canonical_digest) VALUES ('p10-p0',1,'p10-rev','p10-route',1,0,'endpoint_from','endpoint_binding',NULL,'approved','p10-src',repeat('b',64)),('p10-p1',1,'p10-rev','p10-route',1,1,'boundary','ordinary_transit','inbound_completion','approved','p10-src',repeat('c',64)),('p10-p2',1,'p10-rev','p10-route',1,2,'endpoint_to','endpoint_binding',NULL,'approved','p10-src',repeat('d',64)),('p10-rp0',1,'p10-rev','p10-route-rev',1,0,'endpoint_from','endpoint_binding',NULL,'approved','p10-src',repeat('e',64)),('p10-rp1',1,'p10-rev','p10-route-rev',1,1,'boundary','ordinary_transit','inbound_completion','approved','p10-src',repeat('f',64)),('p10-rp2',1,'p10-rev','p10-route-rev',1,2,'endpoint_to','endpoint_binding',NULL,'approved','p10-src',repeat('0',64));
    INSERT INTO world_base.spatial_v3_transition_environment_profiles (id,version,world_revision_id,environment_class_id,permanent_cost_basis_id,dynamic_environment_rule_set_id,dynamic_environment_rule_set_version,status,provenance_ref,canonical_digest) VALUES ('p10-env',1,'p10-rev','road','base','rules',1,'approved','p10-src',repeat('e',64));
    INSERT INTO world_base.spatial_v3_movement_method_cost_profiles (id,version,world_revision_id,baseline_movement_method_id,status,provenance_ref,canonical_digest) VALUES ('p10-cost',1,'p10-rev','walk','approved','p10-src',repeat('f',64));
    INSERT INTO world_base.spatial_v3_movement_method_cost_options VALUES ('p10-cost',1,'walk','baseline',NULL,NULL);
    INSERT INTO world_base.spatial_v3_dynamic_recheck_policies (id,version,world_revision_id,policy_kind,status,provenance_ref,canonical_digest) VALUES ('p10-policy',1,'p10-rev','segment_once','approved','p10-src',repeat('0',64));
    INSERT INTO world_base.spatial_v3_world_route_segments (id,version,world_revision_id,world_route_id,world_route_version,ordinal,from_point_id,from_point_version,to_point_id,to_point_version,transition_environment_profile_id,transition_environment_profile_version,movement_orientation_profile_id,movement_orientation_profile_version,baseline_movement_method_id,movement_method_cost_profile_id,movement_method_cost_profile_version,base_minutes,dynamic_recheck_policy_id,dynamic_recheck_policy_version,status,provenance_ref,canonical_digest) VALUES ('p10-s0',1,'p10-rev','p10-route',1,0,'p10-p0',1,'p10-p1',1,'p10-env',1,'p10-fwd',1,'walk','p10-cost',1,10,'p10-policy',1,'approved','p10-src',repeat('1',64)),('p10-s1',1,'p10-rev','p10-route',1,1,'p10-p1',1,'p10-p2',1,'p10-env',1,'p10-fwd',1,'walk','p10-cost',1,10,'p10-policy',1,'approved','p10-src',repeat('2',64)),('p10-rs0',1,'p10-rev','p10-route-rev',1,0,'p10-rp0',1,'p10-rp1',1,'p10-env',1,'p10-rev-profile',1,'walk','p10-cost',1,10,'p10-policy',1,'approved','p10-src',repeat('3',64)),('p10-rs1',1,'p10-rev','p10-route-rev',1,1,'p10-rp1',1,'p10-rp2',1,'p10-env',1,'p10-rev-profile',1,'walk','p10-cost',1,10,'p10-policy',1,'approved','p10-src',repeat('4',64));
    INSERT INTO world_base.spatial_v3_world_route_segment_spatial_contexts VALUES ('p10-s0',1,'p10-g0',1,'p10-g1a',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'weather-a',NULL,NULL,'approved','p10-src',repeat('7',64)),('p10-s1',1,'p10-g0',1,'p10-g1b',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'weather-b',NULL,NULL,'approved','p10-src',repeat('8',64)),('p10-rs0',1,'p10-g0',1,'p10-g1b',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'weather-b',NULL,NULL,'approved','p10-src',repeat('8',64)),('p10-rs1',1,'p10-g0',1,'p10-g1a',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'weather-a',NULL,NULL,'approved','p10-src',repeat('7',64));
    INSERT INTO world_base.spatial_v3_spatial_transition_contracts (id,version,world_revision_id,transition_kind,from_g0_id,from_g0_version,from_g1_id,from_g1_version,to_g0_id,to_g0_version,to_g1_id,to_g1_version,grid_delta_x,grid_delta_y,status,provenance_ref,canonical_digest) VALUES ('p10-transition',1,'p10-rev','g1_adjacency','p10-g0',1,'p10-g1a',1,'p10-g0',1,'p10-g1b',1,1,0,'approved','p10-src',repeat('3',64));
    INSERT INTO world_base.spatial_v3_spatial_transition_allowed_route_kinds VALUES ('p10-transition',1,'road');
    INSERT INTO world_base.spatial_v3_boundary_crossing_contracts (id,version,world_revision_id,boundary_kind,route_id,route_version,route_point_id,route_point_version,inbound_segment_id,inbound_segment_version,outbound_segment_id,outbound_segment_version,from_context_digest,to_context_digest,transition_contract_id,transition_contract_version,switch_phase,status,provenance_ref,canonical_digest) VALUES ('p10-boundary',1,'p10-rev','g1_internal','p10-route',1,'p10-p1',1,'p10-s0',1,'p10-s1',1,repeat('7',64),repeat('8',64),'p10-transition',1,'inbound_completion','approved','p10-src',repeat('4',64));
    INSERT INTO world_base.spatial_v3_world_route_endpoint_bindings (id,version,world_revision_id,world_route_id,world_route_version,endpoint_role,route_point_id,route_point_version,canonical_g5_id,canonical_g5_version,directional_exit_id,directional_exit_version,scene_endpoint_slot_key,status,provenance_ref,canonical_digest) VALUES ('p10-from',1,'p10-rev','p10-route',1,'from','p10-p0',1,'p10-g5a',1,'p10-exit',1,'departure','approved','p10-src',repeat('5',64)),('p10-to',1,'p10-rev','p10-route',1,'to','p10-p2',1,'p10-g5b',1,NULL,NULL,'arrival','approved','p10-src',repeat('6',64)),('p10-rev-from',1,'p10-rev','p10-route-rev',1,'from','p10-rp0',1,'p10-g5b',1,'p10-exit-rev',1,'departure','approved','p10-src',repeat('7',64)),('p10-rev-to',1,'p10-rev','p10-route-rev',1,'to','p10-rp2',1,'p10-g5a',1,NULL,NULL,'arrival','approved','p10-src',repeat('8',64));
    UPDATE world_base.spatial_v3_world_routes SET reverse_route_id='p10-route-rev',reverse_route_version=1 WHERE id='p10-route';
    UPDATE world_base.spatial_v3_world_routes SET reverse_route_id='p10-route',reverse_route_version=1 WHERE id='p10-route-rev';
    COMMIT;`;
  const boundaryFixtureResult = psql(boundaryFixture);
  assert.equal(boundaryFixtureResult.status, 0, boundaryFixtureResult.stderr);
  for (const mutation of [
    "UPDATE world_base.spatial_v3_world_route_points SET context_switch_phase='outbound_dispatch' WHERE id='p10-p1';",
    "DELETE FROM world_base.spatial_v3_world_route_points WHERE id='p10-p1';",
    "UPDATE world_base.spatial_v3_world_route_segments SET ordinal=7 WHERE id='p10-s0';",
    "DELETE FROM world_base.spatial_v3_world_route_segments WHERE id='p10-s0';",
    "UPDATE world_base.spatial_v3_world_route_segment_spatial_contexts SET canonical_digest=repeat('9',64) WHERE segment_id='p10-s0';",
    "DELETE FROM world_base.spatial_v3_world_route_segment_spatial_contexts WHERE segment_id='p10-s0';",
    "UPDATE world_base.spatial_v3_spatial_transition_contracts SET transition_kind='g0_external',grid_delta_x=NULL,grid_delta_y=NULL WHERE id='p10-transition';",
    "DELETE FROM world_base.spatial_v3_spatial_transition_contracts WHERE id='p10-transition';"
  ]) {
    const result = psql(`BEGIN; ${mutation} COMMIT;`);
    assert.notEqual(result.status, 0, `boundary dependency mutation must fail at COMMIT: ${mutation}`);
  }
});
