import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import test from 'node:test';
import { RUNTIME_MIGRATIONS } from '../../apps/game-server/src/infrastructure/postgres/migrations.js';
import { SPATIAL_V3_TARGET_MIGRATIONS } from '../../apps/game-server/src/infrastructure/postgres/spatial-v3-target-migrations.js';

const docker = (args, input) => spawnSync('docker', args, { input, encoding: 'utf8', timeout: 45_000 });
const name = `p13-party-${process.pid}`;

test('P13 applies 001→002 idempotently and enforces the v3 spatial foundation', async (t) => {
  assert.equal(RUNTIME_MIGRATIONS.length, 1, 'production composition remains v2 before P28');
  assert.equal(SPATIAL_V3_TARGET_MIGRATIONS.length >= 2, true, 'later target migrations may extend the preserved 001→002 prefix');
  assert.equal(SPATIAL_V3_TARGET_MIGRATIONS.slice(0, 2).length, 2, 'target upgrade manifest preserves 001→002 prefix');
  if (docker(['version']).status !== 0) {
    t.skip('Docker required for isolated P13 PostgreSQL test');
    return;
  }
  t.after(() => docker(['rm', '-f', name]));
  assert.equal(docker(['run', '-d', '--name', name, '-e', 'POSTGRES_PASSWORD=p13_local', '-e', 'POSTGRES_USER=p13', '-e', 'POSTGRES_DB=p13', 'postgres:16-alpine']).status, 0);
  let ready = false;
  for (let i = 0; i < 40; i += 1) { await new Promise((done) => setTimeout(done, 350)); if (docker(['exec', name, 'pg_isready', '-U', 'p13', '-d', 'p13']).status === 0) { await new Promise((done) => setTimeout(done, 500)); if (docker(['exec', name, 'pg_isready', '-U', 'p13', '-d', 'p13']).status === 0) { ready = true; break; } } }
  assert.equal(ready, true);
  const psql = (sql) => docker(['exec', '-i', name, 'psql', '-q', '-v', 'ON_ERROR_STOP=1', '-U', 'p13', '-d', 'p13'], sql);
  const [v2, v3] = await Promise.all(['001_party_runtime.sql', '002_party_runtime_v3.sql'].map((file) => readFile(`schemas/party-db/${file}`, 'utf8')));
  const firstV2 = psql(v2); const firstV3 = psql(v3); const secondV3 = psql(v3);
  assert.equal(firstV2.status, 0, firstV2.stderr); assert.equal(firstV3.status, 0, firstV3.stderr); assert.equal(secondV3.status, 0, secondV3.stderr || '002 is re-applicable');
  assert.equal(psql("INSERT INTO party_runtime.parties (party_id,schema_version,world_revision_id,world_catalog_digest,materializer_version,rng_version,command_catalog_digest,profile_bundle_digest) VALUES ('p',3,'w','d','m','r','c','b');").status, 0);
  const site = "INSERT INTO party_runtime.party_g5_sites(id,party_id,origin,parent_g4_id,canonical_g5_ref,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('site','p','canonical','g4','{\"entity_id\":\"g5\"}','active',0,'c','c');";
  assert.equal(psql(site).status, 0);
  assert.notEqual(psql(site.replace("'site'", "'site-2'")).status, 0, 'one active canonical projection');
  const baseline = "INSERT INTO party_runtime.party_scene_baselines(id,party_id,host_kind,host_id,source_kind,scene_template_ref,materialization_trace_id,materializer_version,catalog_digest,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('base','p','g5_site','site','canonical_template','{\"entity_id\":\"scene\"}','trace','m','d','active',0,'c','c');";
  assert.equal(psql(baseline).status, 0);
  assert.notEqual(psql(baseline.replace("'base'", "'base-2'")).status, 0, 'one active baseline per typed host');
  const g6 = "INSERT INTO party_runtime.party_g6_instances(id,party_id,scene_baseline_id,source_scene_template_ref,scene_slot_key,host_kind,host_id,physical_class_id,primary_scene_role_id,vertical_context_id,overhead_cover_id,intra_g6_visibility_mode,default_visibility_distance_band,acoustic_uniformity,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('g6','p','base','{\"entity_id\":\"scene\"}','slot','g5_site','site','open','role','surface','none','default_clear','near','uniform','active',0,'c','c');";
  assert.equal(psql(g6).status, 0); assert.notEqual(psql(g6.replace("'g6'", "'g6-2'")).status, 0, 'one G6 slot per baseline');
  assert.equal(psql("INSERT INTO party_runtime.scene_position_nodes(id,party_id,g6_instance_id,position_type_id,template_slot_key,template_instance_ordinal,capacity,access_class_id,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('pos','p','g6','standing','p',0,2,'public','active',0,'c','c');").status, 0);
  assert.equal(psql("INSERT INTO party_runtime.expansion_frontiers(id,party_id,g4_id,source_g5_site_id,slot_ref,status,state_version,created_change_set_id) VALUES ('frontier','p','g4','site','{\"entity_id\":\"slot\"}','open',0,'c'); INSERT INTO party_runtime.scene_frontier_bindings(id,party_id,position_id,frontier_id,scene_baseline_id,status,state_version,activated_change_set_id) VALUES ('binding','p','pos','frontier','base','active',0,'c');").status, 0, 'frontier binding supports an unconditional null access condition');
  assert.notEqual(psql("BEGIN; UPDATE party_runtime.expansion_frontiers SET status='consumed',resolution_kind='generated_site',resolved_site_connection_id='c',resolved_change_set_id='c' WHERE id='frontier'; COMMIT;").status, 0, 'frontier cannot resolve while its scene binding is active');
  assert.notEqual(psql("BEGIN; UPDATE party_runtime.scene_position_nodes SET status='superseded',terminal_change_set_id='c' WHERE id='pos'; COMMIT;").status, 0, 'scene parent cannot deactivate while its frontier binding is active');
  assert.notEqual(psql("BEGIN; INSERT INTO party_runtime.scene_frontier_bindings(id,party_id,position_id,frontier_id,scene_baseline_id,access_condition_set_ref,status,state_version,activated_change_set_id,deactivated_change_set_id) VALUES ('bad-binding','p','pos','frontier','base','{}','inactive',0,'c','c'); COMMIT;").status, 0, 'present frontier access condition must be versioned');
  assert.equal(psql("INSERT INTO party_runtime.party_g5_sites(id,party_id,origin,parent_g4_id,generated_template_ref,expansion_slot_ref,source_frontier_id,generation_ordinal,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('generated','p','generated','g4','{}','{}','frontier',0,'active',0,'c','c');").status, 0);
  assert.notEqual(psql("BEGIN; INSERT INTO party_runtime.party_scene_baselines(id,party_id,host_kind,host_id,source_kind,scene_template_ref,materialization_trace_id,materializer_version,catalog_digest,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('wrong-generated','p','g5_site','site','generated_template','{}','trace','m','d','active',0,'c','c'); COMMIT;").status, 0, 'generated template cannot host a canonical G5');
  assert.notEqual(psql("BEGIN; INSERT INTO party_runtime.party_scene_baselines(id,party_id,host_kind,host_id,source_kind,scene_template_ref,materialization_trace_id,materializer_version,catalog_digest,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('wrong-canonical','p','g5_site','generated','canonical_template','{}','trace','m','d','active',0,'c','c'); COMMIT;").status, 0, 'canonical template cannot host a generated G5');
  assert.equal(psql("INSERT INTO party_runtime.parties (party_id,schema_version,world_revision_id,world_catalog_digest,materializer_version,rng_version,command_catalog_digest,profile_bundle_digest) VALUES ('p2',3,'w','d','m','r','c','b'); INSERT INTO party_runtime.party_g5_sites(id,party_id,origin,parent_g4_id,canonical_g5_ref,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('site2','p2','canonical','g4','{\"entity_id\":\"g52\"}','active',0,'c','c'); INSERT INTO party_runtime.party_scene_baselines(id,party_id,host_kind,host_id,source_kind,scene_template_ref,materialization_trace_id,materializer_version,catalog_digest,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('base2','p2','g5_site','site2','canonical_template','{\"entity_id\":\"scene\"}','trace','m','d','active',0,'c','c'); INSERT INTO party_runtime.party_g6_instances(id,party_id,scene_baseline_id,source_scene_template_ref,scene_slot_key,host_kind,host_id,physical_class_id,primary_scene_role_id,vertical_context_id,overhead_cover_id,intra_g6_visibility_mode,default_visibility_distance_band,acoustic_uniformity,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('g62','p2','base2','{\"entity_id\":\"scene\"}','slot','g5_site','site2','open','role','surface','none','default_clear','near','uniform','active',0,'c','c'); INSERT INTO party_runtime.scene_position_nodes(id,party_id,g6_instance_id,position_type_id,template_slot_key,template_instance_ordinal,capacity,access_class_id,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('pos2','p2','g62','standing','p',0,2,'public','active',0,'c','c');").status, 0);
  for (const statement of [
    "INSERT INTO party_runtime.scene_movement_edges(id,party_id,scene_baseline_id,source_scene_template_ref,source_edge_slot_key,from_position_id,to_position_id,passage_type_id,transition_environment_profile_ref,movement_orientation_profile_ref,cost_kind,action_units,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('edge','p','base','{}','edge','pos','pos2','path','{}','{}','action',1,'active',0,'c','c')",
    "INSERT INTO party_runtime.visibility_links(id,party_id,scene_baseline_id,source_scene_template_ref,source_link_slot_key,from_position_id,to_position_id,quality,distance_band,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('visible','p','base','{}','visible','pos','pos2','clear','near','active',0,'c','c')",
    "INSERT INTO party_runtime.acoustic_edges(id,party_id,scene_baseline_id,source_scene_template_ref,source_edge_slot_key,from_g6_instance_id,to_g6_instance_id,base_loss,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('sound','p','base','{}','sound','g6','g62',1,'active',0,'c','c')"
  ]) assert.notEqual(psql(`BEGIN; ${statement}; COMMIT;`).status, 0, 'cross-party scene relation fails at deferred commit');
  assert.equal(psql("INSERT INTO party_runtime.party_world_route_endpoint_position_bindings(id,party_id,source_endpoint_binding_ref,scene_baseline_id,g5_site_id,position_id,status,state_version,activated_change_set_id) VALUES ('route-endpoint','p','{\"entity_id\":\"endpoint\",\"authoring_version\":\"1\"}','base','site','pos','active',0,'c');").status, 0, 'same-party normalized world endpoint is accepted');
  assert.notEqual(psql("BEGIN; INSERT INTO party_runtime.party_world_route_endpoint_position_bindings(id,party_id,source_endpoint_binding_ref,scene_baseline_id,g5_site_id,position_id,status,state_version,activated_change_set_id) VALUES ('bad-route-endpoint','p','{\"entity_id\":\"endpoint2\",\"authoring_version\":\"1\"}','base2','site2','pos2','active',0,'c'); COMMIT;").status, 0, 'world endpoint cannot mix party/baseline/site/position');
  assert.equal(psql("INSERT INTO party_runtime.party_transit_anchors(id,party_id,source_route_point_ref,anchor_role,context_snapshot,active_side,allowed_departure_dependency_pins,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('transit2','p2','{}','ordinary','{}','arrival','{}','active',0,'c','c');").status, 0);
  assert.notEqual(psql("BEGIN; INSERT INTO party_runtime.party_route_anchor_identities(id,party_id,anchor_kind,source_transit_anchor_id,source_dependency_pins,factual_context_snapshot,status,resolution_kind,state_version,created_change_set_id,updated_change_set_id) VALUES ('bad-anchor-transit','p','shared_checkpoint','transit2','{}','{}','active','reusable_checkpoint',0,'c','c'); COMMIT;").status, 0, 'route anchor source transit must be same-party');
  assert.equal(psql("INSERT INTO party_runtime.portal_entities(id,party_id,scene_baseline_id,portal_template_ref,state,state_version,created_change_set_id,updated_change_set_id) VALUES ('portal2','p2','base2','{}','closed',0,'c','c');").status, 0);
  assert.notEqual(psql("BEGIN; INSERT INTO party_runtime.g5_site_connections(id,party_id,from_site_id,to_site_id,passage_type_id,transition_environment_profile_ref,movement_orientation_profile_ref,cost_kind,action_units,portal_entity_id,availability_condition_set_ref,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('bad-site-portal','p','site','site','passage','{}','{}','action',1,'portal2','{}','active',0,'c','c'); COMMIT;").status, 0, 'site connection portal must be same-party');
  assert.notEqual(psql("BEGIN; INSERT INTO party_runtime.portal_entities(id,party_id,scene_baseline_id,portal_template_ref,state,state_version,created_change_set_id,updated_change_set_id) VALUES ('bad-portal','p','base2','{}','closed',0,'c','c'); COMMIT;").status, 0, 'portal cannot reference a foreign-party baseline');
  assert.notEqual(psql("BEGIN; INSERT INTO party_runtime.party_scene_baselines(id,party_id,host_kind,host_id,source_kind,scene_template_ref,materialization_trace_id,materializer_version,catalog_digest,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('bad-host','p','g5_site','site2','canonical_template','{}','trace','m','d','active',0,'c','c'); COMMIT;").status, 0, 'polymorphic G5 baseline host must be same-party');
  assert.notEqual(psql("BEGIN; INSERT INTO party_runtime.party_scene_baselines(id,party_id,host_kind,host_id,source_kind,scene_template_ref,materialization_trace_id,materializer_version,catalog_digest,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('bad-anchor-host','p','route_anchor_identity','missing','route_checkpoint','{}','trace','m','d','active',0,'c','c'); COMMIT;").status, 0, 'polymorphic route-anchor host must resolve');
  assert.equal(psql("INSERT INTO party_runtime.party_route_anchor_identities(id,party_id,anchor_kind,source_dependency_pins,factual_context_snapshot,status,resolution_kind,state_version,created_change_set_id,updated_change_set_id) VALUES ('anchor','p','migration_checkpoint','{}','{}','active','persistent_consequence',0,'c','c'); INSERT INTO party_runtime.party_scene_baselines(id,party_id,host_kind,host_id,source_kind,scene_template_ref,materialization_trace_id,materializer_version,catalog_digest,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('anchor-base','p','route_anchor_identity','anchor','route_checkpoint','{}','trace','m','d','active',0,'c','c');").status, 0);
  assert.equal(psql("INSERT INTO party_runtime.party_g6_instances(id,party_id,scene_baseline_id,source_scene_template_ref,scene_slot_key,host_kind,host_id,physical_class_id,primary_scene_role_id,vertical_context_id,overhead_cover_id,intra_g6_visibility_mode,default_visibility_distance_band,acoustic_uniformity,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('anchor-g6','p','anchor-base','{}','slot','route_anchor_identity','anchor','open','role','surface','none','default_clear','near','uniform','active',0,'c','c'); INSERT INTO party_runtime.scene_position_nodes(id,party_id,g6_instance_id,position_type_id,template_slot_key,template_instance_ordinal,capacity,access_class_id,status,state_version,created_change_set_id,updated_change_set_id) VALUES ('anchor-pos','p','anchor-g6','standing','p',0,1,'public','active',0,'c','c'); INSERT INTO party_runtime.party_route_anchor_location_bindings(id,route_anchor_id,scene_baseline_id,g6_instance_id,position_node_id,dependency_pins,status,state_version,activated_change_set_id) VALUES ('anchor-location','anchor','anchor-base','anchor-g6','anchor-pos','{}','active',0,'c');").status, 0, 'valid active route-anchor location is accepted');
  for (const statement of [
    "UPDATE party_runtime.party_route_anchor_identities SET status='inactive' WHERE id='anchor'",
    "UPDATE party_runtime.party_scene_baselines SET status='superseded',terminal_change_set_id='c' WHERE id='anchor-base'",
    "UPDATE party_runtime.party_g6_instances SET status='superseded',terminal_change_set_id='c' WHERE id='anchor-g6'",
    "UPDATE party_runtime.scene_position_nodes SET status='superseded',terminal_change_set_id='c' WHERE id='anchor-pos'"
  ]) assert.notEqual(psql(`BEGIN; ${statement}; COMMIT;`).status, 0, 'parent deactivation is rejected while active route-anchor binding remains');
  assert.notEqual(psql("BEGIN; INSERT INTO party_runtime.party_route_anchor_location_bindings(id,route_anchor_id,scene_baseline_id,g6_instance_id,position_node_id,dependency_pins,status,state_version,activated_change_set_id) VALUES ('bad-anchor-location','anchor','anchor-base','g62','pos2','{}','active',0,'c'); COMMIT;").status, 0, 'route-anchor location must use its own baseline/G6/position');
  assert.notEqual(psql("INSERT INTO party_runtime.entity_placements(party_id,entity_kind,entity_id,placement_kind,host_entity_ref,occupies_capacity_units,state_version,updated_change_set_id) VALUES ('p','entity','x','inside_entity','{\"entity_kind\":\"entity\",\"entity_id\":\"x\"}',1,0,'c');").status, 0, 'placement cycle rejected');
  assert.notEqual(psql("INSERT INTO party_runtime.entity_placements(party_id,entity_kind,entity_id,placement_kind,position_node_id,occupies_capacity_units,state_version,updated_change_set_id) VALUES ('p','entity','bad','scene_position','pos',-1,0,'c');").status, 0, 'placement capacity units are non-negative integers');
});
