import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import pg from 'pg';
import { applySpatialV3WorldMigration, buildSpatialV3MigrationInventory, readV2WorldSource } from '../../tools/spatial-v3/p24-migration.mjs';

const docker = (args) => spawnSync('docker', args, { encoding: 'utf8', timeout: 45_000 });
const port = 57100 + (process.pid % 400); const name = `p24-world-${process.pid}`;
const sha = (letter) => letter.repeat(64);
const row = (table, values, source) => ({ table, values, source_identity: source.source_identity, evidence: source.evidence, pin_mapping: source.pin_mapping });

function canonicalWorldRows(source) {
  const revision = 'p24-revision'; const provenance = 'p24-source'; const category = 'p24-spatial-class';
  const nodes = [['p24-g0', 'G0', null], ['p24-g1', 'G1', null], ['p24-g2', 'G2', null], ['p24-g3', 'G3', null], ['p24-g4', 'G4', 'through_area'], ['p24-g5', 'G5', null]];
  const versions = [
    ...nodes.map(([id]) => ['spatial_node', id]), ['orientation_reference_frame', 'p24-frame'], ['movement_orientation_profile', 'p24-orientation'],
    ['transition_environment_profile', 'p24-environment'], ['movement_method_cost_profile', 'p24-cost'], ['dynamic_recheck_policy', 'p24-policy'],
    ['g4_directional_exit', 'p24-exit'], ['world_route', 'p24-route'], ['world_route_point', 'p24-point-from'], ['world_route_point', 'p24-point-to'],
    ['world_route_segment', 'p24-segment'], ['world_route_endpoint_binding', 'p24-endpoint-from'], ['world_route_endpoint_binding', 'p24-endpoint-to'],
    ['regional_scene_template_basis', 'p24-regional-template'], ['scene_selection_rule', 'p24-selection'], ['scene_applicability_rule', 'p24-applicability']
  ];
  return [
    row('spatial_v3_world_revisions', { id: revision, catalog_digest: sha('a'), status: 'approved', provenance_ref: provenance }, source),
    ...versions.map(([entity_kind, entity_id], i) => row('spatial_v3_authoring_versions', { entity_kind, entity_id, version: 1, world_revision_id: revision, canonical_digest: sha('b'), status: 'approved', provenance_ref: provenance }, source)),
    ...nodes.map(([id, spatial_level, traversal_model], i) => row('spatial_v3_nodes', { id, version: 1, world_revision_id: revision, spatial_level, primary_class_id: category, evidence_status: 'reviewed', traversal_model, status: 'approved', provenance_ref: provenance, canonical_digest: sha('c') }, source)),
    ...nodes.map(([id]) => row('spatial_v3_node_classes', { node_id: id, node_version: 1, category_id: category, class_ordinal: 0 }, source)),
    ...nodes.slice(1).map(([id], i) => row('spatial_v3_node_parents', { child_id: id, child_version: 1, parent_id: nodes[i][0], parent_version: 1, world_revision_id: revision }, source)),
    row('spatial_v3_g1_grid_cells', { node_id: 'p24-g1', node_version: 1, world_revision_id: revision, root_g0_id: 'p24-g0', root_g0_version: 1, grid_convention: 'grid_east_north_v1', grid_x: 0, grid_y: 0, cell_code: 'P24-A1' }, source),
    row('spatial_v3_orientation_reference_frames', { id: 'p24-frame', version: 1, world_revision_id: revision, scope_entity_kind: 'world_revision', scope_entity_id: revision, scope_entity_version: 1, north_offset_mdeg: 0, status: 'approved', provenance_ref: provenance, canonical_digest: sha('d') }, source),
    row('spatial_v3_movement_orientation_profiles', { id: 'p24-orientation', version: 1, world_revision_id: revision, reference_frame_id: 'p24-frame', reference_frame_version: 1, profile_kind: 'fixed', fixed_local_azimuth_mdeg: 90000, vertical_direction: 'level', status: 'approved', provenance_ref: provenance, canonical_digest: sha('e') }, source),
    row('spatial_v3_transition_environment_profiles', { id: 'p24-environment', version: 1, world_revision_id: revision, environment_class_id: 'road', permanent_cost_basis_id: 'baseline', dynamic_environment_rule_set_id: 'p24-rule-set', dynamic_environment_rule_set_version: 1, status: 'approved', provenance_ref: provenance, canonical_digest: sha('f') }, source),
    row('spatial_v3_movement_method_cost_profiles', { id: 'p24-cost', version: 1, world_revision_id: revision, baseline_movement_method_id: 'walk', status: 'approved', provenance_ref: provenance, canonical_digest: sha('0') }, source),
    row('spatial_v3_dynamic_recheck_policies', { id: 'p24-policy', version: 1, world_revision_id: revision, policy_kind: 'segment_once', status: 'approved', provenance_ref: provenance, canonical_digest: sha('1') }, source),
    row('spatial_v3_g4_directional_exits', { id: 'p24-exit', version: 1, world_revision_id: revision, g4_id: 'p24-g4', g4_version: 1, direction_context_id: 'east', exit_orientation_profile_id: 'p24-orientation', exit_orientation_profile_version: 1, exit_kind: 'world_route_exit', exit_canonical_g5_id: 'p24-g5', exit_canonical_g5_version: 1, status: 'approved', provenance_ref: provenance, canonical_digest: sha('2') }, source),
    row('spatial_v3_world_routes', { id: 'p24-route', version: 1, world_revision_id: revision, route_kind_id: 'road', status: 'approved', provenance_ref: provenance, canonical_digest: sha('3') }, source),
    row('spatial_v3_world_route_points', { id: 'p24-point-from', version: 1, world_revision_id: revision, world_route_id: 'p24-route', world_route_version: 1, ordinal: 0, point_kind: 'endpoint_from', anchor_policy: 'endpoint_binding', context_switch_phase: null, status: 'approved', provenance_ref: provenance, canonical_digest: sha('4') }, source),
    row('spatial_v3_world_route_points', { id: 'p24-point-to', version: 1, world_revision_id: revision, world_route_id: 'p24-route', world_route_version: 1, ordinal: 1, point_kind: 'endpoint_to', anchor_policy: 'endpoint_binding', context_switch_phase: null, status: 'approved', provenance_ref: provenance, canonical_digest: sha('5') }, source),
    row('spatial_v3_world_route_segments', { id: 'p24-segment', version: 1, world_revision_id: revision, world_route_id: 'p24-route', world_route_version: 1, ordinal: 0, from_point_id: 'p24-point-from', from_point_version: 1, to_point_id: 'p24-point-to', to_point_version: 1, transition_environment_profile_id: 'p24-environment', transition_environment_profile_version: 1, movement_orientation_profile_id: 'p24-orientation', movement_orientation_profile_version: 1, baseline_movement_method_id: 'walk', movement_method_cost_profile_id: 'p24-cost', movement_method_cost_profile_version: 1, base_minutes: 5, dynamic_recheck_policy_id: 'p24-policy', dynamic_recheck_policy_version: 1, status: 'approved', provenance_ref: provenance, canonical_digest: sha('6') }, source),
    row('spatial_v3_world_route_segment_spatial_contexts', { segment_id: 'p24-segment', segment_version: 1, g0_id: 'p24-g0', g0_version: 1, g1_id: 'p24-g1', g1_version: 1, g2_id: 'p24-g2', g2_version: 1, g3_id: 'p24-g3', g3_version: 1, g4_corridor_id: 'p24-g4', g4_corridor_version: 1, jurisdiction_profile_id: null, jurisdiction_profile_version: null, weather_scope_id: 'p24-weather', event_pool_profile_id: null, event_pool_profile_version: null, status: 'approved', provenance_ref: provenance, canonical_digest: sha('7') }, source),
    row('spatial_v3_g4_expansion_profiles', { id: 'p24-expansion-profile', version: 1, world_revision_id: revision, g4_id: 'p24-g4', g4_version: 1, adjacency_rule_set_id: 'p24-adjacency', adjacency_rule_set_version: 1, connectivity_rule_set_id: 'p24-connectivity', connectivity_rule_set_version: 1, seed_policy_id: 'p24-seed', seed_policy_version: 1, status: 'approved', provenance_ref: provenance, canonical_digest: sha('a') }, source),
    row('spatial_v3_terminal_policies', { id: 'p24-terminal-policy', version: 1, world_revision_id: revision, policy_kind: 'physical_boundary', target_directional_exit_id: null, target_directional_exit_version: null, status: 'approved', provenance_ref: provenance, canonical_digest: sha('b') }, source),
    row('spatial_v3_expansion_slots', { id: 'p24-slot', version: 1, world_revision_id: revision, profile_id: 'p24-expansion-profile', profile_version: 1, g4_id: 'p24-g4', g4_version: 1, continuation_role: 'branch', direction_context_id: null, directional_exit_id: null, directional_exit_version: null, max_instances: 1, continuation_length_rule_id: null, continuation_length_rule_version: null, terminal_policy_id: 'p24-terminal-policy', terminal_policy_version: 1, status: 'approved', provenance_ref: provenance, canonical_digest: sha('b') }, source),
    row('spatial_v3_regional_scene_template_bases', { id: 'p24-regional-template', version: 1, world_revision_id: revision, source_profile_family_id: 'p24-profile-family', geometry_claim: 'topological_only', status: 'approved', provenance_ref: provenance, canonical_digest: sha('b') }, source),
    row('spatial_v3_scene_selection_rules', { id: 'p24-selection', version: 1, world_revision_id: revision, rule_kind: 'single_candidate', status: 'approved', provenance_ref: provenance, canonical_digest: sha('b') }, source),
    row('spatial_v3_scene_applicability_rules', { id: 'p24-applicability', version: 1, world_revision_id: revision, rule_kind: 'exact_source_ref', status: 'approved', provenance_ref: provenance, canonical_digest: sha('b') }, source),
    row('spatial_v3_scene_templates', { id: 'p24-scene-template', version: 1, world_revision_id: revision, regional_template_id: 'p24-regional-template', regional_template_version: 1, status: 'approved', provenance_ref: provenance, canonical_digest: sha('c') }, source),
    row('spatial_v3_g6_template_slots', { scene_template_id: 'p24-scene-template', scene_template_version: 1, scene_slot_key: 'p24-g6-slot', physical_class_id: 'spatial.g6.open', primary_scene_role_id: 'road', vertical_context_id: 'surface', overhead_cover_id: 'none', intra_g6_visibility_mode: 'default_clear', default_visibility_distance_band: 'near', acoustic_uniformity: 'uniform', enclosing_structure_slot_key: null }, source),
    row('spatial_v3_scene_position_templates', { scene_template_id: 'p24-scene-template', scene_template_version: 1, position_slot_key: 'p24-position', g6_scene_slot_key: 'p24-g6-slot', instance_count: 1, position_type_id: 'standing', capacity: 1, access_class_id: 'public' }, source),
    row('spatial_v3_scene_endpoint_slots', { scene_template_id: 'p24-scene-template', scene_template_version: 1, slot_key: 'departure', endpoint_role: 'departure', required_position_slot_key: 'p24-position', required_position_instance_ordinal: 0 }, source),
    row('spatial_v3_scene_endpoint_slots', { scene_template_id: 'p24-scene-template', scene_template_version: 1, slot_key: 'arrival', endpoint_role: 'arrival', required_position_slot_key: 'p24-position', required_position_instance_ordinal: 0 }, source),
    row('spatial_v3_scene_materialization_profiles', { id: 'p24-scene-profile', version: 1, world_revision_id: revision, source_kind: 'g5_generation_template', source_entity_id: 'p24-g5-template', source_entity_version: 1, selection_rule_id: 'p24-selection', selection_rule_version: 1, status: 'approved', provenance_ref: provenance, canonical_digest: sha('d') }, source),
    row('spatial_v3_scene_materialization_profiles', { id: 'p24-canonical-g5-profile', version: 1, world_revision_id: revision, source_kind: 'canonical_g5', source_entity_id: 'p24-g5', source_entity_version: 1, selection_rule_id: 'p24-selection', selection_rule_version: 1, status: 'approved', provenance_ref: provenance, canonical_digest: sha('d') }, source),
    row('spatial_v3_g5_generation_templates', { id: 'p24-g5-template', version: 1, world_revision_id: revision, g5_class_id: 'spatial.g5.parcel', regional_template_id: 'p24-regional-template', regional_template_version: 1, scene_materialization_profile_id: 'p24-scene-profile', scene_materialization_profile_version: 1, status: 'approved', provenance_ref: provenance, canonical_digest: sha('e') }, source),
    row('spatial_v3_expansion_profile_template_limits', { profile_id: 'p24-expansion-profile', profile_version: 1, template_id: 'p24-g5-template', template_version: 1, max_count: 1 }, source),
    row('spatial_v3_expansion_slot_templates', { slot_id: 'p24-slot', slot_version: 1, template_id: 'p24-g5-template', template_version: 1, selection_weight: 1, compatibility_rule_id: null, compatibility_rule_version: null }, source),
    row('spatial_v3_g5_successor_frontier_rules', { g5_template_id: 'p24-g5-template', g5_template_version: 1, ordinal: 0, source_expansion_slot_id: 'p24-slot', source_expansion_slot_version: 1, successor_kind: 'branch_frontier', target_expansion_slot_id: 'p24-slot', target_expansion_slot_version: 1, scene_endpoint_slot_key: 'departure', terminal_policy_id: 'p24-terminal-policy', terminal_policy_version: 1, condition_rule_id: null, condition_rule_version: null }, source),
    row('spatial_v3_scene_materialization_candidates', { profile_id: 'p24-scene-profile', profile_version: 1, scene_template_id: 'p24-scene-template', scene_template_version: 1, weight: 1, applicability_rule_id: 'p24-applicability', applicability_rule_version: 1 }, source)
    ,row('spatial_v3_scene_materialization_candidates', { profile_id: 'p24-canonical-g5-profile', profile_version: 1, scene_template_id: 'p24-scene-template', scene_template_version: 1, weight: 1, applicability_rule_id: 'p24-applicability', applicability_rule_version: 1 }, source)
    ,row('spatial_v3_world_route_endpoint_bindings', { id: 'p24-endpoint-from', version: 1, world_revision_id: revision, world_route_id: 'p24-route', world_route_version: 1, endpoint_role: 'from', route_point_id: 'p24-point-from', route_point_version: 1, canonical_g5_id: 'p24-g5', canonical_g5_version: 1, directional_exit_id: 'p24-exit', directional_exit_version: 1, scene_endpoint_slot_key: 'departure', status: 'approved', provenance_ref: provenance, canonical_digest: sha('8') }, source)
    ,row('spatial_v3_world_route_endpoint_bindings', { id: 'p24-endpoint-to', version: 1, world_revision_id: revision, world_route_id: 'p24-route', world_route_version: 1, endpoint_role: 'to', route_point_id: 'p24-point-to', route_point_version: 1, canonical_g5_id: 'p24-g5', canonical_g5_version: 1, directional_exit_id: null, directional_exit_version: null, scene_endpoint_slot_key: 'arrival', status: 'approved', provenance_ref: provenance, canonical_digest: sha('9') }, source)
  ];
}

test('P24 world migration applies canonical G0–G5, semantic grid, route and template chain in isolated PostgreSQL', async (t) => {
  if (docker(['version']).status !== 0) return t.skip('Docker required');
  t.after(() => docker(['rm', '-f', name])); assert.equal(docker(['run', '-d', '--name', name, '-p', `${port}:5432`, '-e', 'POSTGRES_PASSWORD=p24', '-e', 'POSTGRES_USER=p24', '-e', 'POSTGRES_DB=p24', 'postgres:16-alpine']).status, 0);
  const pool = new pg.Pool({ host: '127.0.0.1', port, user: 'p24', password: 'p24', database: 'p24' }); t.after(() => pool.end());
  for (let i = 0; i < 50; i += 1) { try { await pool.query('SELECT 1'); break; } catch { await new Promise((resolve) => setTimeout(resolve, 200)); if (i === 49) throw new Error('postgres unavailable'); } }
  for (let i = 1; i <= 17; i += 1) await pool.query(await readFile(`infra/world-base/schema/${String(i).padStart(2, '0')}.sql`, 'utf8'));
  await pool.query("INSERT INTO world_base.source_records(id,status) VALUES('p24-source','approved')");
  await pool.query("INSERT INTO world_base.universal_categories(id,domain,stable_code,facet,preferred_label,definition,scope_note,inclusion_rules,exclusion_rules,title,status) VALUES('p24-spatial-class','spatial','p24-spatial-class','class','P24 spatial class','P24 fixture class','P24','P24','P24','P24','approved')");
  await pool.query("INSERT INTO world_base.world_revisions(id,title,catalog_digest,status) VALUES('legacy-p24','legacy world snapshot',$1,'approved')", [sha('a')]);
  // Real v2 source fixture: P24 must inventory legacy region/graph records,
  // not prove coverage only against a hand-authored v3 target row.
  await pool.query("INSERT INTO world_base.regions(id,canonical_name,status) VALUES('legacy-region','Legacy region','approved')");
  await pool.query("INSERT INTO world_base.graph_nodes(id,title,node_type,scale_level,region_id,status) VALUES('legacy-g0','Legacy G0','world_region','G0','legacy-region','approved'),('legacy-g1','Legacy G1','subregion','G1','legacy-region','approved')");
  await pool.query("INSERT INTO world_base.graph_edges(id,from_node_id,to_node_id,scale_level,status) VALUES('legacy-edge','legacy-g0','legacy-g1','G1','approved')");
  const sourceExtract = await readV2WorldSource(pool); const source = sourceExtract.records.find((item) => item.source_identity.startsWith('world_base.world_revisions:legacy-p24:')); assert.ok(source, 'read-only source reader must pin actual legacy world revision');
  const inventory = buildSpatialV3MigrationInventory({ world_records: sourceExtract.records.map((row) => row.source_identity === source.source_identity
    ? { old_identity: row.source_identity, old_type: 'world_revision_snapshot', old_level: 'G0-G5', target_contract: 'spatial_v3 canonical world chain', action: 'migrate', reason: 'reviewed canonical source snapshot', evidence: row.evidence, pin_mapping: row.pin_mapping, review_status: 'reviewed' }
    : { old_identity: row.source_identity, old_type: row.source_table, old_level: 'legacy_nonspatial_authoring', target_contract: 'immutable_v2_snapshot', action: 'keep', reason: 'retained only in immutable P24 source snapshot before P28', evidence: row.evidence, pin_mapping: row.pin_mapping, review_status: 'reviewed' }) });
  assert.ok(sourceExtract.records.some((row) => row.source_table === 'world_base.graph_nodes'), 'v2 graph nodes are in the real source snapshot');
  assert.ok(sourceExtract.records.some((row) => row.source_table === 'world_base.graph_edges'), 'v2 graph edges are in the real source snapshot');
  const targetRows = canonicalWorldRows(source);
  assert.equal((await applySpatialV3WorldMigration(pool, { inventory, source_extract: sourceExtract, target_rows: targetRows, dry_run: true })).ok, true);
  assert.equal((await pool.query("SELECT count(*)::int AS n FROM world_base.spatial_v3_world_revisions WHERE id='p24-revision'")).rows[0].n, 0, 'dry run must write no target rows');
  const applied = await applySpatialV3WorldMigration(pool, { inventory, source_extract: sourceExtract, target_rows: targetRows }); assert.equal(applied.applied, targetRows.length);
  assert.equal((await pool.query("SELECT count(*)::int AS n FROM world_base.spatial_v3_migration_coverage_artifacts")).rows[0].n, 1, 'full source inventory/digests must persist with world apply');
  const readback = await pool.query("SELECT (SELECT count(*) FROM world_base.spatial_v3_nodes WHERE world_revision_id='p24-revision')::int AS nodes, (SELECT count(*) FROM world_base.spatial_v3_node_parents WHERE world_revision_id='p24-revision')::int AS containment, (SELECT count(*) FROM world_base.spatial_v3_g1_grid_cells WHERE world_revision_id='p24-revision')::int AS grids, (SELECT count(*) FROM world_base.spatial_v3_world_route_endpoint_bindings WHERE world_revision_id='p24-revision')::int AS endpoints, (SELECT count(*) FROM world_base.spatial_v3_scene_materialization_candidates)::int AS candidates");
  assert.deepEqual(readback.rows[0], { nodes: 6, containment: 5, grids: 1, endpoints: 2, candidates: 2 });
  assert.equal((await pool.query("SELECT count(*)::int AS n FROM world_base.spatial_v3_world_route_endpoint_bindings WHERE world_route_id='p24-route' AND endpoint_role IN ('from','to')")).rows[0].n, 2, 'route must have complete endpoint bindings');
  const failureRows = [...targetRows, { ...row('spatial_v3_world_revisions', { id: 'p24-rolled-back-revision', catalog_digest: sha('b'), status: 'approved', provenance_ref: 'p24-source' }, source) }, targetRows[0]];
  await assert.rejects(() => applySpatialV3WorldMigration(pool, { inventory, source_extract: sourceExtract, target_rows: failureRows }), /duplicate key/u);
  assert.equal((await pool.query("SELECT count(*)::int AS n FROM world_base.spatial_v3_world_revisions WHERE id='p24-rolled-back-revision'")).rows[0].n, 0, 'any multi-row failure rolls back every preceding target write');
});
