import { STAGE19_INPUT_SCHEMA, STAGE19_OUTPUT_SCHEMA, STAGE19_PRECHECK_SCHEMA, STAGE19_AUDIT_SCHEMA, STAGE19_RESULT_SCHEMA, STAGE19_HIDDEN_STATE_STATUSES, STAGE19_HIDDEN_BLOCKS } from '@rus/contracts/time-knowledge-hidden-boundary';
import { isObject } from '../shared/utils.js';
export { STAGE19_INPUT_SCHEMA, STAGE19_OUTPUT_SCHEMA, STAGE19_PRECHECK_SCHEMA, STAGE19_AUDIT_SCHEMA, STAGE19_RESULT_SCHEMA };
export const DEFAULT_STAGE19_HIDDEN_STATE_POLICY=Object.freeze({require_no_player_output:true,require_reveal_conditions_for_every_hidden_fact:true,require_source_trace:true,require_hidden_fact_ids:true,require_risk_triggers:true,require_consequence_hooks:true,require_npc_private_state_for_scene_or_key_npcs:true,allow_minimal_background_npc_hidden_state:true,allow_unresolved_container_contents:true,allow_materialized_container_contents_only_with_causal_basis:true,do_not_create_new_npcs:true,do_not_create_new_items:true,do_not_create_new_containers:true,do_not_create_new_places:true,do_not_create_new_anchors:true,do_not_create_new_routes:true,do_not_write_visible_scene:true,do_not_write_intro_prose:true,do_not_write_narrator_text:true});
export const OUTPUT_ARRAYS=STAGE19_HIDDEN_BLOCKS;
export const BLOCK_ID_FIELDS=Object.freeze({hidden_npc_state:'hidden_npc_state_id',hidden_access_state:'hidden_access_state_id',hidden_property_state:'hidden_property_state_id',hidden_container_state:'hidden_container_state_id',hidden_item_state:'hidden_item_state_id',hidden_risk_state:'hidden_risk_state_id',hidden_event_state:'hidden_event_state_id',hidden_social_state:'hidden_social_state_id',hidden_route_state:'hidden_route_state_id',hidden_environment_state:'hidden_environment_state_id',discovery_rules:'discovery_rule_id',reveal_conditions:'reveal_condition_id',consequence_hooks:'consequence_hook_id',forbidden_output_rules:'forbidden_output_rule_id'});
export const STATUS=new Set(STAGE19_HIDDEN_STATE_STATUSES);
export const FORMAT_STATE_CODES=new Set(['HIDDEN_STATE_INVALID_JSON','HIDDEN_STATE_SCHEMA_MISMATCH','HIDDEN_STATE_REQUIRED_BLOCK_MISSING','HIDDEN_STATE_ARRAY_INVALID']);
export const FORMAT_AUDIT_CODES=new Set(['HIDDEN_STATE_AUDIT_INVALID_JSON','HIDDEN_STATE_AUDIT_SCHEMA_MISMATCH','HIDDEN_STATE_AUDIT_REQUIRED_BLOCK_MISSING']);
export function normalizeStage19HiddenStatePolicy(policy={}){return Object.freeze({...DEFAULT_STAGE19_HIDDEN_STATE_POLICY,...(isObject(policy)?policy:{})});}
