import assert from 'node:assert/strict';
import test from 'node:test';
import { canonicalDigest, createOrdinaryAggregate, applyOrdinaryAggregateTransition } from '@rus/materialization';
import { ordinaryWorldPropertyPlacementContextDigest, resolveOrdinaryWorldPropertyPlacement } from '@rus/items-property';
import { createOrdinaryMaterializationAtomicWritePlan, createOrdinaryMaterializationPhase6Coordinator } from '../src/infrastructure/postgres/ordinary-materialization-phase-6-commit.js';

const scope_ref = { entity_kind: 'g6', entity_id: 'scope' };
function propertyPlacementContext() {
  return {
    scope_ref:{...scope_ref}, item_kind:'man_made',
    property_catalog_version_ref:'property-catalog-v1',
    placement_catalog_version_ref:'placement-catalog-v1',
    personal_communal_refs:[], occupied_site_refs:['occupied-source'],
    unowned_cause_refs:[], placement_context_refs:['placement-context'],
    property_catalog:[{property_basis_ref:'property',state:'committed',scope_ref:{...scope_ref},basis_class:'occupied_site_default',source_ref:'occupied-source',unowned_cause_ref:null}],
    placement_catalog:[{position_ref:'position',state:'committed',scope_ref:{...scope_ref},position_kind:'scene_position',g6_ref:'scope',containment_depth:1,placement_context_ref:'placement-context'}]
  };
}
function admittedItem({ request_identity, candidate_key, coverage_key, context_version }) {
  const supporting_basis_ref = 'basis', property_basis_ref = 'property', position_ref = 'position', mechanics_policy_ref = 'policy';
  const evidence = structuredClone(resolveOrdinaryWorldPropertyPlacement({...propertyPlacementContext(),supporting_basis_ref,causal_basis_refs:[supporting_basis_ref],requested_position_ref:position_ref}).evidence);
  const source_refs = [candidate_key,coverage_key,supporting_basis_ref,property_basis_ref,position_ref,mechanics_policy_ref,evidence.property_source_ref,evidence.property_catalog_version_ref,evidence.placement_catalog_version_ref,evidence.placement_context_ref,evidence.property_placement_context_digest].sort();
  return { candidate_key,coverage_key,context_version,functional_bucket:'household',admission_class:'common_mundane',supporting_basis_ref,causal_basis_refs:[supporting_basis_ref],property_basis_ref,position_ref,mechanics_policy_ref,
    item_proposal:{schema:'ordinary_world_item_proposal_v1',request_id:request_identity,scope_ref:{...scope_ref},candidate_key,coverage_key,context_version,semantic_descriptor:{semantic_type:'household_tool',name:'wooden spoon',facts:['ordinary']},supporting_basis_ref,property_basis_ref,property_placement_evidence:evidence,placement:{scope_ref:'scope',position_ref},runtime_item_mechanics_policy_ref:mechanics_policy_ref},
    mechanics_snapshot:{schema:'rus.items.runtime_instance_mechanics_snapshot.v2',version:2,provenance:{source_kind:'ordinary_world_materialization',causal_ref:'cause',request_id:request_identity,candidate_key,coverage_key,context_version,policy_ref:mechanics_policy_ref,source_refs},mechanics:{mass_grams:80,external_hand_cost:0,carry_form:'compact',packing_slot_cost:1,quantity:{value:1,unit:'item'},container:null}} };
}
function data(kind) { const seed=applyOrdinaryAggregateTransition({aggregate:createOrdinaryAggregate({scope_ref,resolution_record_cap:4}),transition:{kind:'seed',request_identity:'seed',expected_state_version:0,density_band:'ordinary',identity_budget:1,background_groups:[]}}); const request_identity=`request-${kind}`,transition={kind:'resolve_presence',request_identity,expected_state_version:1,resolution_ref:`resolution-${kind}`,candidate_key:'candidate',coverage_key:'coverage',category_key:'category',context_version:'context',resolution:kind,...(kind==='materialize'?{identity_key:'identity'}:{})}; const next_aggregate=applyOrdinaryAggregateTransition({aggregate:seed,transition}); const item=kind==='materialize'?admittedItem({request_identity,candidate_key:'candidate',coverage_key:'coverage',context_version:'context'}):null;if(item)item.item_id=`ordinary_item_${canonicalDigest({party_id:'party',scope_ref,candidate_key:'candidate',coverage_key:'coverage',context_version:'context'}).slice(0,24)}`;const basis=()=>({basis_ref:'basis',state:'committed',scope_ref:{...scope_ref},prepared_seed_provenance:null,functional_buckets:['household'],allowed_admission_classes:['common_mundane']}),digest=canonicalDigest({domain:'ordinary_supporting_basis_catalog_v1',supporting_bases:[basis()]}),propertyPlacement=propertyPlacementContext(),propertyPlacementDigest=ordinaryWorldPropertyPlacementContextDigest({...propertyPlacement,supporting_basis_ref:'basis',causal_basis_refs:['basis'],requested_position_ref:'position'});return {party_id:'party',scope_ref:{...scope_ref},request_identity,input_digest:'input',transition_digest:canonicalDigest(transition),expected_versions:{party_state_version:0,ordinary_state_version:1,catalog_version:1,property_version:1,placement_version:1,supporting_basis_catalog_version:0,supporting_basis_catalog_digest:digest,property_placement_context_digest:propertyPlacementDigest},expected_supporting_basis_catalog:[basis()],new_prepared_bases:[],next_supporting_basis_catalog:[basis()],next_supporting_basis_catalog_version:0,next_supporting_basis_catalog_digest:digest,expected_property_placement_context:propertyPlacement,resolution:kind,transitions:[transition],next_aggregate,item}; }
test('Phase 6 DTO binds exact materialize aggregate delta and deterministic item',()=>{const plan=createOrdinaryMaterializationAtomicWritePlan(data('materialize'));assert.equal(plan.schema,'ordinary_materialization_atomic_write_plan_v1');assert.equal(plan.next_aggregate.remaining_identity_budget,0);assert.match(plan.item.item_id,/^ordinary_item_/u);assert.equal(Object.isFrozen(plan.item.mechanics_snapshot.provenance),true);});
test('Phase 6 DTO preserves budget for factual negative result',()=>{const plan=createOrdinaryMaterializationAtomicWritePlan(data('absent'));assert.equal(plan.item,null);assert.equal(plan.next_aggregate.remaining_identity_budget,1);});
test('Phase 6 DTO never reads getter and rejects forged identity',()=>{const getter=data('absent');Object.defineProperty(getter,'party_id',{enumerable:true,get(){throw Error('read')}});assert.throws(()=>createOrdinaryMaterializationAtomicWritePlan(getter),{code:'ORDINARY_PHASE6_PLAN_INVALID'});const forged=data('materialize');forged.item.item_id='forged';assert.throws(()=>createOrdinaryMaterializationAtomicWritePlan(forged),{code:'ORDINARY_PHASE6_POSITIVE_ITEM_INVALID'});});
test('Phase 6 DTO rejects forged private proposal or v2 snapshot',()=>{const forgedProposal=data('materialize');forgedProposal.item.item_proposal={};assert.throws(()=>createOrdinaryMaterializationAtomicWritePlan(forgedProposal),{code:'ORDINARY_PHASE6_POSITIVE_ITEM_INVALID'});const forgedSnapshot=data('materialize');forgedSnapshot.item.mechanics_snapshot={schema:'rus.items.runtime_instance_mechanics_snapshot.v2',version:2,provenance:{},mechanics:{}};assert.throws(()=>createOrdinaryMaterializationAtomicWritePlan(forgedSnapshot),{code:'ORDINARY_PHASE6_POSITIVE_ITEM_INVALID'});});
test('Phase 6 DTO re-resolves property and placement from the trusted committed context',()=>{for(const mutate of [(v)=>{v.item.item_proposal.property_placement_evidence.property_basis_ref='forged-property';},(v)=>{v.item.item_proposal.property_placement_evidence.placement.position_ref='forged-position';},(v)=>{v.expected_property_placement_context.placement_catalog[0].position_ref='other-position';}]){const value=data('materialize');mutate(value);assert.throws(()=>createOrdinaryMaterializationAtomicWritePlan(value));}});
test('Phase 6 DTO rejects unknown, query-conditioned and cross-scope supporting bases',()=>{for(const mutate of [(v)=>{v.next_supporting_basis_catalog[0].basis_ref='unknown';},(v)=>{v.next_supporting_basis_catalog[0].prepared_seed_provenance={seed_request_id:'seed',mode:'seed_scope',candidate_query:'forbidden'};},(v)=>{v.next_supporting_basis_catalog[0].scope_ref.entity_id='other';}]){const value=data('materialize');mutate(value);assert.throws(()=>createOrdinaryMaterializationAtomicWritePlan(value));}});
test('Phase 6 coordinator calls model before exact reread and atomic commit',async()=>{let reads=0,modelled=false;const coordinator=createOrdinaryMaterializationPhase6Coordinator({loadCommitted:async()=>{reads+=1;return{version_pins:{v:1}};},buildSanitizedRequest:async()=>({}),model:async()=>{modelled=true;return{};},validate:async()=>({}),admit:async()=>({}),buildPurePlan:async()=>{assert.equal(modelled,true);assert.equal(reads,2);return'plan';},atomicCommit:async(plan)=>{assert.equal(plan,'plan');return'ok';}});assert.equal(await coordinator.execute({}),'ok');});
