import { STAGE17_TIME_OF_DAY, STAGE17_LIGHT_PROFILES, STAGE17_SEASONS } from '@rus/contracts/time-knowledge-hidden-boundary';
import { array, isObject, issue, nonEmpty, normalizeText, text } from './shared.js';
const TIME_OF_DAY = new Set(STAGE17_TIME_OF_DAY);
const LIGHT = new Set(STAGE17_LIGHT_PROFILES);
const SEASONS = new Set(STAGE17_SEASONS);
const ALLOWED_LIGHT = Object.freeze({
  deep_night:new Set(['dark','moonlit','firelit','indoor_lit','obscured']), night:new Set(['dark','moonlit','firelit','indoor_lit','obscured']),
  dawn:new Set(['dim','twilight','obscured']), morning:new Set(['daylight','dim','obscured']), day:new Set(['daylight','dim','obscured']),
  afternoon:new Set(['daylight','dim','obscured']), evening:new Set(['daylight','dim','twilight','obscured']), dusk:new Set(['twilight','dim','dark','obscured'])
});
const NIGHT_DAY_TERMS=[/коротк[^ \t\r\n]*\s+светов[^ \t\r\n]*\s+дн/i,/ярк[^ \t\r\n]*\s+дневн[^ \t\r\n]*\s+свет/i,/на\s+дворе\s+день/i,/дневн[^ \t\r\n]*\s+толп/i,/открыт[^ \t\r\n]*\s+торг/i,/обычн[^ \t\r\n]*\s+дневн[^ \t\r\n]*\s+работ/i,/солнц[^ \t\r\n]*\s+высок/i,/daylight/i,/bright\s+day/i,/midday/i,/daytime\s+crowd/i];
const DAY_NIGHT_TERMS=[/глубок[^ \t\r\n]*\s+ноч/i,/полная\s+темнот/i,/трет[^ \t\r\n]*\s+час[^ \t\r\n]*\s+ноч/i,/deep\s+night/i,/pitch\s+dark/i];
const DAY_ACTIVITY_TERMS=[/дневн[^ \t\r\n]*\s+работ/i,/дневн[^ \t\r\n]*\s+толп/i,/открыт[^ \t\r\n]*\s+торг/i,/daytime\s+work/i,/daytime\s+crowd/i];
const DARK_LIGHTS=new Set(['dark','moonlit','obscured']); const CLOSED=new Set(['closed','locked','sealed','hidden','inaccessible']); const HIDDEN=new Set(['hidden','known_but_not_seen','inaccessible']);
export function runTimeLightChecks(input, concerns) { checkClock(input, concerns); checkSeasonWeather(input, concerns); checkG5Visibility(input, concerns); checkNpcVisibility(input, concerns); checkItemVisibility(input, concerns); checkBodyWeather(input, concerns); checkDraftVisible(input, concerns); }
export function checkClock(input, concerns) {
  const clock=input.historical_frame?.clock;
  if(!isObject(clock)||!Number.isInteger(clock.day)||!Number.isInteger(clock.hour)||clock.hour<0||clock.hour>23||!Number.isInteger(clock.minute)||clock.minute<0||clock.minute>59||!TIME_OF_DAY.has(clock.time_of_day)||!LIGHT.has(clock.light_profile)||!text(clock.clock_moment)){concerns.push(issue('TIME_LIGHT_CLOCK_SCHEMA_INVALID','historical_frame.clock is invalid.','historical_frame.clock'));return;}
  if(!ALLOWED_LIGHT[clock.time_of_day]?.has(clock.light_profile)) concerns.push(issue('TIME_LIGHT_TIME_OF_DAY_LIGHT_CONFLICT','time_of_day conflicts with light_profile.','historical_frame.clock.light_profile',[...ALLOWED_LIGHT[clock.time_of_day]],clock.light_profile));
  if(clock.hour>=0&&clock.hour<=4&&['day','afternoon'].includes(clock.time_of_day)) concerns.push(issue('TIME_LIGHT_CLOCK_MOMENT_CONFLICT','Night hour conflicts with daytime label.','historical_frame.clock.time_of_day'));
  if(clock.hour>=10&&clock.hour<=15&&clock.time_of_day==='deep_night') concerns.push(issue('TIME_LIGHT_CLOCK_MOMENT_CONFLICT','Midday hour conflicts with deep_night.','historical_frame.clock.time_of_day'));
  const moment=normalizeText(clock.clock_moment); if(/(полд|midday)/i.test(moment)&&['night','deep_night'].includes(clock.time_of_day)) concerns.push(issue('TIME_LIGHT_CLOCK_MOMENT_CONFLICT','clock_moment conflicts with time_of_day.','historical_frame.clock.clock_moment')); if(/(глубок.*ноч|deep night)/i.test(moment)&&['day','afternoon'].includes(clock.time_of_day)) concerns.push(issue('TIME_LIGHT_CLOCK_MOMENT_CONFLICT','clock_moment conflicts with time_of_day.','historical_frame.clock.clock_moment'));
}
export function checkSeasonWeather(input, concerns) {
  const season=input.historical_frame?.calendar?.season; const w=input.weather_state;
  if(!SEASONS.has(season)) concerns.push(issue('TIME_LIGHT_SEASON_WEATHER_CONFLICT','historical_frame.calendar.season is invalid.','historical_frame.calendar.season'));
  const override=['regional_rule','event_state','generated_and_audited'].includes(w?.weather_source)&&nonEmpty(array(w?.source_trace??w?.evidence));
  if(w?.precipitation==='snow'&&w?.temperature_band==='hot') concerns.push(issue('TIME_LIGHT_SEASON_WEATHER_CONFLICT','Snow cannot coexist with hot temperature.','weather_state'));
  if(w?.ground_state==='ice'&&w?.temperature_band==='hot') concerns.push(issue('TIME_LIGHT_SEASON_WEATHER_CONFLICT','Ice cannot coexist with hot temperature.','weather_state'));
  if(season==='winter'&&w?.temperature_band==='hot'&&!override) concerns.push(issue('TIME_LIGHT_SEASON_WEATHER_CONFLICT','Winter hot weather requires an approved source rule.','weather_state.temperature_band'));
  if(season==='summer'&&w?.temperature_band==='severe_cold'&&!override) concerns.push(issue('TIME_LIGHT_SEASON_WEATHER_CONFLICT','Summer severe cold requires an approved source rule.','weather_state.temperature_band'));
}
export function checkG5Visibility(input, concerns) {
  const g5=input.g5_scene_graph??{}; const anchors=array(g5.anchors??g5.scene_anchors??g5.g5_anchors); const ids=new Set(anchors.map((x)=>x.anchor_id??x.id).filter(Boolean)); const vm=g5.visibility_model??{}; const visible=new Set(array(vm.visible_anchor_ids??g5.visible_anchor_ids)); const hidden=new Set(array(vm.hidden_anchor_ids??g5.hidden_anchor_ids)); const inspect=new Set(array(vm.requires_inspection_anchor_ids??g5.requires_inspection_anchor_ids));
  for(const id of [...visible,...hidden,...inspect]) if(!ids.has(id)) concerns.push(issue('TIME_LIGHT_G5_VISIBILITY_CONFLICT','Visibility references an unknown G5 anchor.','g5_scene_graph.visibility_model',null,id));
  for(const id of visible) if(hidden.has(id)||inspect.has(id)) concerns.push(issue('TIME_LIGHT_G5_VISIBILITY_CONFLICT','Visible anchor cannot also be hidden or inspection-only.','g5_scene_graph.visibility_model',null,id));
  const g5Light=vm.light_profile; if(g5Light&&g5Light!==input.historical_frame.clock.light_profile) concerns.push(issue('TIME_LIGHT_G5_VISIBILITY_CONFLICT','G5 light_profile conflicts with authoritative clock.','g5_scene_graph.visibility_model.light_profile',input.historical_frame.clock.light_profile,g5Light));
  if(DARK_LIGHTS.has(input.historical_frame.clock.light_profile)&&anchors.length>1&&visible.size===anchors.length) concerns.push(issue('TIME_LIGHT_G5_VISIBILITY_CONFLICT','Dark scene cannot expose every anchor without explicit lighting basis.','g5_scene_graph.visibility_model.visible_anchor_ids'));
}
export function checkNpcVisibility(input, concerns) { const tod=input.historical_frame.clock.time_of_day; const light=input.historical_frame.clock.light_profile; for(const [i,npc] of array(input.initial_npc_placement?.npc_instances??input.initial_npc_placement?.placements).entries()){const path=`initial_npc_placement.npc_instances[${i}]`;const visible=npc.visible_to_player_now===true||['visible','seen'].includes(npc.visibility_state);const basis=npc.visibility_basis??npc.visibility_reason??npc.perception_basis;if(visible&&DARK_LIGHTS.has(light)&&!['near','lit','firelit','moonlit','silhouette','audible_only','known_presence'].includes(basis)) concerns.push(issue('TIME_LIGHT_NPC_VISIBILITY_CONFLICT','NPC visible in darkness without a valid basis.',`${path}.visibility_basis`));const activity=normalizeText(npc.current_activity??npc.activity??'');const exception=npc.schedule_exception??npc.time_basis??null;if(['night','deep_night'].includes(tod)&&DAY_ACTIVITY_TERMS.some((r)=>r.test(activity))&&!exception) concerns.push(issue('TIME_LIGHT_NPC_ACTIVITY_CONFLICT','Daytime NPC activity conflicts with night. ',`${path}.current_activity`));} }
export function checkItemVisibility(input, concerns) { const light=input.historical_frame.clock.light_profile; for(const [i,item] of array(input.initial_item_placement?.item_instances).entries()){const path=`initial_item_placement.item_instances[${i}]`;const state=item.visibility_state??item.visibility?.state;const visible=item.visible_to_player_now===true||['visible','seen'].includes(state);const basis=item.visibility_basis??item.visibility?.basis;if(HIDDEN.has(state)&&visible) concerns.push(issue('TIME_LIGHT_HIDDEN_ITEM_VISIBLE','Hidden item cannot be visible.',`${path}.visibility_state`));if(visible&&DARK_LIGHTS.has(light)&&!['near','lit','firelit','moonlit','inspection'].includes(basis)) concerns.push(issue('TIME_LIGHT_ITEM_VISIBILITY_CONFLICT','Item visible in darkness without a valid basis.',`${path}.visibility_basis`));} for(const [i,c] of array(input.initial_item_placement?.container_instances).entries()){const state=c.access_state??c.container_state??c.state;const contentsVisible=c.contents_visible===true||c.content_state?.visible===true||nonEmpty(array(c.visible_content_item_ids));if(CLOSED.has(state)&&contentsVisible) concerns.push(issue('TIME_LIGHT_CLOSED_CONTAINER_CONTENT_VISIBLE','Closed or hidden container cannot expose concrete contents.',`initial_item_placement.container_instances[${i}]`));} }
export function checkBodyWeather(input, concerns) { const w=input.weather_state;if(!['severe_cold'].includes(w.temperature_band)&&w.wind!=='dangerous')return;const body=input.player_character?.body??{};const clothing=normalizeText(body.clothing_summary??input.player_character?.equipment?.clothing_summary??'');const conditions=array(body.active_conditions??input.player_character?.active_conditions).map(normalizeText);const exposure=Number(body.exposure_minutes??input.player_character?.exposure_minutes??0);const clearlyUnprotected=/(лёгк|тонк|мокр|без верхн|light|wet|unprotected)/i.test(clothing);const hasCold=conditions.some((x)=>/(холод|переохлаж|промок|cold|hypotherm|wet)/i.test(x));if(clearlyUnprotected&&exposure>=30&&!hasCold) concerns.push(issue('TIME_LIGHT_BODY_WEATHER_CONFLICT','Extended severe exposure contradicts body state.','player_character.body'));else if(!hasCold) concerns.push(issue('TIME_LIGHT_BODY_WEATHER_RISK','Extreme weather creates a potential body risk that visible context must acknowledge.','player_character.body',null,null,'warning')); }
export function checkDraftVisible(input, concerns) { const draft=input.draft_visible_context_package??{};const tod=input.historical_frame.clock.time_of_day;const texts=[];if(text(draft.visible_scene))texts.push(['draft_visible_context_package.visible_scene',draft.visible_scene]);array(draft.visible_changes).forEach((x,i)=>texts.push([`draft_visible_context_package.visible_changes[${i}]`,typeof x==='string'?x:x?.summary??x?.text??'']));for(const [path,value] of texts){if(['night','deep_night'].includes(tod)&&NIGHT_DAY_TERMS.some((r)=>r.test(value))) concerns.push(issue(path.includes('visible_changes')?'TIME_LIGHT_VISIBLE_CHANGES_CLOCK_CONFLICT':'TIME_LIGHT_VISIBLE_SCENE_CLOCK_CONFLICT','Visible text contains daylight terms at night.',path));if(['day','afternoon'].includes(tod)&&DAY_NIGHT_TERMS.some((r)=>r.test(value))) concerns.push(issue(path.includes('visible_changes')?'TIME_LIGHT_VISIBLE_CHANGES_CLOCK_CONFLICT':'TIME_LIGHT_VISIBLE_SCENE_CLOCK_CONFLICT','Visible text contains night terms during day.',path));} }
