CREATE TABLE world_base.regions (
  id TEXT PRIMARY KEY,
  slug TEXT,
  canonical_name TEXT,
  display_name TEXT,
  alt_names JSONB NOT NULL DEFAULT '[]'::jsonb,
  region_type TEXT,
  parent_region_id TEXT REFERENCES world_base.regions(id) ON DELETE SET NULL,
  period_start_year INTEGER,
  period_end_year INTEGER,
  summary TEXT,
  geographic_scope TEXT,
  natural_landscape TEXT,
  climate_summary TEXT,
  seasonal_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  waterways_summary TEXT,
  roads_summary TEXT,
  settlement_logic_summary TEXT,
  political_summary TEXT,
  ruling_power TEXT,
  administrative_structure TEXT,
  law_summary TEXT,
  custom_summary TEXT,
  religion_summary TEXT,
  social_order_summary TEXT,
  economy_summary TEXT,
  military_pressure_summary TEXT,
  historical_context_summary TEXT,
  neighbor_regions JSONB NOT NULL DEFAULT '[]'::jsonb,
  external_pressure_summary TEXT,
  common_risks_summary TEXT,
  npc_common_knowledge_summary TEXT,
  llm_generation_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  llm_forbidden_assumptions JSONB NOT NULL DEFAULT '[]'::jsonb,
  llm_context_summary TEXT,
  validation_notes TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.region_landscape_templates (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  landscape_template_id TEXT NOT NULL REFERENCES world_base.landscape_templates(id) ON DELETE CASCADE,
  is_allowed BOOLEAN NOT NULL DEFAULT true,
  is_common BOOLEAN NOT NULL DEFAULT false,
  is_dominant BOOLEAN NOT NULL DEFAULT false,
  is_rare BOOLEAN NOT NULL DEFAULT false,
  generation_weight NUMERIC NOT NULL DEFAULT 0 CHECK (generation_weight >= 0),
  allowed_scale_levels JSONB NOT NULL DEFAULT '[]'::jsonb,
  allowed_node_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  regional_limits TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (region_id, landscape_template_id)
);

CREATE TABLE world_base.region_water_body_templates (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  water_body_template_id TEXT NOT NULL REFERENCES world_base.water_body_templates(id) ON DELETE CASCADE,
  is_allowed BOOLEAN NOT NULL DEFAULT true,
  is_common BOOLEAN NOT NULL DEFAULT false,
  is_dominant BOOLEAN NOT NULL DEFAULT false,
  is_rare BOOLEAN NOT NULL DEFAULT false,
  generation_weight NUMERIC NOT NULL DEFAULT 0 CHECK (generation_weight >= 0),
  allowed_scale_levels JSONB NOT NULL DEFAULT '[]'::jsonb,
  allowed_node_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  regional_limits TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (region_id, water_body_template_id)
);

CREATE TABLE world_base.region_land_use_templates (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  land_use_template_id TEXT NOT NULL REFERENCES world_base.land_use_templates(id) ON DELETE CASCADE,
  is_allowed BOOLEAN NOT NULL DEFAULT true,
  is_common BOOLEAN NOT NULL DEFAULT false,
  is_rare BOOLEAN NOT NULL DEFAULT false,
  generation_weight NUMERIC NOT NULL DEFAULT 0 CHECK (generation_weight >= 0),
  allowed_scale_levels JSONB NOT NULL DEFAULT '[]'::jsonb,
  allowed_node_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  regional_limits TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (region_id, land_use_template_id)
);

CREATE TABLE world_base.region_place_templates (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  place_template_id TEXT NOT NULL REFERENCES world_base.place_templates(id) ON DELETE CASCADE,
  is_allowed BOOLEAN NOT NULL DEFAULT true,
  is_common BOOLEAN NOT NULL DEFAULT false,
  is_rare BOOLEAN NOT NULL DEFAULT false,
  generation_weight NUMERIC NOT NULL DEFAULT 0 CHECK (generation_weight >= 0),
  allowed_scale_levels JSONB NOT NULL DEFAULT '[]'::jsonb,
  allowed_node_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  regional_limits TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (region_id, place_template_id)
);

CREATE TABLE world_base.region_neighbors (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  neighbor_region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  direction TEXT,
  border_type TEXT,
  connection_type TEXT,
  trade_connection TEXT,
  military_pressure TEXT,
  political_relation TEXT,
  cultural_relation TEXT,
  religious_relation TEXT,
  route_connection_summary TEXT,
  known_to_commoners TEXT,
  known_to_traders TEXT,
  known_to_elites TEXT,
  known_to_clergy TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.region_laws (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  title TEXT,
  slug TEXT,
  law_type TEXT CHECK (law_type IS NULL OR law_type IN (
    'property','violence','weapon','travel','hospitality','debt','trade','religious','status','punishment','court','tax','custom'
  )),
  applies_to_statuses JSONB NOT NULL DEFAULT '[]'::jsonb,
  applies_to_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  applies_to_places JSONB NOT NULL DEFAULT '[]'::jsonb,
  period_start_year INTEGER,
  period_end_year INTEGER,
  summary TEXT,
  rule_text TEXT,
  custom_basis TEXT,
  authority_enforcing TEXT,
  punishment_or_consequence TEXT,
  dispute_resolution TEXT,
  property_effect TEXT,
  violence_effect TEXT,
  weapon_effect TEXT,
  travel_effect TEXT,
  trade_effect TEXT,
  religious_effect TEXT,
  who_knows_this TEXT,
  npc_behavior_effect TEXT,
  player_risk TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.region_economy (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  title TEXT,
  slug TEXT,
  economy_type TEXT CHECK (economy_type IS NULL OR economy_type IN (
    'farming','fishing','hunting','fur','beekeeping','logging','charcoal','tar','iron','salt','livestock','craft','trade','transport','monastery_economy','military_supply'
  )),
  resource_or_activity TEXT,
  production_method TEXT,
  seasonality TEXT,
  required_landscape TEXT,
  required_settlement_type TEXT,
  required_tools JSONB NOT NULL DEFAULT '[]'::jsonb,
  required_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  labor_intensity TEXT,
  wealth_level TEXT,
  risk_level TEXT,
  goods_produced JSONB NOT NULL DEFAULT '[]'::jsonb,
  goods_consumed JSONB NOT NULL DEFAULT '[]'::jsonb,
  goods_imported JSONB NOT NULL DEFAULT '[]'::jsonb,
  goods_exported JSONB NOT NULL DEFAULT '[]'::jsonb,
  trade_graph_edges JSONB NOT NULL DEFAULT '[]'::jsonb,
  market_access TEXT,
  storage_requirements TEXT,
  spoilage_or_loss_risk TEXT,
  who_controls_it TEXT,
  tax_or_duty TEXT,
  social_status_link TEXT,
  conflict_potential TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Universal social archetype layer (canonical positions before regional terms)
