CREATE TABLE world_base.skill_catalog (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  summary TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.occupation_skill_defaults (
  occupation_archetype_id TEXT PRIMARY KEY REFERENCES world_base.occupation_archetypes(id) ON DELETE CASCADE,
  primary_skill_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  secondary_skill_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  gate_skill_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  forbidden_skill_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  default_level_logic TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.role_occupation_rules (
  role_archetype_id TEXT NOT NULL REFERENCES world_base.social_role_archetypes(id) ON DELETE CASCADE,
  occupation_archetype_id TEXT NOT NULL REFERENCES world_base.occupation_archetypes(id) ON DELETE CASCADE,
  is_allowed BOOLEAN NOT NULL DEFAULT true,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (role_archetype_id, occupation_archetype_id)
);

CREATE TABLE world_base.universal_archetype_proposals (
  id TEXT PRIMARY KEY,
  source_region_id TEXT REFERENCES world_base.regions(id) ON DELETE SET NULL,
  proposal_type TEXT CHECK (proposal_type IS NULL OR proposal_type IN ('social_position', 'occupation', 'skill', 'other')),
  local_term TEXT,
  why_existing_archetypes_not_enough TEXT,
  proposed_archetype_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  affected_regions JSONB NOT NULL DEFAULT '[]'::jsonb,
  review_status TEXT NOT NULL DEFAULT 'pending' CHECK (review_status IN ('pending', 'approved', 'rejected')),
  review_notes TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.region_social_roles (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  title TEXT,
  slug TEXT,
  role_group TEXT CHECK (role_group IS NULL OR role_group IN (
    'elite','clergy','warrior','merchant','craftsman','peasant','dependent','slave','servant','outsider','marginal','official'
  )),
  social_position_archetype_id TEXT REFERENCES world_base.social_position_archetypes(id) ON DELETE RESTRICT,
  social_class_id TEXT REFERENCES world_base.social_classes(id) ON DELETE RESTRICT,
  role_archetype_id TEXT REFERENCES world_base.social_role_archetypes(id) ON DELETE RESTRICT,
  legal_status_archetype_id TEXT REFERENCES world_base.legal_status_archetypes(id) ON DELETE SET NULL,
  dependency_archetype_id TEXT REFERENCES world_base.dependency_archetypes(id) ON DELETE SET NULL,
  mobility_archetype_id TEXT REFERENCES world_base.mobility_archetypes(id) ON DELETE SET NULL,
  mapping_review_status TEXT CHECK (mapping_review_status IS NULL OR mapping_review_status IN ('pending', 'approved', 'accepted_with_caution', 'rejected')),
  mapping_confidence TEXT,
  mapping_notes TEXT,
  status_level TEXT,
  free_status TEXT,
  dependency_type TEXT,
  wealth_level TEXT,
  legal_capacity TEXT,
  mobility_level TEXT,
  social_respect TEXT,
  vulnerability_level TEXT,
  allowed_occupations JSONB NOT NULL DEFAULT '[]'::jsonb,
  forbidden_occupations JSONB NOT NULL DEFAULT '[]'::jsonb,
  allowed_weapons JSONB NOT NULL DEFAULT '[]'::jsonb,
  forbidden_weapons JSONB NOT NULL DEFAULT '[]'::jsonb,
  allowed_places JSONB NOT NULL DEFAULT '[]'::jsonb,
  restricted_places JSONB NOT NULL DEFAULT '[]'::jsonb,
  property_rights TEXT,
  travel_rights TEXT,
  trade_rights TEXT,
  court_rights TEXT,
  tax_obligations TEXT,
  service_obligations TEXT,
  typical_clothing TEXT,
  typical_equipment JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_knowledge JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_speech_register TEXT,
  typical_fears JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_goals JSONB NOT NULL DEFAULT '[]'::jsonb,
  who_commands_them TEXT,
  who_protects_them TEXT,
  who_can_punish_them TEXT,
  relation_to_church TEXT,
  relation_to_power TEXT,
  npc_generation_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  player_character_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.region_occupations (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  title TEXT,
  slug TEXT,
  occupation_group TEXT CHECK (occupation_group IS NULL OR occupation_group IN (
    'agriculture','fishing','forest','craft','trade','transport','military','religious','service','administration','criminal','healing','hospitality'
  )),
  occupation_archetype_id TEXT REFERENCES world_base.occupation_archetypes(id) ON DELETE RESTRICT,
  mapping_review_status TEXT CHECK (mapping_review_status IS NULL OR mapping_review_status IN ('pending', 'approved', 'accepted_with_caution', 'rejected')),
  mapping_confidence TEXT,
  mapping_notes TEXT,
  summary TEXT,
  allowed_social_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  forbidden_social_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_status TEXT,
  typical_wealth TEXT,
  typical_gender_age_rules TEXT,
  required_location_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  required_economy_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  required_tools JSONB NOT NULL DEFAULT '[]'::jsonb,
  required_materials JSONB NOT NULL DEFAULT '[]'::jsonb,
  produced_goods JSONB NOT NULL DEFAULT '[]'::jsonb,
  services_provided JSONB NOT NULL DEFAULT '[]'::jsonb,
  seasonality TEXT,
  work_rhythm TEXT,
  income_logic TEXT,
  typical_skills JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_attributes JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_clothing TEXT,
  typical_equipment JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_risks JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_knowledge JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_contacts JSONB NOT NULL DEFAULT '[]'::jsonb,
  settlement_generation_weight TEXT,
  npc_generation_weight TEXT,
  rarity TEXT,
  is_historical_fact BOOLEAN NOT NULL DEFAULT false,
  is_generated_allowed BOOLEAN NOT NULL DEFAULT false,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.region_place_generation_rules (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  title TEXT,
  slug TEXT,
  template_type TEXT CHECK (template_type IS NULL OR template_type IN (
    'village','fishing_village','forest_camp','charcoal_burner_camp','logging_camp','winter_hut','pogost','ferry','ford','roadside_inn','market_site','monastery_dependency','watch_post','hunting_camp','beekeeping_site'
  )),
  summary TEXT,
  generation_allowed BOOLEAN NOT NULL DEFAULT false,
  max_instances_per_region INTEGER,
  min_distance_from_major_place TEXT,
  required_landscape TEXT,
  required_economy TEXT,
  required_route_access TEXT,
  required_water_access TEXT,
  seasonal_availability TEXT,
  typical_population_band TEXT,
  typical_household_count TEXT,
  typical_wealth_level TEXT,
  typical_authority TEXT,
  typical_social_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_occupations JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_buildings JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_animals JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_tools JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_goods JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_food_sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_risks JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_conflicts JSONB NOT NULL DEFAULT '[]'::jsonb,
  layout_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  naming_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  access_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  law_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  religion_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  trade_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  defense_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  npc_generation_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  item_generation_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  route_generation_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  historical_plausibility_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.region_material_culture (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  title TEXT,
  slug TEXT,
  material_category TEXT CHECK (material_category IS NULL OR material_category IN (
    'clothing','tool','weapon','armor','food','livestock','container','transport','religious_item','trade_good','household_item','craft_material','luxury','document_or_mark'
  )),
  summary TEXT,
  commonness TEXT,
  status_level TEXT,
  allowed_social_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  restricted_social_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_places JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_owners JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_holders JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_materials JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_condition TEXT,
  typical_quality TEXT,
  typical_value_band TEXT,
  typical_marks JSONB NOT NULL DEFAULT '[]'::jsonb,
  legal_status TEXT,
  social_risk TEXT,
  theft_risk TEXT,
  trade_risk TEXT,
  seasonality TEXT,
  economic_source TEXT,
  import_or_local TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
