CREATE TABLE world_base.region_risks (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  title TEXT,
  slug TEXT,
  risk_type TEXT CHECK (risk_type IS NULL OR risk_type IN (
    'road','weather','law','violence','theft','hunger','disease','wild_animals','social','religious','economic','war','fire','water','cold'
  )),
  summary TEXT,
  applies_to_places JSONB NOT NULL DEFAULT '[]'::jsonb,
  applies_to_graph_edges JSONB NOT NULL DEFAULT '[]'::jsonb,
  applies_to_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  applies_to_occupations JSONB NOT NULL DEFAULT '[]'::jsonb,
  seasonality TEXT,
  trigger_conditions JSONB NOT NULL DEFAULT '[]'::jsonb,
  visible_signs JSONB NOT NULL DEFAULT '[]'::jsonb,
  hidden_causes JSONB NOT NULL DEFAULT '[]'::jsonb,
  possible_consequences JSONB NOT NULL DEFAULT '[]'::jsonb,
  risk_level TEXT,
  frequency TEXT,
  avoidance_methods JSONB NOT NULL DEFAULT '[]'::jsonb,
  mitigation_methods JSONB NOT NULL DEFAULT '[]'::jsonb,
  npc_reactions JSONB NOT NULL DEFAULT '[]'::jsonb,
  law_consequences TEXT,
  economic_consequences TEXT,
  body_state_consequences TEXT,
  item_consequences TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.conflict_templates (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  title TEXT,
  slug TEXT,
  conflict_type TEXT CHECK (conflict_type IS NULL OR conflict_type IN (
    'debt','property','trade','family','labor','status','religious','road','theft','violence','tax','duty','stranger','resource'
  )),
  summary TEXT,
  applies_to_place_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  applies_to_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  applies_to_occupations JSONB NOT NULL DEFAULT '[]'::jsonb,
  trigger_conditions JSONB NOT NULL DEFAULT '[]'::jsonb,
  participants JSONB NOT NULL DEFAULT '[]'::jsonb,
  stakes JSONB NOT NULL DEFAULT '[]'::jsonb,
  visible_signs JSONB NOT NULL DEFAULT '[]'::jsonb,
  hidden_layers JSONB NOT NULL DEFAULT '[]'::jsonb,
  possible_escalation JSONB NOT NULL DEFAULT '[]'::jsonb,
  possible_resolution JSONB NOT NULL DEFAULT '[]'::jsonb,
  law_involvement TEXT,
  authority_involvement TEXT,
  rumor_effect TEXT,
  relationship_effect TEXT,
  economic_effect TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.rumor_templates (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  title TEXT,
  slug TEXT,
  rumor_type TEXT,
  summary TEXT,
  source_role TEXT,
  spread_places JSONB NOT NULL DEFAULT '[]'::jsonb,
  spread_graph_edges JSONB NOT NULL DEFAULT '[]'::jsonb,
  affected_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  linked_event_id TEXT,
  linked_place_id TEXT,
  linked_risk_id TEXT,
  truth_status TEXT CHECK (truth_status IS NULL OR truth_status IN ('true','false','distorted','unknown','mixed')),
  distortion_level TEXT,
  what_is_visible TEXT,
  what_is_hidden TEXT,
  who_believes_it JSONB NOT NULL DEFAULT '[]'::jsonb,
  who_denies_it JSONB NOT NULL DEFAULT '[]'::jsonb,
  danger_of_repeating TEXT,
  possible_effects JSONB NOT NULL DEFAULT '[]'::jsonb,
  expiration_or_update_rule TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.price_bands (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  title TEXT,
  slug TEXT,
  item_or_service_type TEXT,
  value_band TEXT,
  normal_price_description TEXT,
  cheap_condition TEXT,
  expensive_condition TEXT,
  scarcity_factors JSONB NOT NULL DEFAULT '[]'::jsonb,
  seasonal_modifiers JSONB NOT NULL DEFAULT '[]'::jsonb,
  war_modifiers JSONB NOT NULL DEFAULT '[]'::jsonb,
  road_modifiers JSONB NOT NULL DEFAULT '[]'::jsonb,
  status_modifiers JSONB NOT NULL DEFAULT '[]'::jsonb,
  trade_place_modifiers JSONB NOT NULL DEFAULT '[]'::jsonb,
  who_can_afford JSONB NOT NULL DEFAULT '[]'::jsonb,
  who_can_sell JSONB NOT NULL DEFAULT '[]'::jsonb,
  who_controls_supply TEXT,
  barter_options JSONB NOT NULL DEFAULT '[]'::jsonb,
  tax_or_duty TEXT,
  risk_of_fraud TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.seasonal_rules (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  season TEXT CHECK (season IS NULL OR season IN (
    'winter','spring','summer','autumn','rasputitsa','early_winter','late_winter'
  )),
  title TEXT,
  slug TEXT,
  weather_profile TEXT,
  daylight_profile TEXT,
  road_effects JSONB NOT NULL DEFAULT '[]'::jsonb,
  river_effects JSONB NOT NULL DEFAULT '[]'::jsonb,
  forest_effects JSONB NOT NULL DEFAULT '[]'::jsonb,
  field_effects JSONB NOT NULL DEFAULT '[]'::jsonb,
  food_effects JSONB NOT NULL DEFAULT '[]'::jsonb,
  work_effects JSONB NOT NULL DEFAULT '[]'::jsonb,
  trade_effects JSONB NOT NULL DEFAULT '[]'::jsonb,
  war_effects JSONB NOT NULL DEFAULT '[]'::jsonb,
  disease_effects JSONB NOT NULL DEFAULT '[]'::jsonb,
  clothing_requirements JSONB NOT NULL DEFAULT '[]'::jsonb,
  shelter_requirements JSONB NOT NULL DEFAULT '[]'::jsonb,
  available_occupations JSONB NOT NULL DEFAULT '[]'::jsonb,
  restricted_occupations JSONB NOT NULL DEFAULT '[]'::jsonb,
  available_graph_edges JSONB NOT NULL DEFAULT '[]'::jsonb,
  restricted_graph_edges JSONB NOT NULL DEFAULT '[]'::jsonb,
  common_risks JSONB NOT NULL DEFAULT '[]'::jsonb,
  common_scenes JSONB NOT NULL DEFAULT '[]'::jsonb,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.religious_context (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  title TEXT,
  slug TEXT,
  religion_type TEXT,
  summary TEXT,
  dominant_religion TEXT,
  minority_religions JSONB NOT NULL DEFAULT '[]'::jsonb,
  religious_authority TEXT,
  sacred_places JSONB NOT NULL DEFAULT '[]'::jsonb,
  monastery_presence TEXT,
  church_presence TEXT,
  ritual_calendar JSONB NOT NULL DEFAULT '[]'::jsonb,
  taboos JSONB NOT NULL DEFAULT '[]'::jsonb,
  oath_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  burial_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  hospitality_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  charity_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  conflict_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  role_effects JSONB NOT NULL DEFAULT '[]'::jsonb,
  law_effects JSONB NOT NULL DEFAULT '[]'::jsonb,
  npc_knowledge JSONB NOT NULL DEFAULT '[]'::jsonb,
  player_risks JSONB NOT NULL DEFAULT '[]'::jsonb,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.region_npc_knowledge (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  social_role_id TEXT REFERENCES world_base.region_social_roles(id) ON DELETE SET NULL,
  occupation_id TEXT REFERENCES world_base.region_occupations(id) ON DELETE SET NULL,
  knowledge_type TEXT CHECK (knowledge_type IS NULL OR knowledge_type IN (
    'common','role_based','occupation_based','elite','clergy','trader','outsider','local','rumor','false_belief'
  )),
  title TEXT,
  summary TEXT,
  knows_as_fact JSONB NOT NULL DEFAULT '[]'::jsonb,
  knows_as_rumor JSONB NOT NULL DEFAULT '[]'::jsonb,
  common_mistakes JSONB NOT NULL DEFAULT '[]'::jsonb,
  cannot_know JSONB NOT NULL DEFAULT '[]'::jsonb,
  taboo_topics JSONB NOT NULL DEFAULT '[]'::jsonb,
  dangerous_to_say JSONB NOT NULL DEFAULT '[]'::jsonb,
  who_they_trust JSONB NOT NULL DEFAULT '[]'::jsonb,
  who_they_fear JSONB NOT NULL DEFAULT '[]'::jsonb,
  regional_knowledge JSONB NOT NULL DEFAULT '[]'::jsonb,
  local_place_knowledge JSONB NOT NULL DEFAULT '[]'::jsonb,
  law_knowledge JSONB NOT NULL DEFAULT '[]'::jsonb,
  economy_knowledge JSONB NOT NULL DEFAULT '[]'::jsonb,
  religion_knowledge JSONB NOT NULL DEFAULT '[]'::jsonb,
  historical_knowledge JSONB NOT NULL DEFAULT '[]'::jsonb,
  route_knowledge JSONB NOT NULL DEFAULT '[]'::jsonb,
  social_order_knowledge JSONB NOT NULL DEFAULT '[]'::jsonb,
  price_knowledge JSONB NOT NULL DEFAULT '[]'::jsonb,
  speech_style_notes TEXT,
  behavior_effect TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.region_npc_generation_rules (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  title TEXT,
  slug TEXT,
  npc_profile_type TEXT CHECK (npc_profile_type IS NULL OR npc_profile_type IN ('background','scene','key','group')),
  applies_to_place_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  applies_to_location_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  allowed_social_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  allowed_occupations JSONB NOT NULL DEFAULT '[]'::jsonb,
  forbidden_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  rarity_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  name_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  age_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  gender_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  status_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  wealth_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  clothing_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  equipment_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  speech_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  knowledge_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  fear_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  goal_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  authority_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  reaction_to_strangers TEXT,
  reaction_to_violence TEXT,
  reaction_to_theft TEXT,
  reaction_to_trade TEXT,
  reaction_to_law TEXT,
  background_npc_minimum INTEGER,
  scene_npc_minimum INTEGER,
  key_npc_minimum INTEGER,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
