CREATE TABLE world_base.place_generation_limits (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  place_template_id TEXT REFERENCES world_base.region_place_generation_rules(id) ON DELETE SET NULL,
  max_total INTEGER,
  max_per_subregion INTEGER,
  min_total_if_region_active INTEGER,
  economic_basis_required BOOLEAN NOT NULL DEFAULT false,
  route_basis_required BOOLEAN NOT NULL DEFAULT false,
  water_basis_required BOOLEAN NOT NULL DEFAULT false,
  authority_basis_required BOOLEAN NOT NULL DEFAULT false,
  historical_anchor_basis_required BOOLEAN NOT NULL DEFAULT false,
  allowed_near_place_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  forbidden_near_place_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  minimum_distance_band TEXT,
  maximum_distance_band TEXT,
  density_logic TEXT,
  naming_policy TEXT,
  duplication_policy TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.llm_context_packs (
  id TEXT PRIMARY KEY,
  region_id TEXT REFERENCES world_base.regions(id) ON DELETE SET NULL,
  title TEXT,
  slug TEXT,
  context_type TEXT CHECK (context_type IS NULL OR context_type IN (
    'region_start','new_place_generation','npc_generation','route_generation','historical_check','scene_context','repair_context'
  )),
  summary TEXT,
  included_tables JSONB NOT NULL DEFAULT '[]'::jsonb,
  included_record_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  prompt_text TEXT,
  hard_constraints JSONB NOT NULL DEFAULT '[]'::jsonb,
  forbidden_assumptions JSONB NOT NULL DEFAULT '[]'::jsonb,
  known_gaps JSONB NOT NULL DEFAULT '[]'::jsonb,
  use_when TEXT,
  do_not_use_when TEXT,
  max_tokens_estimate INTEGER,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.llm_validation_rules (
  id TEXT PRIMARY KEY,
  region_id TEXT REFERENCES world_base.regions(id) ON DELETE SET NULL,
  title TEXT,
  slug TEXT,
  validation_type TEXT,
  rule_text TEXT,
  applies_to_table TEXT,
  applies_to_generation_step TEXT,
  severity TEXT CHECK (severity IS NULL OR severity IN ('warning','error','hard_block')),
  failure_message TEXT,
  repair_instruction TEXT,
  examples_valid JSONB NOT NULL DEFAULT '[]'::jsonb,
  examples_invalid JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.region_gaps (
  id TEXT PRIMARY KEY,
  region_id TEXT REFERENCES world_base.regions(id) ON DELETE SET NULL,
  title TEXT,
  slug TEXT,
  gap_type TEXT,
  summary TEXT,
  why_needed TEXT,
  affected_tables JSONB NOT NULL DEFAULT '[]'::jsonb,
  priority TEXT,
  risk_if_missing TEXT,
  suggested_sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  suggested_research_query TEXT,
  current_workaround TEXT,
  blocked_generation_steps JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.places (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  template_id TEXT REFERENCES world_base.region_place_generation_rules(id) ON DELETE SET NULL,
  slug TEXT,
  canonical_name TEXT,
  display_name TEXT,
  alt_names JSONB NOT NULL DEFAULT '[]'::jsonb,
  place_type TEXT CHECK (place_type IS NULL OR place_type IN (
    'city','posad','village','selo','pogost','monastery','fortress','yard','inn','ferry','ford','pier','market','road_segment','forest_camp','winter_hut','watch_post','border_zone'
  )),
  historical_status TEXT,
  is_fixed_historical_place BOOLEAN NOT NULL DEFAULT false,
  is_generated_place BOOLEAN NOT NULL DEFAULT false,
  generation_source TEXT,
  period_start_year INTEGER,
  period_end_year INTEGER,
  summary TEXT,
  function_in_region TEXT,
  economic_basis TEXT,
  political_control TEXT,
  religious_control TEXT,
  legal_status TEXT,
  owner_or_holder TEXT,
  population_band TEXT,
  wealth_level TEXT,
  landscape TEXT,
  water_access TEXT,
  road_access TEXT,
  defense_level TEXT,
  market_level TEXT,
  craft_level TEXT,
  food_supply_level TEXT,
  risk_level TEXT,
  known_to_commoners TEXT,
  known_to_traders TEXT,
  known_to_elites TEXT,
  known_to_clergy TEXT,
  known_to_outsiders TEXT,
  visible_description TEXT,
  hidden_notes TEXT,
  map_notes TEXT,
  llm_generation_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  llm_forbidden_changes JSONB NOT NULL DEFAULT '[]'::jsonb,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.graph_nodes (
  id TEXT PRIMARY KEY,
  slug TEXT,
  title TEXT,
  node_type TEXT CHECK (node_type IS NULL OR node_type IN (
    'world_region','subregion','place','location','minilocation','scene_anchor',
    'route_junction','river_junction','ford','ferry','gate','road_segment',
    'water_segment','border_crossing','sea_crossing','mountain_pass','desert_oasis','steppe_camp',
    'region_cell','cell_subgraph','map_corridor','geographic_landmark','historical_landmark'
  )),
  scale_level TEXT CHECK (scale_level IS NULL OR scale_level IN ('G0', 'G1', 'G2', 'G3', 'G4', 'G5')),
  parent_node_id TEXT REFERENCES world_base.graph_nodes(id) ON DELETE SET NULL,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  place_id TEXT REFERENCES world_base.places(id) ON DELETE SET NULL,
  grid_x INTEGER,
  grid_y INTEGER,
  grid_z INTEGER NOT NULL DEFAULT 0,
  region_cell_code TEXT,
  cell_shape TEXT CHECK (cell_shape IS NULL OR cell_shape IN ('square', 'partial', 'irregular', 'water', 'border')),
  region_cell_status TEXT CHECK (region_cell_status IS NULL OR region_cell_status IN ('active', 'partial', 'border', 'outside_region', 'water_only')),
  cell_size_km NUMERIC,
  crossing_base_gu NUMERIC,
  crossing_base_time_hours NUMERIC,
  primary_landscape_template_id TEXT REFERENCES world_base.landscape_templates(id) ON DELETE SET NULL,
  secondary_landscape_template_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  landscape_mix_notes TEXT,
  primary_water_body_template_id TEXT REFERENCES world_base.water_body_templates(id) ON DELETE SET NULL,
  secondary_water_body_template_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  hydrology_notes TEXT,
  land_use_template_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  place_template_id TEXT REFERENCES world_base.place_templates(id) ON DELETE SET NULL,
  terrain_profile TEXT,
  water_profile TEXT,
  road_profile TEXT,
  settlement_density TEXT,
  dominant_content TEXT,
  known_landmarks JSONB NOT NULL DEFAULT '[]'::jsonb,
  canonical_corridors JSONB NOT NULL DEFAULT '[]'::jsonb,
  neighbor_node_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  historical_status TEXT,
  is_known_to_player_default BOOLEAN NOT NULL DEFAULT false,
  is_known_to_character_default BOOLEAN NOT NULL DEFAULT false,
  summary TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (
    NOT (scale_level = 'G1' AND node_type = 'region_cell')
    OR (
      grid_x IS NOT NULL AND grid_y IS NOT NULL AND grid_z IS NOT NULL
      AND cell_size_km IS NOT NULL AND crossing_base_gu IS NOT NULL
      AND crossing_base_time_hours IS NOT NULL AND region_cell_status IS NOT NULL
      AND primary_landscape_template_id IS NOT NULL
    )
  ),
  FOREIGN KEY (region_id, primary_landscape_template_id)
    REFERENCES world_base.region_landscape_templates(region_id, landscape_template_id)
);

CREATE TABLE world_base.graph_edges (
  id TEXT PRIMARY KEY,
  from_node_id TEXT NOT NULL REFERENCES world_base.graph_nodes(id) ON DELETE CASCADE,
  to_node_id TEXT NOT NULL REFERENCES world_base.graph_nodes(id) ON DELETE CASCADE,
  reverse_edge_id TEXT REFERENCES world_base.graph_edges(id) ON DELETE SET NULL,
  scale_level TEXT CHECK (scale_level IS NULL OR scale_level IN ('G0', 'G1', 'G2', 'G3', 'G4', 'G5')),
  edge_type TEXT CHECK (edge_type IS NULL OR edge_type IN (
    'road','path','river','lake_route','sea_route','winter_road','ford','ferry','bridge',
    'gate','street','door','yard_passage','forest_track','offroad_crossing','mountain_pass','desert_route',
    'steppe_route','border_transition','corridor_segment','portage'
  )),
  base_gu NUMERIC,
  base_distance_km NUMERIC,
  base_time_minutes NUMERIC,
  base_time_hours NUMERIC,
  base_time_days NUMERIC,
  route_template_id TEXT REFERENCES world_base.route_templates(id) ON DELETE SET NULL,
  landscape_template_id TEXT REFERENCES world_base.landscape_templates(id) ON DELETE SET NULL,
  water_body_template_id TEXT REFERENCES world_base.water_body_templates(id) ON DELETE SET NULL,
  terrain_type TEXT,
  route_surface TEXT,
  seasonal_rule TEXT,
  access_rule TEXT,
  risk_level TEXT,
  known_to_commoners TEXT,
  known_to_traders TEXT,
  known_to_elites TEXT,
  known_to_clergy TEXT,
  known_to_character_default TEXT,
  requires_guide BOOLEAN NOT NULL DEFAULT false,
  requires_boat BOOLEAN NOT NULL DEFAULT false,
  requires_horse BOOLEAN NOT NULL DEFAULT false,
  requires_sled BOOLEAN NOT NULL DEFAULT false,
  requires_permission BOOLEAN NOT NULL DEFAULT false,
  requires_orientation_check BOOLEAN NOT NULL DEFAULT false,
  orientation_difficulty TEXT CHECK (orientation_difficulty IS NULL OR orientation_difficulty IN ('none', 'easy', 'ordinary', 'hard', 'dangerous', 'extreme')),
  movement_risk_profile JSONB NOT NULL DEFAULT '[]'::jsonb,
  failure_consequences JSONB NOT NULL DEFAULT '[]'::jsonb,
  historical_status TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (NOT (edge_type = 'offroad_crossing') OR landscape_template_id IS NOT NULL),
  CHECK (edge_type IS NULL OR edge_type NOT IN ('river', 'lake_route', 'sea_route', 'ford', 'ferry', 'bridge') OR water_body_template_id IS NOT NULL),
  CHECK (edge_type IS NULL OR edge_type NOT IN ('road', 'path', 'forest_track', 'winter_road', 'portage', 'corridor_segment') OR route_template_id IS NOT NULL)
);

CREATE TABLE world_base.historical_anchors (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  place_id TEXT REFERENCES world_base.places(id) ON DELETE SET NULL,
  slug TEXT,
  canonical_name TEXT,
  display_name TEXT,
  anchor_type TEXT CHECK (anchor_type IS NULL OR anchor_type IN (
    'city','fortress','monastery','market','river','ford','ferry','road','winter_road','border','battle_site','princely_court','bishopric'
  )),
  summary TEXT,
  historical_status TEXT,
  period_start_year INTEGER,
  period_end_year INTEGER,
  approximate_bearing TEXT,
  distance_band TEXT,
  zone_of_influence TEXT,
  access_graph_edges JSONB NOT NULL DEFAULT '[]'::jsonb,
  visible_signs JSONB NOT NULL DEFAULT '[]'::jsonb,
  economic_influence TEXT,
  political_influence TEXT,
  religious_influence TEXT,
  military_influence TEXT,
  trade_influence TEXT,
  character_knowledge_common TEXT,
  character_knowledge_trader TEXT,
  character_knowledge_elite TEXT,
  character_knowledge_clergy TEXT,
  character_knowledge_outsider TEXT,
  discovery_conditions JSONB NOT NULL DEFAULT '[]'::jsonb,
  llm_use_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  llm_forbidden_changes JSONB NOT NULL DEFAULT '[]'::jsonb,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
