CREATE TABLE world_base.historical_events (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  title TEXT,
  slug TEXT,
  event_type TEXT,
  period_start_year INTEGER,
  period_end_year INTEGER,
  approximate_date TEXT,
  date_confidence TEXT,
  historical_status TEXT,
  summary TEXT,
  cause TEXT,
  participants JSONB NOT NULL DEFAULT '[]'::jsonb,
  affected_regions JSONB NOT NULL DEFAULT '[]'::jsonb,
  affected_places JSONB NOT NULL DEFAULT '[]'::jsonb,
  current_phase TEXT,
  phase_logic JSONB NOT NULL DEFAULT '[]'::jsonb,
  local_signs JSONB NOT NULL DEFAULT '[]'::jsonb,
  economic_effect TEXT,
  road_effect TEXT,
  law_effect TEXT,
  social_effect TEXT,
  military_effect TEXT,
  religious_effect TEXT,
  npc_knowledge_effect TEXT,
  rumor_effect TEXT,
  what_commoners_know TEXT,
  what_traders_know TEXT,
  what_elites_know TEXT,
  what_clergy_know TEXT,
  what_outsiders_know TEXT,
  hidden_truth_policy TEXT,
  future_knowledge_forbidden JSONB NOT NULL DEFAULT '[]'::jsonb,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.historical_figures (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  title TEXT,
  slug TEXT,
  canonical_name TEXT,
  alt_names JSONB NOT NULL DEFAULT '[]'::jsonb,
  figure_type TEXT,
  social_status TEXT,
  political_role TEXT,
  religious_role TEXT,
  military_role TEXT,
  social_class_id TEXT,
  role_archetype_id TEXT,
  social_position_archetype_id TEXT,
  period_start_year INTEGER,
  period_end_year INTEGER,
  summary TEXT,
  region_of_influence TEXT,
  linked_events JSONB NOT NULL DEFAULT '[]'::jsonb,
  linked_places JSONB NOT NULL DEFAULT '[]'::jsonb,
  current_location_policy TEXT,
  direct_encounter_policy TEXT,
  influence_method TEXT,
  orders_or_effects JSONB NOT NULL DEFAULT '[]'::jsonb,
  reputation TEXT,
  what_commoners_know TEXT,
  what_traders_know TEXT,
  what_elites_know TEXT,
  what_clergy_know TEXT,
  what_outsiders_know TEXT,
  can_appear_directly BOOLEAN NOT NULL DEFAULT false,
  appearance_conditions JSONB NOT NULL DEFAULT '[]'::jsonb,
  forbidden_uses JSONB NOT NULL DEFAULT '[]'::jsonb,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.place_locations (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  place_id TEXT NOT NULL REFERENCES world_base.places(id) ON DELETE CASCADE,
  slug TEXT,
  title TEXT,
  location_type TEXT CHECK (location_type IS NULL OR location_type IN (
    'gate','street','market','yard','churchyard','riverbank','pier','house','hall','barn','stable','workshop','storehouse','forest_edge','road_approach','monastery_yard','fortification_wall'
  )),
  summary TEXT,
  function TEXT,
  access_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  visibility_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  who_controls_access TEXT,
  typical_npc_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_objects JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_buildings JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_sounds JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_smells JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_risks JSONB NOT NULL DEFAULT '[]'::jsonb,
  social_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  law_risks JSONB NOT NULL DEFAULT '[]'::jsonb,
  connected_location_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  entry_points JSONB NOT NULL DEFAULT '[]'::jsonb,
  closed_zones JSONB NOT NULL DEFAULT '[]'::jsonb,
  public_private_level TEXT,
  crowd_level TEXT,
  light_level TEXT,
  weather_exposure TEXT,
  llm_generation_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  item_generation_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  npc_generation_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.place_minilocations (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  place_id TEXT NOT NULL REFERENCES world_base.places(id) ON DELETE CASCADE,
  location_id TEXT NOT NULL REFERENCES world_base.place_locations(id) ON DELETE CASCADE,
  slug TEXT,
  title TEXT,
  minilocation_type TEXT CHECK (minilocation_type IS NULL OR minilocation_type IN (
    'near_door','near_hearth','under_shed','behind_cart','near_gate','near_table','near_chest','near_boat','near_well','at_threshold','in_shadow','beside_fire'
  )),
  summary TEXT,
  position_description TEXT,
  access_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  visibility TEXT,
  cover_or_hiding TEXT,
  noise_level TEXT,
  light_level TEXT,
  weather_exposure TEXT,
  nearby_objects JSONB NOT NULL DEFAULT '[]'::jsonb,
  nearby_npc_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  possible_actions JSONB NOT NULL DEFAULT '[]'::jsonb,
  movement_cost TEXT,
  risk_notes TEXT,
  connected_minilocation_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  anchor_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.scene_anchors (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  place_id TEXT NOT NULL REFERENCES world_base.places(id) ON DELETE CASCADE,
  location_id TEXT REFERENCES world_base.place_locations(id) ON DELETE SET NULL,
  minilocation_id TEXT REFERENCES world_base.place_minilocations(id) ON DELETE SET NULL,
  slug TEXT,
  title TEXT,
  anchor_type TEXT,
  summary TEXT,
  physical_description TEXT,
  is_fixed BOOLEAN NOT NULL DEFAULT false,
  is_movable BOOLEAN NOT NULL DEFAULT false,
  is_container BOOLEAN NOT NULL DEFAULT false,
  is_passage BOOLEAN NOT NULL DEFAULT false,
  is_obstacle BOOLEAN NOT NULL DEFAULT false,
  is_light_source BOOLEAN NOT NULL DEFAULT false,
  is_cover BOOLEAN NOT NULL DEFAULT false,
  is_dangerous BOOLEAN NOT NULL DEFAULT false,
  access_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  visibility_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  ownership_status TEXT,
  controller TEXT,
  condition TEXT,
  interaction_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  risk_notes TEXT,
  linked_item_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  linked_graph_edge_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.place_buildings (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  place_id TEXT NOT NULL REFERENCES world_base.places(id) ON DELETE CASCADE,
  location_id TEXT REFERENCES world_base.place_locations(id) ON DELETE SET NULL,
  slug TEXT,
  title TEXT,
  building_type TEXT CHECK (building_type IS NULL OR building_type IN (
    'house','hut','barn','stable','storehouse','workshop','church','monastery_cell','gatehouse','tower','wall','bathhouse','mill','inn','warehouse','boathouse','smithy'
  )),
  summary TEXT,
  function TEXT,
  owner_or_holder TEXT,
  controller TEXT,
  public_private_level TEXT,
  access_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  legal_status TEXT,
  religious_status TEXT,
  wealth_level TEXT,
  condition TEXT,
  materials JSONB NOT NULL DEFAULT '[]'::jsonb,
  size_band TEXT,
  floors_or_sections TEXT,
  typical_rooms JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_objects JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_npc_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_activities JSONB NOT NULL DEFAULT '[]'::jsonb,
  storage_logic TEXT,
  locked_areas JSONB NOT NULL DEFAULT '[]'::jsonb,
  hidden_area_policy TEXT,
  fire_risk TEXT,
  theft_risk TEXT,
  social_risk TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.historical_event_phases (
  id TEXT PRIMARY KEY,
  event_id TEXT NOT NULL REFERENCES world_base.historical_events(id) ON DELETE CASCADE,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  phase_name TEXT CHECK (phase_name IS NULL OR phase_name IN ('background','omens','escalation','impact','aftermath')),
  phase_order INTEGER,
  date_start TEXT,
  date_end TEXT,
  date_confidence TEXT,
  trigger_condition TEXT,
  summary TEXT,
  visible_signs JSONB NOT NULL DEFAULT '[]'::jsonb,
  hidden_processes JSONB NOT NULL DEFAULT '[]'::jsonb,
  affected_places JSONB NOT NULL DEFAULT '[]'::jsonb,
  affected_graph_edges JSONB NOT NULL DEFAULT '[]'::jsonb,
  affected_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  affected_goods JSONB NOT NULL DEFAULT '[]'::jsonb,
  npc_behavior_changes JSONB NOT NULL DEFAULT '[]'::jsonb,
  price_changes JSONB NOT NULL DEFAULT '[]'::jsonb,
  security_changes JSONB NOT NULL DEFAULT '[]'::jsonb,
  law_changes JSONB NOT NULL DEFAULT '[]'::jsonb,
  rumor_templates JSONB NOT NULL DEFAULT '[]'::jsonb,
  delayed_event_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  what_character_can_know TEXT,
  what_character_cannot_know TEXT,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE world_base.item_templates (
  id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL REFERENCES world_base.regions(id) ON DELETE CASCADE,
  material_culture_id TEXT REFERENCES world_base.region_material_culture(id) ON DELETE SET NULL,
  title TEXT,
  slug TEXT,
  item_type TEXT,
  summary TEXT,
  function TEXT,
  typical_material TEXT,
  weight_band TEXT,
  size_band TEXT,
  durability TEXT,
  quality_band TEXT,
  value_band TEXT,
  rarity TEXT,
  legal_status TEXT,
  social_status_signal TEXT,
  typical_owner_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_holder_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_locations JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_containers JSONB NOT NULL DEFAULT '[]'::jsonb,
  visibility_default TEXT,
  access_default TEXT,
  marking_default TEXT,
  risk_default TEXT,
  skill_use JSONB NOT NULL DEFAULT '[]'::jsonb,
  attribute_use JSONB NOT NULL DEFAULT '[]'::jsonb,
  possible_modifiers JSONB NOT NULL DEFAULT '[]'::jsonb,
  failure_risks JSONB NOT NULL DEFAULT '[]'::jsonb,
  damage_or_wear_rules JSONB NOT NULL DEFAULT '[]'::jsonb,
  game_use TEXT,
  limits TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'usable_with_caution', 'approved', 'needs_review', 'conflict', 'rejected')),
  confidence TEXT NOT NULL DEFAULT 'unknown' CHECK (confidence IN ('unknown', 'low', 'medium_low', 'medium', 'medium_high', 'high')),
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  audit_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
