-- Spatial architecture v3 / P10 target-only orientation and route authoring.
-- This part deliberately does not reinterpret or write legacy graph_edges.

CREATE TABLE IF NOT EXISTS world_base.spatial_v3_orientation_reference_frames (
  entity_kind TEXT NOT NULL DEFAULT 'orientation_reference_frame' CHECK (entity_kind = 'orientation_reference_frame'),
  id TEXT NOT NULL, version INTEGER NOT NULL CHECK (version > 0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT,
  scope_entity_kind TEXT NOT NULL, scope_entity_id TEXT NOT NULL, scope_entity_version INTEGER NOT NULL CHECK (scope_entity_version > 0),
  parent_frame_id TEXT, parent_frame_version INTEGER,
  north_offset_mdeg INTEGER NOT NULL CHECK (north_offset_mdeg BETWEEN 0 AND 359999),
  status TEXT NOT NULL CHECK (status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT,
  canonical_digest TEXT NOT NULL CHECK (canonical_digest ~ '^[a-f0-9]{64}$'),
  PRIMARY KEY (id, version), UNIQUE (id, version, world_revision_id),
  FOREIGN KEY (entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY (parent_frame_id,parent_frame_version) REFERENCES world_base.spatial_v3_orientation_reference_frames(id,version) ON DELETE RESTRICT,
  CHECK ((parent_frame_id IS NULL) = (parent_frame_version IS NULL))
);

CREATE TABLE IF NOT EXISTS world_base.spatial_v3_movement_orientation_profiles (
  entity_kind TEXT NOT NULL DEFAULT 'movement_orientation_profile' CHECK (entity_kind = 'movement_orientation_profile'),
  id TEXT NOT NULL, version INTEGER NOT NULL CHECK (version > 0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT,
  reference_frame_id TEXT NOT NULL, reference_frame_version INTEGER NOT NULL,
  profile_kind TEXT NOT NULL CHECK (profile_kind IN ('fixed','curved')), fixed_local_azimuth_mdeg INTEGER CHECK (fixed_local_azimuth_mdeg BETWEEN 0 AND 359999),
  vertical_direction TEXT NOT NULL CHECK (vertical_direction IN ('level','up','down','mixed')),
  reverse_profile_id TEXT, reverse_profile_version INTEGER,
  status TEXT NOT NULL CHECK (status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT,
  canonical_digest TEXT NOT NULL CHECK (canonical_digest ~ '^[a-f0-9]{64}$'),
  PRIMARY KEY (id,version), UNIQUE (id,version,world_revision_id),
  FOREIGN KEY (entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY (reference_frame_id,reference_frame_version,world_revision_id) REFERENCES world_base.spatial_v3_orientation_reference_frames(id,version,world_revision_id) ON DELETE RESTRICT,
  FOREIGN KEY (reverse_profile_id,reverse_profile_version) REFERENCES world_base.spatial_v3_movement_orientation_profiles(id,version) ON DELETE RESTRICT,
  CHECK ((reverse_profile_id IS NULL) = (reverse_profile_version IS NULL)),
  CHECK ((profile_kind = 'fixed' AND fixed_local_azimuth_mdeg IS NOT NULL) OR (profile_kind = 'curved' AND fixed_local_azimuth_mdeg IS NULL))
);

CREATE TABLE IF NOT EXISTS world_base.spatial_v3_movement_orientation_profile_points (
  profile_id TEXT NOT NULL, profile_version INTEGER NOT NULL, ordinal INTEGER NOT NULL CHECK (ordinal >= 0),
  progress_ppm INTEGER NOT NULL CHECK (progress_ppm BETWEEN 0 AND 1000000), local_azimuth_mdeg INTEGER NOT NULL CHECK (local_azimuth_mdeg BETWEEN 0 AND 359999),
  interpolation_to_next TEXT CHECK (interpolation_to_next IN ('shortest_arc','clockwise_arc','counterclockwise_arc')),
  PRIMARY KEY (profile_id,profile_version,ordinal), UNIQUE(profile_id,profile_version,progress_ppm),
  FOREIGN KEY (profile_id,profile_version) REFERENCES world_base.spatial_v3_movement_orientation_profiles(id,version) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS world_base.spatial_v3_relative_orientations (
  entity_kind TEXT NOT NULL DEFAULT 'spatial_relative_orientation' CHECK (entity_kind = 'spatial_relative_orientation'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version > 0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT,
  source_entity_kind TEXT NOT NULL, source_entity_id TEXT NOT NULL, source_entity_version INTEGER NOT NULL, target_entity_kind TEXT NOT NULL, target_entity_id TEXT NOT NULL, target_entity_version INTEGER NOT NULL,
  reference_frame_id TEXT NOT NULL, reference_frame_version INTEGER NOT NULL,
  relation_kind TEXT NOT NULL CHECK (relation_kind IN ('north_of','northeast_of','east_of','southeast_of','south_of','southwest_of','west_of','northwest_of','overlaps','crosses','upstream_of','downstream_of')),
  bearing_center_mdeg INTEGER CHECK(bearing_center_mdeg BETWEEN 0 AND 359999), bearing_half_width_mdeg INTEGER CHECK(bearing_half_width_mdeg BETWEEN 0 AND 180000), distance_band_id TEXT,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'),
  PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id),
  FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(reference_frame_id,reference_frame_version,world_revision_id) REFERENCES world_base.spatial_v3_orientation_reference_frames(id,version,world_revision_id) ON DELETE RESTRICT,
  CHECK((bearing_center_mdeg IS NULL) = (bearing_half_width_mdeg IS NULL)), CHECK(source_entity_id <> target_entity_id)
);

CREATE TABLE IF NOT EXISTS world_base.spatial_v3_g4_directional_exits (
  entity_kind TEXT NOT NULL DEFAULT 'g4_directional_exit' CHECK(entity_kind='g4_directional_exit'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT,
  g4_id TEXT NOT NULL, g4_version INTEGER NOT NULL, direction_context_id TEXT NOT NULL, exit_orientation_profile_id TEXT, exit_orientation_profile_version INTEGER, exit_orientation_rule_id TEXT, exit_orientation_rule_version INTEGER,
  exit_kind TEXT NOT NULL CHECK(exit_kind IN ('world_route_exit','physical_boundary')), exit_canonical_g5_id TEXT, exit_canonical_g5_version INTEGER, boundary_feature_entity_kind TEXT, boundary_feature_entity_id TEXT, boundary_feature_version INTEGER,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'),
  PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(exit_orientation_profile_id,exit_orientation_profile_version,world_revision_id) REFERENCES world_base.spatial_v3_movement_orientation_profiles(id,version,world_revision_id) ON DELETE RESTRICT,
  CHECK((exit_kind='world_route_exit') = (exit_canonical_g5_id IS NOT NULL AND exit_canonical_g5_version IS NOT NULL)),
  CHECK((exit_kind='physical_boundary') = (boundary_feature_entity_id IS NOT NULL AND boundary_feature_version IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS world_base.spatial_v3_world_routes (
  entity_kind TEXT NOT NULL DEFAULT 'world_route' CHECK(entity_kind='world_route'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT,
  route_kind_id TEXT NOT NULL, reverse_route_id TEXT, reverse_route_version INTEGER, availability_condition_set_id TEXT, availability_condition_set_version INTEGER, risk_profile_id TEXT, risk_profile_version INTEGER,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'),
  PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(reverse_route_id,reverse_route_version) REFERENCES world_base.spatial_v3_world_routes(id,version) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED, CHECK((reverse_route_id IS NULL) = (reverse_route_version IS NULL)), CHECK(reverse_route_id IS NULL OR reverse_route_id <> id)
);
CREATE OR REPLACE FUNCTION world_base.validate_spatial_v3_directional_exit() RETURNS TRIGGER AS $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM world_base.spatial_v3_nodes g4 JOIN world_base.spatial_v3_nodes g5 ON g5.id=NEW.exit_canonical_g5_id AND g5.version=NEW.exit_canonical_g5_version AND g5.world_revision_id=NEW.world_revision_id JOIN world_base.spatial_v3_node_parents parent ON parent.child_id=g5.id AND parent.child_version=g5.version AND parent.parent_id=g4.id AND parent.parent_version=g4.version AND parent.world_revision_id=NEW.world_revision_id WHERE g4.id=NEW.g4_id AND g4.version=NEW.g4_version AND g4.world_revision_id=NEW.world_revision_id AND g4.spatial_level='G4' AND g5.spatial_level='G5') AND NEW.exit_kind='world_route_exit' THEN RAISE EXCEPTION 'route_endpoint_invalid: exit canonical G5 must have declared G4 direct parent'; END IF; RETURN NEW;
END; $$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS world_base.spatial_v3_world_route_points (
  entity_kind TEXT NOT NULL DEFAULT 'world_route_point' CHECK(entity_kind='world_route_point'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT,
  world_route_id TEXT NOT NULL, world_route_version INTEGER NOT NULL, ordinal INTEGER NOT NULL CHECK(ordinal>=0), point_kind TEXT NOT NULL CHECK(point_kind IN ('endpoint_from','waypoint','checkpoint','boundary','endpoint_to')),
  anchor_policy TEXT NOT NULL CHECK(anchor_policy IN ('endpoint_binding','ordinary_transit','shared_checkpoint')), stable_label_id TEXT, context_switch_phase TEXT CHECK(context_switch_phase IN ('inbound_completion','outbound_dispatch')),
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'),
  PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), UNIQUE(world_route_id,world_route_version,ordinal), FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(world_route_id,world_route_version,world_revision_id) REFERENCES world_base.spatial_v3_world_routes(id,version,world_revision_id) ON DELETE RESTRICT,
  CHECK((point_kind IN ('endpoint_from','endpoint_to')) = (anchor_policy='endpoint_binding')),
  CHECK((point_kind NOT IN ('endpoint_from','endpoint_to')) OR context_switch_phase IS NULL)
);

CREATE TABLE IF NOT EXISTS world_base.spatial_v3_transition_environment_profiles (
  entity_kind TEXT NOT NULL DEFAULT 'transition_environment_profile' CHECK(entity_kind='transition_environment_profile'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT,
  environment_class_id TEXT, permanent_cost_basis_id TEXT, dynamic_environment_rule_set_id TEXT, dynamic_environment_rule_set_version INTEGER,
  definition TEXT,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'),
  PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_movement_method_cost_profiles (
  entity_kind TEXT NOT NULL DEFAULT 'movement_method_cost_profile' CHECK(entity_kind='movement_method_cost_profile'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT, baseline_movement_method_id TEXT NOT NULL,
  base_minutes INTEGER CHECK(base_minutes > 0), dynamic_modifiers_required BOOLEAN, calibration_kind TEXT, distance_derived BOOLEAN, measured_historical_duration BOOLEAN, definition TEXT,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'), PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_movement_method_cost_options (
  profile_id TEXT NOT NULL, profile_version INTEGER NOT NULL, movement_method_id TEXT NOT NULL, cost_mode TEXT NOT NULL CHECK(cost_mode IN ('baseline','rational_factor')), factor_numerator INTEGER, factor_denominator INTEGER,
  PRIMARY KEY(profile_id,profile_version,movement_method_id), FOREIGN KEY(profile_id,profile_version) REFERENCES world_base.spatial_v3_movement_method_cost_profiles(id,version) ON DELETE CASCADE,
  CHECK((cost_mode='baseline' AND factor_numerator IS NULL AND factor_denominator IS NULL) OR (cost_mode='rational_factor' AND factor_numerator>0 AND factor_denominator>0))
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_dynamic_recheck_policies (
  entity_kind TEXT NOT NULL DEFAULT 'dynamic_recheck_policy' CHECK(entity_kind='dynamic_recheck_policy'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT, policy_kind TEXT NOT NULL CHECK(policy_kind IN ('segment_once','fixed_progress_slices','explicit_progress_points','fixed_time_interval')), progress_slice_ppm INTEGER CHECK(progress_slice_ppm BETWEEN 1 AND 1000000), interval_minutes INTEGER CHECK(interval_minutes > 0), event_triggers JSONB, definition TEXT,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'), PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED,
  CHECK((policy_kind='fixed_progress_slices') = (progress_slice_ppm IS NOT NULL)),
  CHECK((policy_kind='fixed_time_interval') = (interval_minutes IS NOT NULL))
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_dynamic_recheck_policy_points (
  policy_id TEXT NOT NULL, policy_version INTEGER NOT NULL, ordinal INTEGER NOT NULL CHECK(ordinal>=0), progress_ppm INTEGER NOT NULL CHECK(progress_ppm BETWEEN 1 AND 999999), PRIMARY KEY(policy_id,policy_version,ordinal), UNIQUE(policy_id,policy_version,progress_ppm), FOREIGN KEY(policy_id,policy_version) REFERENCES world_base.spatial_v3_dynamic_recheck_policies(id,version) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS world_base.spatial_v3_world_route_segments (
  entity_kind TEXT NOT NULL DEFAULT 'world_route_segment' CHECK(entity_kind='world_route_segment'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT,
  world_route_id TEXT NOT NULL, world_route_version INTEGER NOT NULL, ordinal INTEGER NOT NULL CHECK(ordinal>=0), from_point_id TEXT NOT NULL, from_point_version INTEGER NOT NULL, to_point_id TEXT NOT NULL, to_point_version INTEGER NOT NULL,
  transition_environment_profile_id TEXT NOT NULL, transition_environment_profile_version INTEGER NOT NULL, movement_orientation_profile_id TEXT, movement_orientation_profile_version INTEGER, topological_orientation_profile_id TEXT, topological_orientation_profile_version INTEGER, baseline_movement_method_id TEXT NOT NULL, movement_method_cost_profile_id TEXT NOT NULL, movement_method_cost_profile_version INTEGER NOT NULL, base_minutes INTEGER NOT NULL CHECK (base_minutes > 0), dynamic_recheck_policy_id TEXT NOT NULL, dynamic_recheck_policy_version INTEGER NOT NULL, capacity INTEGER CHECK(capacity>0), risk_profile_id TEXT, risk_profile_version INTEGER, availability_condition_set_id TEXT, availability_condition_set_version INTEGER,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'),
  PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), UNIQUE(world_route_id,world_route_version,ordinal), FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(world_route_id,world_route_version,world_revision_id) REFERENCES world_base.spatial_v3_world_routes(id,version,world_revision_id) ON DELETE RESTRICT,
  FOREIGN KEY(from_point_id,from_point_version,world_revision_id) REFERENCES world_base.spatial_v3_world_route_points(id,version,world_revision_id) ON DELETE RESTRICT, FOREIGN KEY(to_point_id,to_point_version,world_revision_id) REFERENCES world_base.spatial_v3_world_route_points(id,version,world_revision_id) ON DELETE RESTRICT,
  FOREIGN KEY(transition_environment_profile_id,transition_environment_profile_version,world_revision_id) REFERENCES world_base.spatial_v3_transition_environment_profiles(id,version,world_revision_id) ON DELETE RESTRICT, FOREIGN KEY(movement_orientation_profile_id,movement_orientation_profile_version,world_revision_id) REFERENCES world_base.spatial_v3_movement_orientation_profiles(id,version,world_revision_id) ON DELETE RESTRICT, FOREIGN KEY(movement_method_cost_profile_id,movement_method_cost_profile_version,world_revision_id) REFERENCES world_base.spatial_v3_movement_method_cost_profiles(id,version,world_revision_id) ON DELETE RESTRICT, FOREIGN KEY(dynamic_recheck_policy_id,dynamic_recheck_policy_version,world_revision_id) REFERENCES world_base.spatial_v3_dynamic_recheck_policies(id,version,world_revision_id) ON DELETE RESTRICT,
  CHECK(from_point_id <> to_point_id)
);

CREATE TABLE IF NOT EXISTS world_base.spatial_v3_world_route_segment_spatial_contexts (
  segment_id TEXT NOT NULL, segment_version INTEGER NOT NULL, g0_id TEXT NOT NULL, g0_version INTEGER NOT NULL, g1_id TEXT NOT NULL, g1_version INTEGER NOT NULL, g2_id TEXT, g2_version INTEGER, g3_id TEXT, g3_version INTEGER, g4_corridor_id TEXT, g4_corridor_version INTEGER, jurisdiction_profile_id TEXT, jurisdiction_profile_version INTEGER, weather_scope_id TEXT NOT NULL, event_pool_profile_id TEXT, event_pool_profile_version INTEGER,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'), PRIMARY KEY(segment_id,segment_version), FOREIGN KEY(segment_id,segment_version) REFERENCES world_base.spatial_v3_world_route_segments(id,version) ON DELETE CASCADE,
  CHECK((g2_id IS NULL)=(g2_version IS NULL)), CHECK((g3_id IS NULL)=(g3_version IS NULL)), CHECK((g4_corridor_id IS NULL)=(g4_corridor_version IS NULL)), CHECK((jurisdiction_profile_id IS NULL)=(jurisdiction_profile_version IS NULL))
);

CREATE TABLE IF NOT EXISTS world_base.spatial_v3_spatial_transition_contracts (
  entity_kind TEXT NOT NULL DEFAULT 'spatial_transition_contract' CHECK(entity_kind='spatial_transition_contract'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT,
  transition_kind TEXT NOT NULL CHECK(transition_kind IN ('g1_adjacency','g0_external','jurisdiction_only','combined')), from_g0_id TEXT NOT NULL, from_g0_version INTEGER NOT NULL, from_g1_id TEXT NOT NULL, from_g1_version INTEGER NOT NULL, to_g0_id TEXT NOT NULL, to_g0_version INTEGER NOT NULL, to_g1_id TEXT NOT NULL, to_g1_version INTEGER NOT NULL, grid_delta_x INTEGER, grid_delta_y INTEGER, legal_customs_profile_id TEXT, legal_customs_profile_version INTEGER,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'),
  PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED,
  CHECK((transition_kind IN ('g1_adjacency','combined')) OR (grid_delta_x IS NULL AND grid_delta_y IS NULL)), CHECK((transition_kind IN ('jurisdiction_only','combined')) = (legal_customs_profile_id IS NOT NULL AND legal_customs_profile_version IS NOT NULL)), CHECK((grid_delta_x IS NULL)=(grid_delta_y IS NULL))
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_spatial_transition_allowed_route_kinds (
  transition_contract_id TEXT NOT NULL, transition_contract_version INTEGER NOT NULL, route_kind_id TEXT NOT NULL,
  PRIMARY KEY(transition_contract_id,transition_contract_version,route_kind_id),
  FOREIGN KEY(transition_contract_id,transition_contract_version) REFERENCES world_base.spatial_v3_spatial_transition_contracts(id,version) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_boundary_crossing_contracts (
  entity_kind TEXT NOT NULL DEFAULT 'boundary_crossing_contract' CHECK(entity_kind='boundary_crossing_contract'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT,
  boundary_kind TEXT NOT NULL CHECK(boundary_kind IN ('g1_internal','g0_external','jurisdiction_only','combined')), route_id TEXT NOT NULL, route_version INTEGER NOT NULL, route_point_id TEXT NOT NULL, route_point_version INTEGER NOT NULL, inbound_segment_id TEXT NOT NULL, inbound_segment_version INTEGER NOT NULL, outbound_segment_id TEXT NOT NULL, outbound_segment_version INTEGER NOT NULL, from_context_digest TEXT NOT NULL CHECK(from_context_digest ~ '^[a-f0-9]{64}$'), to_context_digest TEXT NOT NULL CHECK(to_context_digest ~ '^[a-f0-9]{64}$'), transition_contract_id TEXT NOT NULL, transition_contract_version INTEGER NOT NULL, switch_phase TEXT NOT NULL CHECK(switch_phase IN ('inbound_completion','outbound_dispatch')), directionality TEXT NOT NULL DEFAULT 'directed' CHECK (directionality = 'directed'),
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'), PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), UNIQUE(route_id,route_version,route_point_id,route_point_version), FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(route_id,route_version,world_revision_id) REFERENCES world_base.spatial_v3_world_routes(id,version,world_revision_id) ON DELETE RESTRICT, FOREIGN KEY(route_point_id,route_point_version,world_revision_id) REFERENCES world_base.spatial_v3_world_route_points(id,version,world_revision_id) ON DELETE RESTRICT, FOREIGN KEY(inbound_segment_id,inbound_segment_version,world_revision_id) REFERENCES world_base.spatial_v3_world_route_segments(id,version,world_revision_id) ON DELETE RESTRICT, FOREIGN KEY(outbound_segment_id,outbound_segment_version,world_revision_id) REFERENCES world_base.spatial_v3_world_route_segments(id,version,world_revision_id) ON DELETE RESTRICT, FOREIGN KEY(transition_contract_id,transition_contract_version,world_revision_id) REFERENCES world_base.spatial_v3_spatial_transition_contracts(id,version,world_revision_id) ON DELETE RESTRICT,
  CHECK(inbound_segment_id <> outbound_segment_id)
);

CREATE TABLE IF NOT EXISTS world_base.spatial_v3_world_route_endpoint_bindings (
  entity_kind TEXT NOT NULL DEFAULT 'world_route_endpoint_binding' CHECK(entity_kind='world_route_endpoint_binding'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT,
  world_route_id TEXT NOT NULL, world_route_version INTEGER NOT NULL, endpoint_role TEXT NOT NULL CHECK(endpoint_role IN ('from','to')), route_point_id TEXT NOT NULL, route_point_version INTEGER NOT NULL, canonical_g5_id TEXT NOT NULL, canonical_g5_version INTEGER NOT NULL, directional_exit_id TEXT, directional_exit_version INTEGER, scene_endpoint_slot_key TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'), PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), UNIQUE(world_route_id,world_route_version,endpoint_role), FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED,
  FOREIGN KEY(world_route_id,world_route_version,world_revision_id) REFERENCES world_base.spatial_v3_world_routes(id,version,world_revision_id) ON DELETE RESTRICT, FOREIGN KEY(route_point_id,route_point_version,world_revision_id) REFERENCES world_base.spatial_v3_world_route_points(id,version,world_revision_id) ON DELETE RESTRICT, FOREIGN KEY(directional_exit_id,directional_exit_version,world_revision_id) REFERENCES world_base.spatial_v3_g4_directional_exits(id,version,world_revision_id) ON DELETE RESTRICT,
  CHECK((endpoint_role='from') = (directional_exit_id IS NOT NULL AND directional_exit_version IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS world_base.spatial_v3_activity_contracts (
  entity_kind TEXT NOT NULL DEFAULT 'activity_contract' CHECK(entity_kind='activity_contract'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT, activity_kind_id TEXT NOT NULL, cost_kind TEXT NOT NULL CHECK(cost_kind='time'), interruption_policy_id TEXT NOT NULL, interruption_policy_version INTEGER NOT NULL, failure_time_retention_policy TEXT NOT NULL CHECK(failure_time_retention_policy='retain_committed_elapsed'), failure_execution_transition TEXT NOT NULL CHECK(failure_execution_transition IN ('waiting_at_anchor','aborted')),
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'), PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_action_contracts (
  entity_kind TEXT NOT NULL DEFAULT 'action_contract' CHECK(entity_kind='action_contract'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT, action_kind_id TEXT NOT NULL, cost_kind TEXT NOT NULL CHECK(cost_kind='action'), failure_location_policy TEXT NOT NULL CHECK(failure_location_policy='preserve_departure'), failure_execution_transition TEXT NOT NULL CHECK(failure_execution_transition IN ('waiting_at_anchor','aborted')),
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'), PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_movement_mode_transition_contracts (
  entity_kind TEXT NOT NULL DEFAULT 'movement_mode_transition_contract' CHECK(entity_kind='movement_mode_transition_contract'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT, transition_kind TEXT NOT NULL CHECK(transition_kind IN ('board','disembark','load','unload','transfer_control','change_cohort_formation')), cost_kind TEXT NOT NULL CHECK(cost_kind IN ('action','time')), source_carrier_kind TEXT CHECK(source_carrier_kind IN ('actor','cohort','transport')), target_carrier_kind TEXT CHECK(target_carrier_kind IN ('actor','cohort','transport')),
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'), PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED,
  CHECK((transition_kind='board' AND source_carrier_kind IN ('actor','cohort') AND target_carrier_kind='transport') OR (transition_kind='disembark' AND source_carrier_kind='transport' AND target_carrier_kind IN ('actor','cohort')) OR (transition_kind IN ('load','unload') AND source_carrier_kind IS NULL AND target_carrier_kind IS NULL) OR (transition_kind='transfer_control' AND source_carrier_kind='transport' AND target_carrier_kind='transport') OR (transition_kind='change_cohort_formation' AND source_carrier_kind='cohort' AND target_carrier_kind='cohort'))
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_recovery_transition_templates (
  entity_kind TEXT NOT NULL DEFAULT 'recovery_transition_template' CHECK(entity_kind='recovery_transition_template'), id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT, source_selector_kind TEXT NOT NULL CHECK(source_selector_kind IN ('interruption_anchor','checkpoint_anchor','transit_anchor_role','stranded_snapshot')), target_selector_kind TEXT NOT NULL CHECK(target_selector_kind IN ('source_endpoint','previous_checkpoint','canonical_safe_exit','specific_authoring_endpoint')), target_selector_value TEXT, required_cost_contract_id TEXT, required_cost_contract_version INTEGER,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'), PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), FOREIGN KEY(entity_kind,id,version,world_revision_id) REFERENCES world_base.spatial_v3_authoring_versions(entity_kind,entity_id,version,world_revision_id) DEFERRABLE INITIALLY DEFERRED, CHECK((target_selector_kind='source_endpoint') = (target_selector_value IS NULL)), CHECK((required_cost_contract_id IS NULL)=(required_cost_contract_version IS NULL))
);

-- Deferred aggregate validation. Error-code names are intentional: orientation_frame_cycle,
-- orientation_profile_invalid, route_chain_discontinuous, route_cycle_or_branch and
-- boundary_crossing_contract_gap map to the frozen Appendix C registry.
CREATE OR REPLACE FUNCTION world_base.validate_spatial_v3_orientation_frame() RETURNS TRIGGER AS $$
DECLARE current_id TEXT := NEW.id; current_version INTEGER := NEW.version; next_id TEXT; next_version INTEGER; parent_revision TEXT; hops INTEGER := 0;
BEGIN
  IF NEW.parent_frame_id IS NULL AND (NEW.scope_entity_kind <> 'world_revision' OR NEW.scope_entity_id <> NEW.world_revision_id OR NEW.north_offset_mdeg <> 0) THEN RAISE EXCEPTION 'orientation_profile_invalid: root frame must scope its revision and have zero offset'; END IF;
  IF NEW.parent_frame_id IS NOT NULL THEN SELECT world_revision_id INTO parent_revision FROM world_base.spatial_v3_orientation_reference_frames WHERE id=NEW.parent_frame_id AND version=NEW.parent_frame_version; IF parent_revision IS DISTINCT FROM NEW.world_revision_id THEN RAISE EXCEPTION 'orientation_frame_cycle: parent crosses world revision'; END IF; END IF;
  LOOP
    SELECT parent_frame_id,parent_frame_version INTO next_id,next_version FROM world_base.spatial_v3_orientation_reference_frames WHERE id=current_id AND version=current_version;
    EXIT WHEN next_id IS NULL; hops := hops+1; IF hops>256 OR (next_id=NEW.id AND next_version=NEW.version) THEN RAISE EXCEPTION 'orientation_frame_cycle'; END IF; current_id:=next_id; current_version:=next_version;
  END LOOP; IF NEW.status='approved' AND (SELECT count(*) FROM world_base.spatial_v3_orientation_reference_frames WHERE world_revision_id=NEW.world_revision_id AND parent_frame_id IS NULL AND status='approved')<>1 THEN RAISE EXCEPTION 'orientation_profile_invalid: exact one approved root frame required'; END IF; RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION world_base.validate_spatial_v3_orientation_profile() RETURNS TRIGGER AS $$
DECLARE points INTEGER; first_progress INTEGER; last_progress INTEGER; invalid_points BOOLEAN;
BEGIN
 SELECT count(*),min(progress_ppm),max(progress_ppm),bool_or(ordinal<>progress_rank OR (ordinal=0 AND progress_ppm<>0) OR (ordinal=points_count-1 AND interpolation_to_next IS NOT NULL) OR (ordinal<points_count-1 AND interpolation_to_next IS NULL)) INTO points,first_progress,last_progress,invalid_points FROM (SELECT *, row_number() OVER (ORDER BY ordinal)-1 AS progress_rank, count(*) OVER () AS points_count FROM world_base.spatial_v3_movement_orientation_profile_points WHERE profile_id=NEW.id AND profile_version=NEW.version) point_rows;
 IF NEW.profile_kind='curved' AND (points<2 OR first_progress<>0 OR last_progress<>1000000 OR invalid_points) THEN RAISE EXCEPTION 'orientation_profile_invalid'; END IF;
 IF NEW.reverse_profile_id IS NOT NULL AND (NOT EXISTS (SELECT 1 FROM world_base.spatial_v3_movement_orientation_profiles p WHERE p.id=NEW.reverse_profile_id AND p.version=NEW.reverse_profile_version AND p.reverse_profile_id=NEW.id AND p.reverse_profile_version=NEW.version AND p.reference_frame_id=NEW.reference_frame_id AND p.reference_frame_version=NEW.reference_frame_version AND ((NEW.vertical_direction='up' AND p.vertical_direction='down') OR (NEW.vertical_direction='down' AND p.vertical_direction='up') OR (NEW.vertical_direction IN ('level','mixed') AND p.vertical_direction=NEW.vertical_direction))) OR EXISTS(SELECT 1 FROM world_base.spatial_v3_movement_orientation_profile_points f LEFT JOIN world_base.spatial_v3_movement_orientation_profile_points r ON r.profile_id=NEW.reverse_profile_id AND r.profile_version=NEW.reverse_profile_version AND r.progress_ppm=1000000-f.progress_ppm WHERE f.profile_id=NEW.id AND f.profile_version=NEW.version AND (r.profile_id IS NULL OR r.local_azimuth_mdeg<>((f.local_azimuth_mdeg+180000)%360000))) ) THEN RAISE EXCEPTION 'orientation_profile_invalid'; END IF; RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION world_base.validate_spatial_v3_orientation_profile_points() RETURNS TRIGGER AS $$
DECLARE profile_row world_base.spatial_v3_movement_orientation_profiles%ROWTYPE; points INTEGER; first_progress INTEGER; last_progress INTEGER; invalid_points BOOLEAN;
BEGIN
 SELECT * INTO profile_row FROM world_base.spatial_v3_movement_orientation_profiles WHERE id=COALESCE(NEW.profile_id,OLD.profile_id) AND version=COALESCE(NEW.profile_version,OLD.profile_version);
 IF NOT FOUND THEN RETURN NULL; END IF;
 SELECT count(*),min(progress_ppm),max(progress_ppm),bool_or(ordinal<>progress_rank OR (ordinal=0 AND progress_ppm<>0) OR (ordinal=points_count-1 AND interpolation_to_next IS NOT NULL) OR (ordinal<points_count-1 AND interpolation_to_next IS NULL)) INTO points,first_progress,last_progress,invalid_points FROM (SELECT *, row_number() OVER (ORDER BY ordinal)-1 AS progress_rank, count(*) OVER () AS points_count FROM world_base.spatial_v3_movement_orientation_profile_points WHERE profile_id=profile_row.id AND profile_version=profile_row.version) point_rows;
 IF (profile_row.profile_kind='fixed' AND points<>0) OR (profile_row.profile_kind='curved' AND (points<2 OR first_progress<>0 OR last_progress<>1000000 OR invalid_points)) THEN RAISE EXCEPTION 'orientation_profile_invalid'; END IF;
 IF profile_row.reverse_profile_id IS NOT NULL AND EXISTS(SELECT 1 FROM world_base.spatial_v3_movement_orientation_profile_points f LEFT JOIN world_base.spatial_v3_movement_orientation_profile_points r ON r.profile_id=profile_row.reverse_profile_id AND r.profile_version=profile_row.reverse_profile_version AND r.progress_ppm=1000000-f.progress_ppm WHERE f.profile_id=profile_row.id AND f.profile_version=profile_row.version AND (r.profile_id IS NULL OR r.local_azimuth_mdeg<>((f.local_azimuth_mdeg+180000)%360000))) THEN RAISE EXCEPTION 'orientation_profile_invalid'; END IF; RETURN NULL;
END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION world_base.validate_spatial_v3_route() RETURNS TRIGGER AS $$
DECLARE pcount INTEGER; scount INTEGER; bad BOOLEAN;
BEGIN
 SELECT count(*) INTO pcount FROM world_base.spatial_v3_world_route_points WHERE world_route_id=NEW.id AND world_route_version=NEW.version;
 SELECT count(*) INTO scount FROM world_base.spatial_v3_world_route_segments WHERE world_route_id=NEW.id AND world_route_version=NEW.version;
 IF NEW.status='approved' AND (pcount<2 OR pcount<>scount+1 OR (SELECT count(*) FROM world_base.spatial_v3_world_route_endpoint_bindings WHERE world_route_id=NEW.id AND world_route_version=NEW.version AND endpoint_role='from')<>1 OR (SELECT count(*) FROM world_base.spatial_v3_world_route_endpoint_bindings WHERE world_route_id=NEW.id AND world_route_version=NEW.version AND endpoint_role='to')<>1 OR EXISTS(SELECT 1 FROM world_base.spatial_v3_world_route_segments s LEFT JOIN world_base.spatial_v3_world_route_segment_spatial_contexts c ON c.segment_id=s.id AND c.segment_version=s.version WHERE s.world_route_id=NEW.id AND s.world_route_version=NEW.version GROUP BY s.id,s.version HAVING count(c.segment_id)<>1)) THEN RAISE EXCEPTION 'route_chain_discontinuous'; END IF;
 SELECT EXISTS(SELECT 1 FROM world_base.spatial_v3_world_route_segments s JOIN world_base.spatial_v3_world_route_points fp ON fp.id=s.from_point_id AND fp.version=s.from_point_version JOIN world_base.spatial_v3_world_route_points tp ON tp.id=s.to_point_id AND tp.version=s.to_point_version WHERE s.world_route_id=NEW.id AND s.world_route_version=NEW.version AND (fp.world_route_id<>NEW.id OR tp.world_route_id<>NEW.id OR fp.ordinal<>s.ordinal OR tp.ordinal<>s.ordinal+1)) INTO bad;
 IF bad THEN RAISE EXCEPTION 'route_cycle_or_branch'; END IF; RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION world_base.assert_spatial_v3_route(p_route_id TEXT, p_route_version INTEGER) RETURNS VOID AS $$
DECLARE route_row world_base.spatial_v3_world_routes%ROWTYPE; pcount INTEGER; scount INTEGER; bad BOOLEAN;
BEGIN
 SELECT * INTO route_row FROM world_base.spatial_v3_world_routes WHERE id=p_route_id AND version=p_route_version; IF NOT FOUND OR route_row.status<>'approved' THEN RETURN; END IF;
 SELECT count(*) INTO pcount FROM world_base.spatial_v3_world_route_points WHERE world_route_id=p_route_id AND world_route_version=p_route_version; SELECT count(*) INTO scount FROM world_base.spatial_v3_world_route_segments WHERE world_route_id=p_route_id AND world_route_version=p_route_version;
 SELECT EXISTS(SELECT 1 FROM world_base.spatial_v3_world_route_points p WHERE p.world_route_id=p_route_id AND p.world_route_version=p_route_version AND ((p.ordinal=0 AND p.point_kind<>'endpoint_from') OR (p.ordinal=pcount-1 AND p.point_kind<>'endpoint_to') OR (p.ordinal>0 AND p.ordinal<pcount-1 AND (p.point_kind IN ('endpoint_from','endpoint_to') OR (p.point_kind='waypoint' AND (p.anchor_policy<>'ordinary_transit' OR p.context_switch_phase IS NULL)) OR (p.point_kind='checkpoint' AND (p.anchor_policy<>'shared_checkpoint' OR p.context_switch_phase IS NULL)) OR (p.point_kind='boundary' AND p.context_switch_phase IS NULL))))) INTO bad;
 IF pcount<2 OR pcount<>scount+1 OR bad OR (SELECT count(*) FROM world_base.spatial_v3_world_route_endpoint_bindings WHERE world_route_id=p_route_id AND world_route_version=p_route_version AND endpoint_role='from')<>1 OR (SELECT count(*) FROM world_base.spatial_v3_world_route_endpoint_bindings WHERE world_route_id=p_route_id AND world_route_version=p_route_version AND endpoint_role='to')<>1 THEN RAISE EXCEPTION 'route_chain_discontinuous'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_world_route_endpoint_bindings b JOIN world_base.spatial_v3_world_route_points p ON p.id=b.route_point_id AND p.version=b.route_point_version LEFT JOIN world_base.spatial_v3_g4_directional_exits e ON e.id=b.directional_exit_id AND e.version=b.directional_exit_version WHERE b.world_route_id=p_route_id AND b.world_route_version=p_route_version AND ((b.endpoint_role='from' AND (p.point_kind<>'endpoint_from' OR e.id IS NULL OR e.exit_kind<>'world_route_exit' OR e.exit_canonical_g5_id<>b.canonical_g5_id OR e.exit_canonical_g5_version<>b.canonical_g5_version)) OR (b.endpoint_role='to' AND (p.point_kind<>'endpoint_to' OR b.directional_exit_id IS NOT NULL)))) THEN RAISE EXCEPTION 'route_endpoint_invalid'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_world_route_segments s JOIN world_base.spatial_v3_world_route_points f ON f.id=s.from_point_id AND f.version=s.from_point_version JOIN world_base.spatial_v3_world_route_points t ON t.id=s.to_point_id AND t.version=s.to_point_version LEFT JOIN world_base.spatial_v3_world_route_segment_spatial_contexts c ON c.segment_id=s.id AND c.segment_version=s.version WHERE s.world_route_id=p_route_id AND s.world_route_version=p_route_version GROUP BY s.id,s.version,f.world_route_id,f.world_route_version,f.ordinal,t.world_route_id,t.world_route_version,t.ordinal HAVING f.world_route_id<>p_route_id OR f.world_route_version<>p_route_version OR t.world_route_id<>p_route_id OR t.world_route_version<>p_route_version OR f.ordinal<>s.ordinal OR t.ordinal<>s.ordinal+1 OR count(c.segment_id)<>1) THEN RAISE EXCEPTION 'route_cycle_or_branch'; END IF;
 IF route_row.reverse_route_id IS NOT NULL AND (NOT EXISTS(SELECT 1 FROM world_base.spatial_v3_world_routes r WHERE r.id=route_row.reverse_route_id AND r.version=route_row.reverse_route_version AND r.reverse_route_id=route_row.id AND r.reverse_route_version=route_row.version AND r.world_revision_id=route_row.world_revision_id) OR EXISTS(SELECT 1 FROM world_base.spatial_v3_world_route_points p LEFT JOIN world_base.spatial_v3_world_route_points rp ON rp.world_route_id=route_row.reverse_route_id AND rp.world_route_version=route_row.reverse_route_version AND rp.ordinal=pcount-1-p.ordinal WHERE p.world_route_id=route_row.id AND p.world_route_version=route_row.version AND (rp.id IS NULL OR rp.point_kind<>CASE p.point_kind WHEN 'endpoint_from' THEN 'endpoint_to' WHEN 'endpoint_to' THEN 'endpoint_from' ELSE p.point_kind END)) OR EXISTS(SELECT 1 FROM world_base.spatial_v3_world_route_segments s JOIN world_base.spatial_v3_movement_orientation_profiles op ON op.id=s.movement_orientation_profile_id AND op.version=s.movement_orientation_profile_version LEFT JOIN world_base.spatial_v3_world_route_segments rs ON rs.world_route_id=route_row.reverse_route_id AND rs.world_route_version=route_row.reverse_route_version AND rs.ordinal=scount-1-s.ordinal WHERE s.world_route_id=route_row.id AND s.world_route_version=route_row.version AND (rs.id IS NULL OR rs.movement_orientation_profile_id<>op.reverse_profile_id OR rs.movement_orientation_profile_version<>op.reverse_profile_version OR rs.transition_environment_profile_id<>s.transition_environment_profile_id))) THEN RAISE EXCEPTION 'route_cycle_or_branch'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_boundary_crossing_contracts b JOIN world_base.spatial_v3_world_route_segments i ON i.id=b.inbound_segment_id AND i.version=b.inbound_segment_version JOIN world_base.spatial_v3_world_route_segments o ON o.id=b.outbound_segment_id AND o.version=b.outbound_segment_version JOIN world_base.spatial_v3_world_route_points p ON p.id=b.route_point_id AND p.version=b.route_point_version WHERE b.route_id=p_route_id AND b.route_version=p_route_version AND (i.world_route_id<>p_route_id OR o.world_route_id<>p_route_id OR i.ordinal+1<>o.ordinal OR i.to_point_id<>p.id OR o.from_point_id<>p.id OR p.point_kind<>'boundary' OR p.context_switch_phase<>b.switch_phase)) THEN RAISE EXCEPTION 'boundary_crossing_contract_gap'; END IF;
END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION world_base.queue_spatial_v3_route_validation() RETURNS TRIGGER AS $$
DECLARE route_id_value TEXT; route_version_value INTEGER; route_row world_base.spatial_v3_world_routes%ROWTYPE; pcount INTEGER; scount INTEGER; from_count INTEGER; to_count INTEGER; bad BOOLEAN;
BEGIN
 IF TG_TABLE_NAME='spatial_v3_world_route_points' THEN route_id_value:=COALESCE(NEW.world_route_id,OLD.world_route_id); route_version_value:=COALESCE(NEW.world_route_version,OLD.world_route_version);
 ELSIF TG_TABLE_NAME='spatial_v3_world_route_segments' THEN route_id_value:=COALESCE(NEW.world_route_id,OLD.world_route_id); route_version_value:=COALESCE(NEW.world_route_version,OLD.world_route_version);
 ELSIF TG_TABLE_NAME='spatial_v3_world_route_endpoint_bindings' THEN route_id_value:=COALESCE(NEW.world_route_id,OLD.world_route_id); route_version_value:=COALESCE(NEW.world_route_version,OLD.world_route_version);
 ELSE SELECT s.world_route_id,s.world_route_version INTO route_id_value,route_version_value FROM world_base.spatial_v3_world_route_segments s WHERE s.id=COALESCE(NEW.segment_id,OLD.segment_id) AND s.version=COALESCE(NEW.segment_version,OLD.segment_version); END IF;
 SELECT * INTO route_row FROM world_base.spatial_v3_world_routes WHERE id=route_id_value AND version=route_version_value;
 IF FOUND AND route_row.status='approved' THEN
   SELECT count(*) INTO pcount FROM world_base.spatial_v3_world_route_points WHERE world_route_id=route_row.id AND world_route_version=route_row.version;
   SELECT count(*) INTO scount FROM world_base.spatial_v3_world_route_segments WHERE world_route_id=route_row.id AND world_route_version=route_row.version;
   SELECT count(*) INTO from_count FROM world_base.spatial_v3_world_route_endpoint_bindings WHERE world_route_id=route_row.id AND world_route_version=route_row.version AND endpoint_role='from';
   SELECT count(*) INTO to_count FROM world_base.spatial_v3_world_route_endpoint_bindings WHERE world_route_id=route_row.id AND world_route_version=route_row.version AND endpoint_role='to';
   SELECT EXISTS(SELECT 1 FROM world_base.spatial_v3_world_route_segments s LEFT JOIN world_base.spatial_v3_world_route_segment_spatial_contexts c ON c.segment_id=s.id AND c.segment_version=s.version WHERE s.world_route_id=route_row.id AND s.world_route_version=route_row.version GROUP BY s.id,s.version HAVING count(c.segment_id)<>1) INTO bad;
   IF pcount<2 OR pcount<>scount+1 OR from_count<>1 OR to_count<>1 OR bad THEN RAISE EXCEPTION 'route_chain_discontinuous'; END IF;
 END IF;
 PERFORM world_base.assert_spatial_v3_route(route_id_value,route_version_value);
 RETURN NULL;
END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION world_base.validate_spatial_v3_boundary() RETURNS TRIGGER AS $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM world_base.spatial_v3_world_route_segments i JOIN world_base.spatial_v3_world_route_segments o ON o.id=NEW.outbound_segment_id AND o.version=NEW.outbound_segment_version JOIN world_base.spatial_v3_world_routes r ON r.id=NEW.route_id AND r.version=NEW.route_version JOIN world_base.spatial_v3_world_route_points p ON p.id=NEW.route_point_id AND p.version=NEW.route_point_version JOIN world_base.spatial_v3_world_route_segment_spatial_contexts ic ON ic.segment_id=i.id AND ic.segment_version=i.version JOIN world_base.spatial_v3_world_route_segment_spatial_contexts oc ON oc.segment_id=o.id AND oc.segment_version=o.version JOIN world_base.spatial_v3_spatial_transition_contracts t ON t.id=NEW.transition_contract_id AND t.version=NEW.transition_contract_version JOIN world_base.spatial_v3_spatial_transition_allowed_route_kinds allowed ON allowed.transition_contract_id=t.id AND allowed.transition_contract_version=t.version AND allowed.route_kind_id=r.route_kind_id WHERE i.id=NEW.inbound_segment_id AND i.version=NEW.inbound_segment_version AND i.world_route_id=NEW.route_id AND o.world_route_id=NEW.route_id AND i.ordinal+1=o.ordinal AND i.to_point_id=p.id AND o.from_point_id=p.id AND p.point_kind='boundary' AND p.context_switch_phase=NEW.switch_phase AND ic.canonical_digest=NEW.from_context_digest AND oc.canonical_digest=NEW.to_context_digest AND ((NEW.boundary_kind='g1_internal' AND t.transition_kind='g1_adjacency') OR (NEW.boundary_kind='g0_external' AND t.transition_kind='g0_external') OR (NEW.boundary_kind='jurisdiction_only' AND t.transition_kind='jurisdiction_only') OR (NEW.boundary_kind='combined' AND t.transition_kind='combined'))) THEN RAISE EXCEPTION 'boundary_crossing_contract_gap'; END IF; RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION world_base.validate_spatial_v3_transition_contract() RETURNS TRIGGER AS $$
DECLARE fx INTEGER; fy INTEGER; tx INTEGER; ty INTEGER;
BEGIN
 IF NOT EXISTS(SELECT 1 FROM world_base.spatial_v3_nodes WHERE id=NEW.from_g0_id AND version=NEW.from_g0_version AND world_revision_id=NEW.world_revision_id AND spatial_level='G0') OR NOT EXISTS(SELECT 1 FROM world_base.spatial_v3_nodes WHERE id=NEW.to_g0_id AND version=NEW.to_g0_version AND world_revision_id=NEW.world_revision_id AND spatial_level='G0') OR NOT EXISTS(SELECT 1 FROM world_base.spatial_v3_nodes WHERE id=NEW.from_g1_id AND version=NEW.from_g1_version AND world_revision_id=NEW.world_revision_id AND spatial_level='G1') OR NOT EXISTS(SELECT 1 FROM world_base.spatial_v3_nodes WHERE id=NEW.to_g1_id AND version=NEW.to_g1_version AND world_revision_id=NEW.world_revision_id AND spatial_level='G1') THEN RAISE EXCEPTION 'boundary_crossing_contract_gap: pinned G0/G1 node invalid'; END IF;
 SELECT grid_x,grid_y INTO fx,fy FROM world_base.spatial_v3_g1_grid_cells WHERE node_id=NEW.from_g1_id AND node_version=NEW.from_g1_version; SELECT grid_x,grid_y INTO tx,ty FROM world_base.spatial_v3_g1_grid_cells WHERE node_id=NEW.to_g1_id AND node_version=NEW.to_g1_version;
 IF NEW.transition_kind='g1_adjacency' AND NOT(NEW.from_g0_id=NEW.to_g0_id AND NEW.from_g1_id<>NEW.to_g1_id AND abs(tx-fx)+abs(ty-fy)=1 AND NEW.grid_delta_x=tx-fx AND NEW.grid_delta_y=ty-fy AND NEW.legal_customs_profile_id IS NULL) THEN RAISE EXCEPTION 'boundary_crossing_contract_gap: invalid cardinal G1 transition'; END IF;
 IF NEW.transition_kind='g0_external' AND NOT(NEW.from_g0_id<>NEW.to_g0_id AND NEW.from_g1_id<>NEW.to_g1_id AND NEW.grid_delta_x IS NULL AND NEW.legal_customs_profile_id IS NULL) THEN RAISE EXCEPTION 'boundary_crossing_contract_gap: invalid external transition'; END IF;
 IF NEW.transition_kind='jurisdiction_only' AND NOT(NEW.from_g0_id=NEW.to_g0_id AND NEW.from_g1_id=NEW.to_g1_id AND NEW.legal_customs_profile_id IS NOT NULL) THEN RAISE EXCEPTION 'boundary_crossing_contract_gap: invalid jurisdiction transition'; END IF;
 IF NEW.transition_kind='combined' AND NOT(NEW.legal_customs_profile_id IS NOT NULL AND ((NEW.from_g0_id=NEW.to_g0_id AND NEW.from_g1_id<>NEW.to_g1_id AND abs(tx-fx)+abs(ty-fy)=1 AND NEW.grid_delta_x=tx-fx AND NEW.grid_delta_y=ty-fy) OR (NEW.from_g0_id<>NEW.to_g0_id AND NEW.from_g1_id<>NEW.to_g1_id AND NEW.grid_delta_x IS NULL))) THEN RAISE EXCEPTION 'boundary_crossing_contract_gap: invalid combined transition'; END IF;
 IF NOT EXISTS(SELECT 1 FROM world_base.spatial_v3_node_parents p WHERE p.child_id=NEW.from_g1_id AND p.child_version=NEW.from_g1_version AND p.parent_id=NEW.from_g0_id AND p.parent_version=NEW.from_g0_version AND p.world_revision_id=NEW.world_revision_id) OR NOT EXISTS(SELECT 1 FROM world_base.spatial_v3_node_parents p WHERE p.child_id=NEW.to_g1_id AND p.child_version=NEW.to_g1_version AND p.parent_id=NEW.to_g0_id AND p.parent_version=NEW.to_g0_version AND p.world_revision_id=NEW.world_revision_id) THEN RAISE EXCEPTION 'boundary_crossing_contract_gap: G1 parent mismatch'; END IF;
 IF NEW.status='approved' AND NOT EXISTS(SELECT 1 FROM world_base.spatial_v3_spatial_transition_allowed_route_kinds WHERE transition_contract_id=NEW.id AND transition_contract_version=NEW.version) THEN RAISE EXCEPTION 'boundary_crossing_contract_gap: allowed route kind missing'; END IF; RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION world_base.validate_spatial_v3_transition_allowed_route_kind() RETURNS TRIGGER AS $$
DECLARE contract_id_value TEXT:=COALESCE(NEW.transition_contract_id,OLD.transition_contract_id); contract_version_value INTEGER:=COALESCE(NEW.transition_contract_version,OLD.transition_contract_version);
BEGIN IF EXISTS(SELECT 1 FROM world_base.spatial_v3_spatial_transition_contracts t WHERE t.id=contract_id_value AND t.version=contract_version_value AND t.status='approved') AND NOT EXISTS(SELECT 1 FROM world_base.spatial_v3_spatial_transition_allowed_route_kinds WHERE transition_contract_id=contract_id_value AND transition_contract_version=contract_version_value) THEN RAISE EXCEPTION 'boundary_crossing_contract_gap: allowed route kind missing'; END IF; RETURN NULL; END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION world_base.validate_spatial_v3_boundary_dependencies() RETURNS TRIGGER AS $$
DECLARE sid TEXT; sv INTEGER; tid TEXT; tv INTEGER;
BEGIN
 IF TG_TABLE_NAME='spatial_v3_world_route_segment_spatial_contexts' THEN sid:=COALESCE(NEW.segment_id,OLD.segment_id); sv:=COALESCE(NEW.segment_version,OLD.segment_version); ELSE tid:=COALESCE(NEW.id,OLD.id); tv:=COALESCE(NEW.version,OLD.version); END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_boundary_crossing_contracts b JOIN world_base.spatial_v3_world_route_segment_spatial_contexts i ON i.segment_id=b.inbound_segment_id AND i.segment_version=b.inbound_segment_version JOIN world_base.spatial_v3_world_route_segment_spatial_contexts o ON o.segment_id=b.outbound_segment_id AND o.segment_version=b.outbound_segment_version JOIN world_base.spatial_v3_spatial_transition_contracts t ON t.id=b.transition_contract_id AND t.version=b.transition_contract_version WHERE ((sid IS NOT NULL AND ((i.segment_id=sid AND i.segment_version=sv) OR (o.segment_id=sid AND o.segment_version=sv))) OR (tid IS NOT NULL AND t.id=tid AND t.version=tv)) AND (i.canonical_digest<>b.from_context_digest OR o.canonical_digest<>b.to_context_digest OR (b.boundary_kind='g1_internal' AND t.transition_kind<>'g1_adjacency') OR (b.boundary_kind='g0_external' AND t.transition_kind<>'g0_external') OR (b.boundary_kind='jurisdiction_only' AND t.transition_kind<>'jurisdiction_only') OR (b.boundary_kind='combined' AND t.transition_kind<>'combined'))) THEN RAISE EXCEPTION 'boundary_crossing_contract_gap'; END IF; RETURN NULL;
END; $$ LANGUAGE plpgsql;
DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_orientation_frame_validation' AND tgrelid='world_base.spatial_v3_orientation_reference_frames'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_orientation_frame_validation AFTER INSERT OR UPDATE ON world_base.spatial_v3_orientation_reference_frames DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_orientation_frame(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_orientation_profile_validation' AND tgrelid='world_base.spatial_v3_movement_orientation_profiles'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_orientation_profile_validation AFTER INSERT OR UPDATE ON world_base.spatial_v3_movement_orientation_profiles DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_orientation_profile(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_directional_exit_validation' AND tgrelid='world_base.spatial_v3_g4_directional_exits'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_directional_exit_validation AFTER INSERT OR UPDATE ON world_base.spatial_v3_g4_directional_exits DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_directional_exit(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_orientation_profile_points_validation' AND tgrelid='world_base.spatial_v3_movement_orientation_profile_points'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_orientation_profile_points_validation AFTER INSERT OR UPDATE OR DELETE ON world_base.spatial_v3_movement_orientation_profile_points DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_orientation_profile_points(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_route_validation' AND tgrelid='world_base.spatial_v3_world_routes'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_route_validation AFTER INSERT OR UPDATE ON world_base.spatial_v3_world_routes DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_route(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_route_point_relation_validation' AND tgrelid='world_base.spatial_v3_world_route_points'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_route_point_relation_validation AFTER INSERT OR UPDATE OR DELETE ON world_base.spatial_v3_world_route_points DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.queue_spatial_v3_route_validation(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_route_segment_relation_validation' AND tgrelid='world_base.spatial_v3_world_route_segments'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_route_segment_relation_validation AFTER INSERT OR UPDATE OR DELETE ON world_base.spatial_v3_world_route_segments DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.queue_spatial_v3_route_validation(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_route_endpoint_relation_validation' AND tgrelid='world_base.spatial_v3_world_route_endpoint_bindings'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_route_endpoint_relation_validation AFTER INSERT OR UPDATE OR DELETE ON world_base.spatial_v3_world_route_endpoint_bindings DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.queue_spatial_v3_route_validation(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_route_context_relation_validation' AND tgrelid='world_base.spatial_v3_world_route_segment_spatial_contexts'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_route_context_relation_validation AFTER INSERT OR UPDATE OR DELETE ON world_base.spatial_v3_world_route_segment_spatial_contexts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.queue_spatial_v3_route_validation(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_boundary_context_dependency_validation' AND tgrelid='world_base.spatial_v3_world_route_segment_spatial_contexts'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_boundary_context_dependency_validation AFTER UPDATE OR DELETE ON world_base.spatial_v3_world_route_segment_spatial_contexts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_boundary_dependencies(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_boundary_validation' AND tgrelid='world_base.spatial_v3_boundary_crossing_contracts'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_boundary_validation AFTER INSERT OR UPDATE ON world_base.spatial_v3_boundary_crossing_contracts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_boundary(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_transition_contract_validation' AND tgrelid='world_base.spatial_v3_spatial_transition_contracts'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_transition_contract_validation AFTER INSERT OR UPDATE ON world_base.spatial_v3_spatial_transition_contracts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_transition_contract(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_boundary_transition_dependency_validation' AND tgrelid='world_base.spatial_v3_spatial_transition_contracts'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_boundary_transition_dependency_validation AFTER UPDATE OR DELETE ON world_base.spatial_v3_spatial_transition_contracts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_boundary_dependencies(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_transition_allowed_route_kind_validation' AND tgrelid='world_base.spatial_v3_spatial_transition_allowed_route_kinds'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_transition_allowed_route_kind_validation AFTER INSERT OR UPDATE OR DELETE ON world_base.spatial_v3_spatial_transition_allowed_route_kinds DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_transition_allowed_route_kind(); END IF;
END $$;

GRANT SELECT ON ALL TABLES IN SCHEMA world_base TO world_reader;
