-- Spatial architecture v3 / P11 finite expansion and scene authoring.
-- Target-only world authoring.  Party instances are deliberately owned by P13.

CREATE TABLE IF NOT EXISTS world_base.spatial_v3_terminal_policies (
  id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT,
  policy_kind TEXT NOT NULL CHECK(policy_kind IN ('connect_existing','world_route_exit','physical_boundary')), target_directional_exit_id TEXT, target_directional_exit_version INTEGER,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'),
  PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id),
  FOREIGN KEY(target_directional_exit_id,target_directional_exit_version) REFERENCES world_base.spatial_v3_g4_directional_exits(id,version) ON DELETE RESTRICT,
  CHECK((target_directional_exit_id IS NULL) = (target_directional_exit_version IS NULL))
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_continuation_length_rules (
  id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT,
  selection_kind TEXT NOT NULL CHECK(selection_kind IN ('fixed','deterministic_weighted')), status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'),
  PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id)
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_continuation_length_candidates (
  rule_id TEXT NOT NULL, rule_version INTEGER NOT NULL, terminal_ordinal INTEGER NOT NULL CHECK(terminal_ordinal>=0), weight INTEGER NOT NULL CHECK(weight>0),
  PRIMARY KEY(rule_id,rule_version,terminal_ordinal), FOREIGN KEY(rule_id,rule_version) REFERENCES world_base.spatial_v3_continuation_length_rules(id,version) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_g4_expansion_profiles (
  id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT, g4_id TEXT NOT NULL, g4_version INTEGER NOT NULL,
  adjacency_rule_set_id TEXT NOT NULL, adjacency_rule_set_version INTEGER NOT NULL, connectivity_rule_set_id TEXT NOT NULL, connectivity_rule_set_version INTEGER NOT NULL, seed_policy_id TEXT NOT NULL, seed_policy_version INTEGER NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'),
  PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), FOREIGN KEY(g4_id,g4_version,world_revision_id) REFERENCES world_base.spatial_v3_nodes(id,version,world_revision_id) ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_g5_generation_templates (
  id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT,
  g5_class_id TEXT NOT NULL CHECK(g5_class_id IN ('spatial.g5.compound','spatial.g5.parcel')), regional_template_id TEXT NOT NULL, regional_template_version INTEGER NOT NULL, scene_materialization_profile_id TEXT NOT NULL, scene_materialization_profile_version INTEGER NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'), PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id)
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_expansion_profile_template_limits (
  profile_id TEXT NOT NULL, profile_version INTEGER NOT NULL, template_id TEXT NOT NULL, template_version INTEGER NOT NULL, max_count INTEGER NOT NULL CHECK(max_count>0),
  PRIMARY KEY(profile_id,profile_version,template_id,template_version), FOREIGN KEY(profile_id,profile_version) REFERENCES world_base.spatial_v3_g4_expansion_profiles(id,version) ON DELETE CASCADE, FOREIGN KEY(template_id,template_version) REFERENCES world_base.spatial_v3_g5_generation_templates(id,version) ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_expansion_slots (
  id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT, profile_id TEXT NOT NULL, profile_version INTEGER NOT NULL, g4_id TEXT NOT NULL, g4_version INTEGER NOT NULL,
  continuation_role TEXT NOT NULL CHECK(continuation_role IN ('through','branch')), direction_context_id TEXT, directional_exit_id TEXT, directional_exit_version INTEGER, max_instances INTEGER NOT NULL CHECK(max_instances>0), continuation_length_rule_id TEXT, continuation_length_rule_version INTEGER, terminal_policy_id TEXT NOT NULL, terminal_policy_version INTEGER NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'),
  PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id), FOREIGN KEY(profile_id,profile_version) REFERENCES world_base.spatial_v3_g4_expansion_profiles(id,version) ON DELETE CASCADE, FOREIGN KEY(directional_exit_id,directional_exit_version) REFERENCES world_base.spatial_v3_g4_directional_exits(id,version) ON DELETE RESTRICT, FOREIGN KEY(continuation_length_rule_id,continuation_length_rule_version) REFERENCES world_base.spatial_v3_continuation_length_rules(id,version) ON DELETE RESTRICT, FOREIGN KEY(terminal_policy_id,terminal_policy_version) REFERENCES world_base.spatial_v3_terminal_policies(id,version) ON DELETE RESTRICT,
  CHECK((continuation_role='through') = (direction_context_id IS NOT NULL AND directional_exit_id IS NOT NULL AND continuation_length_rule_id IS NOT NULL)), CHECK((directional_exit_id IS NULL) = (directional_exit_version IS NULL)), CHECK((continuation_length_rule_id IS NULL) = (continuation_length_rule_version IS NULL))
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_expansion_slot_templates (
  slot_id TEXT NOT NULL, slot_version INTEGER NOT NULL, template_id TEXT NOT NULL, template_version INTEGER NOT NULL, selection_weight INTEGER NOT NULL CHECK(selection_weight>0), compatibility_rule_id TEXT, compatibility_rule_version INTEGER,
  PRIMARY KEY(slot_id,slot_version,template_id,template_version), FOREIGN KEY(slot_id,slot_version) REFERENCES world_base.spatial_v3_expansion_slots(id,version) ON DELETE CASCADE, FOREIGN KEY(template_id,template_version) REFERENCES world_base.spatial_v3_g5_generation_templates(id,version) ON DELETE RESTRICT,
  FOREIGN KEY(slot_id,slot_version,template_id,template_version) REFERENCES world_base.spatial_v3_expansion_slot_templates(slot_id,slot_version,template_id,template_version) DEFERRABLE INITIALLY DEFERRED
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_scene_templates (
  id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT, regional_template_id TEXT NOT NULL, regional_template_version INTEGER NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'), PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id)
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_scene_materialization_profiles (
  id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), world_revision_id TEXT NOT NULL REFERENCES world_base.spatial_v3_world_revisions(id) ON DELETE RESTRICT, source_kind TEXT NOT NULL CHECK(source_kind IN ('canonical_g5','g5_generation_template','transport_template','route_anchor_template')), source_entity_id TEXT NOT NULL, source_entity_version INTEGER NOT NULL, selection_rule_id TEXT NOT NULL, selection_rule_version INTEGER NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'), PRIMARY KEY(id,version), UNIQUE(id,version,world_revision_id)
);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_scene_materialization_candidates (profile_id TEXT NOT NULL, profile_version INTEGER NOT NULL, scene_template_id TEXT NOT NULL, scene_template_version INTEGER NOT NULL, weight INTEGER NOT NULL CHECK(weight>0), applicability_rule_id TEXT, applicability_rule_version INTEGER, PRIMARY KEY(profile_id,profile_version,scene_template_id,scene_template_version), FOREIGN KEY(profile_id,profile_version) REFERENCES world_base.spatial_v3_scene_materialization_profiles(id,version) ON DELETE CASCADE, FOREIGN KEY(scene_template_id,scene_template_version) REFERENCES world_base.spatial_v3_scene_templates(id,version) ON DELETE RESTRICT);
DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='spatial_v3_g5_template_scene_profile_fk') THEN
  ALTER TABLE world_base.spatial_v3_g5_generation_templates ADD CONSTRAINT spatial_v3_g5_template_scene_profile_fk FOREIGN KEY(scene_materialization_profile_id,scene_materialization_profile_version) REFERENCES world_base.spatial_v3_scene_materialization_profiles(id,version) DEFERRABLE INITIALLY DEFERRED;
 END IF;
END $$;
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_g6_template_slots (scene_template_id TEXT NOT NULL, scene_template_version INTEGER NOT NULL, scene_slot_key TEXT NOT NULL, physical_class_id TEXT NOT NULL CHECK(physical_class_id IN ('spatial.g6.enclosed','spatial.g6.semi_enclosed','spatial.g6.open','spatial.g6.water')), primary_scene_role_id TEXT NOT NULL, vertical_context_id TEXT NOT NULL CHECK(vertical_context_id IN ('surface','elevated','subsurface')), overhead_cover_id TEXT NOT NULL CHECK(overhead_cover_id IN ('none','partial','full')), intra_g6_visibility_mode TEXT NOT NULL CHECK(intra_g6_visibility_mode IN ('default_clear','explicit')), default_visibility_distance_band TEXT CHECK(default_visibility_distance_band IN ('near','short','medium')), acoustic_uniformity TEXT NOT NULL CHECK(acoustic_uniformity='uniform'), enclosing_structure_slot_key TEXT, PRIMARY KEY(scene_template_id,scene_template_version,scene_slot_key), FOREIGN KEY(scene_template_id,scene_template_version) REFERENCES world_base.spatial_v3_scene_templates(id,version) ON DELETE CASCADE, CHECK((intra_g6_visibility_mode='default_clear')=(default_visibility_distance_band IS NOT NULL)));
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_scene_position_templates (scene_template_id TEXT NOT NULL, scene_template_version INTEGER NOT NULL, position_slot_key TEXT NOT NULL, g6_scene_slot_key TEXT NOT NULL, instance_count INTEGER NOT NULL CHECK(instance_count>0), position_type_id TEXT NOT NULL, capacity INTEGER NOT NULL CHECK(capacity>0), access_class_id TEXT NOT NULL, PRIMARY KEY(scene_template_id,scene_template_version,position_slot_key), FOREIGN KEY(scene_template_id,scene_template_version,g6_scene_slot_key) REFERENCES world_base.spatial_v3_g6_template_slots(scene_template_id,scene_template_version,scene_slot_key) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_scene_endpoint_slots (scene_template_id TEXT NOT NULL, scene_template_version INTEGER NOT NULL, slot_key TEXT NOT NULL, endpoint_role TEXT NOT NULL CHECK(endpoint_role IN ('departure','arrival','both')), required_position_slot_key TEXT NOT NULL, required_position_instance_ordinal INTEGER NOT NULL CHECK(required_position_instance_ordinal>=0), PRIMARY KEY(scene_template_id,scene_template_version,slot_key), FOREIGN KEY(scene_template_id,scene_template_version,required_position_slot_key) REFERENCES world_base.spatial_v3_scene_position_templates(scene_template_id,scene_template_version,position_slot_key) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_portal_templates (id TEXT NOT NULL, version INTEGER NOT NULL CHECK(version>0), scene_template_id TEXT NOT NULL, scene_template_version INTEGER NOT NULL, portal_slot_key TEXT NOT NULL, portal_class_id TEXT NOT NULL, default_state TEXT NOT NULL CHECK(default_state IN ('open','closed','locked')), controlling_structure_slot_key TEXT, status TEXT NOT NULL CHECK(status IN ('approved','deprecated','retired')), provenance_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, canonical_digest TEXT NOT NULL CHECK(canonical_digest ~ '^[a-f0-9]{64}$'), PRIMARY KEY(id,version), UNIQUE(scene_template_id,scene_template_version,portal_slot_key), FOREIGN KEY(scene_template_id,scene_template_version) REFERENCES world_base.spatial_v3_scene_templates(id,version) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_stable_structure_templates (scene_template_id TEXT NOT NULL, scene_template_version INTEGER NOT NULL, structure_slot_key TEXT NOT NULL, structure_class_id TEXT NOT NULL, material_profile_id TEXT NOT NULL, material_profile_version INTEGER NOT NULL, state_profile_id TEXT NOT NULL, state_profile_version INTEGER NOT NULL, evidence_ref TEXT NOT NULL REFERENCES world_base.source_records(id) ON DELETE RESTRICT, PRIMARY KEY(scene_template_id,scene_template_version,structure_slot_key), FOREIGN KEY(scene_template_id,scene_template_version) REFERENCES world_base.spatial_v3_scene_templates(id,version) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_g5_successor_frontier_rules (g5_template_id TEXT NOT NULL, g5_template_version INTEGER NOT NULL, ordinal INTEGER NOT NULL CHECK(ordinal>=0), source_expansion_slot_id TEXT NOT NULL, source_expansion_slot_version INTEGER NOT NULL, successor_kind TEXT NOT NULL CHECK(successor_kind IN ('through_successor','branch_frontier')), target_expansion_slot_id TEXT NOT NULL, target_expansion_slot_version INTEGER NOT NULL, scene_endpoint_slot_key TEXT NOT NULL, terminal_policy_id TEXT NOT NULL, terminal_policy_version INTEGER NOT NULL, condition_rule_id TEXT, condition_rule_version INTEGER, PRIMARY KEY(g5_template_id,g5_template_version,ordinal), UNIQUE(g5_template_id,g5_template_version,source_expansion_slot_id,source_expansion_slot_version,successor_kind), FOREIGN KEY(g5_template_id,g5_template_version) REFERENCES world_base.spatial_v3_g5_generation_templates(id,version) ON DELETE CASCADE, FOREIGN KEY(source_expansion_slot_id,source_expansion_slot_version) REFERENCES world_base.spatial_v3_expansion_slots(id,version) ON DELETE RESTRICT, FOREIGN KEY(target_expansion_slot_id,target_expansion_slot_version) REFERENCES world_base.spatial_v3_expansion_slots(id,version) ON DELETE RESTRICT, FOREIGN KEY(terminal_policy_id,terminal_policy_version) REFERENCES world_base.spatial_v3_terminal_policies(id,version) ON DELETE RESTRICT, CHECK((condition_rule_id IS NULL)=(condition_rule_version IS NULL)));
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_scene_movement_edge_templates (scene_template_id TEXT NOT NULL, scene_template_version INTEGER NOT NULL, edge_slot_key TEXT NOT NULL, from_position_slot_key TEXT NOT NULL, to_position_slot_key TEXT NOT NULL, passage_type_id TEXT NOT NULL, transition_environment_profile_id TEXT NOT NULL, transition_environment_profile_version INTEGER NOT NULL, movement_orientation_profile_id TEXT NOT NULL, movement_orientation_profile_version INTEGER NOT NULL, cost_kind TEXT NOT NULL CHECK(cost_kind IN ('action','time')), action_units INTEGER CHECK(action_units>0), baseline_movement_method_id TEXT, movement_method_cost_profile_id TEXT, movement_method_cost_profile_version INTEGER, base_minutes INTEGER CHECK(base_minutes>0), dynamic_recheck_policy_id TEXT, dynamic_recheck_policy_version INTEGER, capacity INTEGER CHECK(capacity>0), portal_template_id TEXT, portal_template_version INTEGER, availability_condition_set_id TEXT, availability_condition_set_version INTEGER, reverse_edge_slot_key TEXT, PRIMARY KEY(scene_template_id,scene_template_version,edge_slot_key), FOREIGN KEY(scene_template_id,scene_template_version,from_position_slot_key) REFERENCES world_base.spatial_v3_scene_position_templates(scene_template_id,scene_template_version,position_slot_key) ON DELETE RESTRICT, FOREIGN KEY(scene_template_id,scene_template_version,to_position_slot_key) REFERENCES world_base.spatial_v3_scene_position_templates(scene_template_id,scene_template_version,position_slot_key) ON DELETE RESTRICT, FOREIGN KEY(portal_template_id,portal_template_version) REFERENCES world_base.spatial_v3_portal_templates(id,version) ON DELETE RESTRICT, CHECK((cost_kind='action' AND action_units IS NOT NULL AND baseline_movement_method_id IS NULL AND movement_method_cost_profile_id IS NULL AND movement_method_cost_profile_version IS NULL AND base_minutes IS NULL AND dynamic_recheck_policy_id IS NULL AND dynamic_recheck_policy_version IS NULL) OR (cost_kind='time' AND action_units IS NULL AND baseline_movement_method_id IS NOT NULL AND movement_method_cost_profile_id IS NOT NULL AND movement_method_cost_profile_version IS NOT NULL AND base_minutes IS NOT NULL AND dynamic_recheck_policy_id IS NOT NULL AND dynamic_recheck_policy_version IS NOT NULL)), CHECK((portal_template_id IS NULL)=(portal_template_version IS NULL)), CHECK((availability_condition_set_id IS NULL)=(availability_condition_set_version IS NULL)), CHECK(portal_template_id IS NULL OR availability_condition_set_id IS NOT NULL));
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_visibility_link_templates (scene_template_id TEXT NOT NULL, scene_template_version INTEGER NOT NULL, link_slot_key TEXT NOT NULL, from_position_slot_key TEXT NOT NULL, to_position_slot_key TEXT NOT NULL, quality TEXT NOT NULL CHECK(quality IN ('clear','partial')), distance_band TEXT NOT NULL CHECK(distance_band IN ('near','short','medium','long','remote')), portal_template_id TEXT, portal_template_version INTEGER, condition_profile_id TEXT, condition_profile_version INTEGER, reverse_link_slot_key TEXT, stable_asymmetry_evidence_ref TEXT REFERENCES world_base.source_records(id) ON DELETE RESTRICT, PRIMARY KEY(scene_template_id,scene_template_version,link_slot_key), FOREIGN KEY(scene_template_id,scene_template_version,from_position_slot_key) REFERENCES world_base.spatial_v3_scene_position_templates(scene_template_id,scene_template_version,position_slot_key) ON DELETE RESTRICT, FOREIGN KEY(scene_template_id,scene_template_version,to_position_slot_key) REFERENCES world_base.spatial_v3_scene_position_templates(scene_template_id,scene_template_version,position_slot_key) ON DELETE RESTRICT, FOREIGN KEY(portal_template_id,portal_template_version) REFERENCES world_base.spatial_v3_portal_templates(id,version) ON DELETE RESTRICT, CHECK((portal_template_id IS NULL)=(portal_template_version IS NULL)));
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_acoustic_edge_templates (scene_template_id TEXT NOT NULL, scene_template_version INTEGER NOT NULL, edge_slot_key TEXT NOT NULL, from_g6_scene_slot_key TEXT NOT NULL, to_g6_scene_slot_key TEXT NOT NULL, base_loss INTEGER NOT NULL CHECK(base_loss IN (0,1,2)), portal_template_id TEXT, portal_template_version INTEGER, closed_extra_loss TEXT CHECK(closed_extra_loss IN ('0','1','2','blocked')), reverse_edge_slot_key TEXT, condition_profile_id TEXT, condition_profile_version INTEGER, PRIMARY KEY(scene_template_id,scene_template_version,edge_slot_key), FOREIGN KEY(scene_template_id,scene_template_version,from_g6_scene_slot_key) REFERENCES world_base.spatial_v3_g6_template_slots(scene_template_id,scene_template_version,scene_slot_key) ON DELETE RESTRICT, FOREIGN KEY(scene_template_id,scene_template_version,to_g6_scene_slot_key) REFERENCES world_base.spatial_v3_g6_template_slots(scene_template_id,scene_template_version,scene_slot_key) ON DELETE RESTRICT, FOREIGN KEY(portal_template_id,portal_template_version) REFERENCES world_base.spatial_v3_portal_templates(id,version) ON DELETE RESTRICT, CHECK((portal_template_id IS NULL AND closed_extra_loss IS NULL) OR (portal_template_id IS NOT NULL AND closed_extra_loss IS NOT NULL AND condition_profile_id IS NOT NULL)), CHECK((portal_template_id IS NULL)=(portal_template_version IS NULL)));
CREATE TABLE IF NOT EXISTS world_base.spatial_v3_portal_state_template_behaviors (portal_template_id TEXT NOT NULL, portal_template_version INTEGER NOT NULL, relation_kind TEXT NOT NULL CHECK(relation_kind IN ('movement','visibility','acoustic')), state TEXT NOT NULL CHECK(state IN ('open','closed','locked','destroyed')), behavior_id TEXT NOT NULL, behavior_version INTEGER NOT NULL, PRIMARY KEY(portal_template_id,portal_template_version,relation_kind,state), FOREIGN KEY(portal_template_id,portal_template_version) REFERENCES world_base.spatial_v3_portal_templates(id,version) ON DELETE CASCADE);

CREATE OR REPLACE FUNCTION world_base.validate_spatial_v3_scene_authoring() RETURNS TRIGGER AS $$
DECLARE endpoint RECORD; position_count INTEGER;
BEGIN
 FOR endpoint IN SELECT * FROM world_base.spatial_v3_scene_endpoint_slots LOOP
  SELECT p.instance_count INTO position_count FROM world_base.spatial_v3_scene_position_templates p WHERE p.scene_template_id=endpoint.scene_template_id AND p.scene_template_version=endpoint.scene_template_version AND p.position_slot_key=endpoint.required_position_slot_key;
  IF position_count IS NULL OR endpoint.required_position_instance_ordinal>=position_count THEN RAISE EXCEPTION 'scene_endpoint_slot_missing'; END IF;
 END LOOP;
 RETURN NULL;
END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION world_base.validate_spatial_v3_normalized_scene_authoring() RETURNS TRIGGER AS $$
BEGIN
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_scene_materialization_profiles p LEFT JOIN world_base.spatial_v3_scene_materialization_candidates c ON c.profile_id=p.id AND c.profile_version=p.version WHERE p.status='approved' GROUP BY p.id,p.version HAVING count(c.scene_template_id)=0) THEN RAISE EXCEPTION 'controlled_vocabulary_gap: scene profile has empty candidate set'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_portal_templates p LEFT JOIN world_base.spatial_v3_stable_structure_templates s ON s.scene_template_id=p.scene_template_id AND s.scene_template_version=p.scene_template_version AND s.structure_slot_key=p.controlling_structure_slot_key WHERE p.controlling_structure_slot_key IS NOT NULL AND s.structure_slot_key IS NULL) THEN RAISE EXCEPTION 'generated_schema_mismatch'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_g6_template_slots g LEFT JOIN world_base.spatial_v3_stable_structure_templates s ON s.scene_template_id=g.scene_template_id AND s.scene_template_version=g.scene_template_version AND s.structure_slot_key=g.enclosing_structure_slot_key WHERE g.enclosing_structure_slot_key IS NOT NULL AND s.structure_slot_key IS NULL) THEN RAISE EXCEPTION 'generated_schema_mismatch'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_scene_position_templates p LEFT JOIN world_base.spatial_v3_scene_movement_edge_templates e ON e.scene_template_id=p.scene_template_id AND e.scene_template_version=p.scene_template_version AND (e.from_position_slot_key=p.position_slot_key OR e.to_position_slot_key=p.position_slot_key) LEFT JOIN world_base.spatial_v3_scene_endpoint_slots x ON x.scene_template_id=p.scene_template_id AND x.scene_template_version=p.scene_template_version AND x.required_position_slot_key=p.position_slot_key WHERE e.edge_slot_key IS NULL AND x.slot_key IS NULL) THEN RAISE EXCEPTION 'generated_schema_mismatch: orphan scene position'; END IF;
 IF EXISTS(
   SELECT 1
   FROM world_base.spatial_v3_scene_templates s
   CROSS JOIN LATERAL (
     WITH RECURSIVE reachable(position_slot_key) AS (
       SELECT min(p.position_slot_key) FROM world_base.spatial_v3_scene_position_templates p
       WHERE p.scene_template_id=s.id AND p.scene_template_version=s.version
       UNION
       SELECT CASE WHEN e.from_position_slot_key=r.position_slot_key THEN e.to_position_slot_key ELSE e.from_position_slot_key END
       FROM reachable r
       JOIN world_base.spatial_v3_scene_movement_edge_templates e
         ON e.scene_template_id=s.id AND e.scene_template_version=s.version
        AND (e.from_position_slot_key=r.position_slot_key OR e.to_position_slot_key=r.position_slot_key)
     ) SELECT count(*) AS reached_count FROM reachable WHERE reachable.position_slot_key IS NOT NULL
   ) reached
   CROSS JOIN LATERAL (
     SELECT count(*) AS position_count FROM world_base.spatial_v3_scene_position_templates p
     WHERE p.scene_template_id=s.id AND p.scene_template_version=s.version
   ) positions
   WHERE s.status='approved' AND (positions.position_count=0 OR reached.reached_count<>positions.position_count)
 ) THEN RAISE EXCEPTION 'generated_schema_mismatch: disconnected scene graph'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_g5_generation_templates t LEFT JOIN world_base.spatial_v3_scene_materialization_profiles p ON p.id=t.scene_materialization_profile_id AND p.version=t.scene_materialization_profile_version WHERE t.status='approved' AND (p.id IS NULL OR p.status<>'approved' OR p.world_revision_id<>t.world_revision_id OR p.source_kind<>'g5_generation_template' OR p.source_entity_id<>t.id OR p.source_entity_version<>t.version)) THEN RAISE EXCEPTION 'generated_schema_mismatch: template scene profile incompatible'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_expansion_slot_templates st JOIN world_base.spatial_v3_g5_generation_templates t ON t.id=st.template_id AND t.version=st.template_version LEFT JOIN world_base.spatial_v3_g5_successor_frontier_rules r ON r.g5_template_id=st.template_id AND r.g5_template_version=st.template_version AND r.source_expansion_slot_id=st.slot_id AND r.source_expansion_slot_version=st.slot_version WHERE t.status='approved' GROUP BY st.slot_id,st.slot_version,st.template_id,st.template_version HAVING count(r.ordinal)<>1) THEN RAISE EXCEPTION 'generated_schema_mismatch: successor applicability missing or ambiguous'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_g5_successor_frontier_rules r JOIN world_base.spatial_v3_g5_generation_templates t ON t.id=r.g5_template_id AND t.version=r.g5_template_version JOIN world_base.spatial_v3_scene_materialization_profiles p ON p.id=t.scene_materialization_profile_id AND p.version=t.scene_materialization_profile_version JOIN world_base.spatial_v3_scene_materialization_candidates c ON c.profile_id=p.id AND c.profile_version=p.version LEFT JOIN world_base.spatial_v3_scene_endpoint_slots e ON e.scene_template_id=c.scene_template_id AND e.scene_template_version=c.scene_template_version AND e.slot_key=r.scene_endpoint_slot_key WHERE e.slot_key IS NULL OR e.endpoint_role NOT IN ('departure','both')) THEN RAISE EXCEPTION 'scene_endpoint_slot_missing: successor endpoint incompatible'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_g5_successor_frontier_rules r JOIN world_base.spatial_v3_g5_generation_templates t ON t.id=r.g5_template_id AND t.version=r.g5_template_version JOIN world_base.spatial_v3_expansion_slots s ON s.id=r.target_expansion_slot_id AND s.version=r.target_expansion_slot_version JOIN world_base.spatial_v3_expansion_slots src ON src.id=r.source_expansion_slot_id AND src.version=r.source_expansion_slot_version WHERE t.world_revision_id<>s.world_revision_id OR src.profile_id<>s.profile_id OR src.profile_version<>s.profile_version OR (r.successor_kind='through_successor' AND (src.continuation_role<>'through' OR s.continuation_role<>'through' OR r.source_expansion_slot_id<>r.target_expansion_slot_id OR r.source_expansion_slot_version<>r.target_expansion_slot_version)) OR (r.successor_kind='branch_frontier' AND (src.continuation_role<>'branch' OR s.continuation_role<>'branch'))) THEN RAISE EXCEPTION 'generated_schema_mismatch: successor applicability invalid'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_scene_movement_edge_templates e JOIN world_base.spatial_v3_portal_templates p ON p.id=e.portal_template_id AND p.version=e.portal_template_version WHERE (p.scene_template_id,p.scene_template_version)<>(e.scene_template_id,e.scene_template_version) OR (e.portal_template_id IS NOT NULL AND (SELECT count(*) FROM world_base.spatial_v3_portal_state_template_behaviors b WHERE b.portal_template_id=e.portal_template_id AND b.portal_template_version=e.portal_template_version AND b.relation_kind='movement')<>4)) THEN RAISE EXCEPTION 'portal_state_behavior_incomplete'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_visibility_link_templates e JOIN world_base.spatial_v3_portal_templates p ON p.id=e.portal_template_id AND p.version=e.portal_template_version WHERE (p.scene_template_id,p.scene_template_version)<>(e.scene_template_id,e.scene_template_version) OR (e.portal_template_id IS NOT NULL AND (SELECT count(*) FROM world_base.spatial_v3_portal_state_template_behaviors b WHERE b.portal_template_id=e.portal_template_id AND b.portal_template_version=e.portal_template_version AND b.relation_kind='visibility')<>4)) THEN RAISE EXCEPTION 'portal_state_behavior_incomplete'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_acoustic_edge_templates e JOIN world_base.spatial_v3_portal_templates p ON p.id=e.portal_template_id AND p.version=e.portal_template_version WHERE (p.scene_template_id,p.scene_template_version)<>(e.scene_template_id,e.scene_template_version) OR (e.portal_template_id IS NOT NULL AND (SELECT count(*) FROM world_base.spatial_v3_portal_state_template_behaviors b WHERE b.portal_template_id=e.portal_template_id AND b.portal_template_version=e.portal_template_version AND b.relation_kind='acoustic')<>4)) THEN RAISE EXCEPTION 'portal_state_behavior_incomplete'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_scene_movement_edge_templates e LEFT JOIN world_base.spatial_v3_scene_movement_edge_templates r ON r.scene_template_id=e.scene_template_id AND r.scene_template_version=e.scene_template_version AND r.edge_slot_key=e.reverse_edge_slot_key WHERE e.reverse_edge_slot_key IS NOT NULL AND (r.edge_slot_key IS NULL OR r.from_position_slot_key<>e.to_position_slot_key OR r.to_position_slot_key<>e.from_position_slot_key OR r.reverse_edge_slot_key<>e.edge_slot_key)) THEN RAISE EXCEPTION 'generated_schema_mismatch'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_visibility_link_templates e LEFT JOIN world_base.spatial_v3_visibility_link_templates r ON r.scene_template_id=e.scene_template_id AND r.scene_template_version=e.scene_template_version AND r.link_slot_key=e.reverse_link_slot_key WHERE (e.portal_template_id IS NOT NULL AND e.condition_profile_id IS NULL) OR (e.reverse_link_slot_key IS NOT NULL AND (r.link_slot_key IS NULL OR r.from_position_slot_key<>e.to_position_slot_key OR r.to_position_slot_key<>e.from_position_slot_key OR r.reverse_link_slot_key<>e.link_slot_key)) OR (e.reverse_link_slot_key IS NULL AND e.stable_asymmetry_evidence_ref IS NULL)) THEN RAISE EXCEPTION 'portal_state_behavior_incomplete'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_acoustic_edge_templates e LEFT JOIN world_base.spatial_v3_acoustic_edge_templates r ON r.scene_template_id=e.scene_template_id AND r.scene_template_version=e.scene_template_version AND r.edge_slot_key=e.reverse_edge_slot_key WHERE (e.portal_template_id IS NOT NULL AND (e.condition_profile_id IS NULL OR e.condition_profile_version IS NULL)) OR (e.reverse_edge_slot_key IS NOT NULL AND (r.edge_slot_key IS NULL OR r.from_g6_scene_slot_key<>e.to_g6_scene_slot_key OR r.to_g6_scene_slot_key<>e.from_g6_scene_slot_key OR r.reverse_edge_slot_key<>e.edge_slot_key))) THEN RAISE EXCEPTION 'portal_state_behavior_incomplete'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_g5_successor_frontier_rules r JOIN world_base.spatial_v3_expansion_slots s ON s.id=r.target_expansion_slot_id AND s.version=r.target_expansion_slot_version WHERE (r.successor_kind='through_successor' AND s.continuation_role<>'through') OR (r.successor_kind='branch_frontier' AND s.continuation_role<>'branch')) THEN RAISE EXCEPTION 'generated_schema_mismatch'; END IF;
 RETURN NULL;
END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION world_base.validate_spatial_v3_expansion_authoring() RETURNS TRIGGER AS $$
BEGIN
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_expansion_slots s LEFT JOIN world_base.spatial_v3_expansion_slot_templates st ON st.slot_id=s.id AND st.slot_version=s.version WHERE s.status='approved' GROUP BY s.id,s.version HAVING count(st.template_id)=0) THEN RAISE EXCEPTION 'controlled_vocabulary_gap: expansion slot has empty candidate set'; END IF;
 IF EXISTS(SELECT 1 FROM world_base.spatial_v3_expansion_slot_templates st LEFT JOIN world_base.spatial_v3_expansion_profile_template_limits l ON l.profile_id=(SELECT s.profile_id FROM world_base.spatial_v3_expansion_slots s WHERE s.id=st.slot_id AND s.version=st.slot_version) AND l.profile_version=(SELECT s.profile_version FROM world_base.spatial_v3_expansion_slots s WHERE s.id=st.slot_id AND s.version=st.slot_version) AND l.template_id=st.template_id AND l.template_version=st.template_version WHERE l.template_id IS NULL) THEN RAISE EXCEPTION 'generated_schema_mismatch'; END IF;
 RETURN NULL;
END; $$ LANGUAGE plpgsql;
CREATE OR REPLACE FUNCTION world_base.validate_spatial_v3_endpoint_slot_binding() RETURNS TRIGGER AS $$
DECLARE expected_role TEXT; match_count INTEGER;
BEGIN
 SELECT count(*), min(e.endpoint_role) INTO match_count,expected_role FROM world_base.spatial_v3_scene_materialization_profiles p JOIN world_base.spatial_v3_scene_materialization_candidates c ON c.profile_id=p.id AND c.profile_version=p.version JOIN world_base.spatial_v3_scene_endpoint_slots e ON e.scene_template_id=c.scene_template_id AND e.scene_template_version=c.scene_template_version WHERE p.source_kind='canonical_g5' AND p.source_entity_id=NEW.canonical_g5_id AND p.source_entity_version=NEW.canonical_g5_version AND p.status='approved' AND e.slot_key=NEW.scene_endpoint_slot_key;
 IF expected_role IS NULL THEN RAISE EXCEPTION 'scene_endpoint_slot_missing'; END IF;
 IF match_count <> 1 THEN RAISE EXCEPTION 'scene_endpoint_slot_ambiguous'; END IF;
 IF (NEW.endpoint_role='from' AND expected_role NOT IN ('departure','both')) OR (NEW.endpoint_role='to' AND expected_role NOT IN ('arrival','both')) THEN RAISE EXCEPTION 'scene_endpoint_slot_ambiguous'; END IF;
 RETURN NEW;
END; $$ LANGUAGE plpgsql;
DO $$ DECLARE _table TEXT; BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_scene_authoring_validation' AND tgrelid='world_base.spatial_v3_scene_endpoint_slots'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_scene_authoring_validation AFTER INSERT OR UPDATE OR DELETE ON world_base.spatial_v3_scene_endpoint_slots DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_scene_authoring(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_scene_position_authoring_validation' AND tgrelid='world_base.spatial_v3_scene_position_templates'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_scene_position_authoring_validation AFTER INSERT OR UPDATE OR DELETE ON world_base.spatial_v3_scene_position_templates DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_scene_authoring(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_expansion_authoring_validation' AND tgrelid='world_base.spatial_v3_expansion_slot_templates'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_expansion_authoring_validation AFTER INSERT OR UPDATE OR DELETE ON world_base.spatial_v3_expansion_slot_templates DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_expansion_authoring(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_route_endpoint_slot_validation' AND tgrelid='world_base.spatial_v3_world_route_endpoint_bindings'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_route_endpoint_slot_validation AFTER INSERT OR UPDATE ON world_base.spatial_v3_world_route_endpoint_bindings DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_endpoint_slot_binding(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_scene_candidate_normalized_validation' AND tgrelid='world_base.spatial_v3_scene_materialization_candidates'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_scene_candidate_normalized_validation AFTER INSERT OR UPDATE OR DELETE ON world_base.spatial_v3_scene_materialization_candidates DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_normalized_scene_authoring(); END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='spatial_v3_scene_profile_normalized_validation' AND tgrelid='world_base.spatial_v3_scene_materialization_profiles'::regclass) THEN CREATE CONSTRAINT TRIGGER spatial_v3_scene_profile_normalized_validation AFTER INSERT OR UPDATE OR DELETE ON world_base.spatial_v3_scene_materialization_profiles DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_normalized_scene_authoring(); END IF;
 FOREACH _table IN ARRAY ARRAY['spatial_v3_scene_templates','spatial_v3_scene_movement_edge_templates','spatial_v3_visibility_link_templates','spatial_v3_acoustic_edge_templates','spatial_v3_g5_successor_frontier_rules','spatial_v3_g5_generation_templates','spatial_v3_expansion_slots','spatial_v3_expansion_slot_templates','spatial_v3_portal_templates','spatial_v3_portal_state_template_behaviors','spatial_v3_g6_template_slots','spatial_v3_stable_structure_templates','spatial_v3_scene_position_templates','spatial_v3_scene_endpoint_slots'] LOOP IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='p11_norm_' || substring(_table from 12) AND tgrelid=('world_base.' || _table)::regclass) THEN EXECUTE format('CREATE CONSTRAINT TRIGGER p11_norm_%s AFTER INSERT OR UPDATE OR DELETE ON world_base.%I DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION world_base.validate_spatial_v3_normalized_scene_authoring()', substring(_table from 12), _table); END IF; END LOOP;
END $$;
GRANT SELECT ON ALL TABLES IN SCHEMA world_base TO world_reader;
